import type { TriviaDeckData } from './trivia-decks';

/**
 * Practical Python recall for ML engineering work.
 *
 * Each card keeps the scenario and concept together: `answer` is the short
 * phrase the grader checks, while `explanation` supplies the production rule.
 */
export const practicalPythonTriviaDeck = {
  id: 'python-interview-trivia-v3',
  title: 'Practical Python for ML engineering',
  cards: [
    {
      id: 'python-aliasing-append',
      topic: 'References & values',
      question: 'What is `b` after `a = []; b = a; a.append("sample")`?',
      answer: '`["sample"]`',
      acceptedAnswers: ['[sample]'],
      explanation: 'Assignment aliases the same list instead of copying it, so mutation is visible through both names.',
    },
    {
      id: 'python-mutation-vs-rebinding',
      topic: 'References & values',
      code: 'def f(xs: list[int]) -> None:\n    xs.append(1)\n    xs = []\n\nitems: list[int] = []\nf(items)',
      question: 'What is `items` after `f(items)` returns?',
      answer: '`[1]`',
      acceptedAnswers: ['[1] because mutation is visible'],
      explanation: 'The append mutates the caller\'s list; assigning `xs = []` only rebinds the local name.',
    },
    {
      id: 'python-identity-vs-equality',
      topic: 'References & values',
      question: 'Which operators belong in `cached ___ None` and `prediction ___ target`?',
      answer: '`is` / `==`',
      acceptedAnswers: ['is and ==', 'is, =='],
      explanation: 'Use identity for `None` and sentinels, and equality for values.',
    },
    {
      id: 'python-missing-sentinel',
      topic: 'References & values',
      question: 'What should represent “not supplied” when `None` is a valid value?',
      answer: 'Sentinel',
      acceptedAnswers: ['MISSING', 'object sentinel'],
      explanation: 'A private object such as `MISSING = object()` creates a state distinct from every valid input.',
    },
    {
      id: 'python-shared-mutable-default',
      topic: 'References & values',
      code: 'def add(x: int, xs: list[int] = []) -> list[int]:\n    xs.append(x)\n    return xs',
      question: 'Why does `add` retain values across calls?',
      answer: 'Shared mutable default',
      acceptedAnswers: ['mutable default', 'default evaluated once'],
      explanation: 'Python creates the default list once when the function is defined; use `None` and allocate inside.',
    },
    {
      id: 'python-repeated-inner-list',
      topic: 'References & values',
      question: 'What is `rows` after `rows = [[]] * 3; rows[0].append(1)`?',
      answer: '`[[1], [1], [1]]`',
      acceptedAnswers: ['[[1],[1],[1]]'],
      explanation: 'List repetition copied one reference three times, so every row names the same inner list.',
    },
    {
      id: 'python-shallow-list-copy',
      topic: 'References & values',
      code: 'a = [{"lr": 1e-3}]\nb = a.copy()\nb[0]["lr"] = 1e-4',
      question: 'What value does `a[0]["lr"]` hold after the update through `b`?',
      answer: '`1e-4`',
      acceptedAnswers: ['0.0001'],
      explanation: '`list.copy()` creates a new outer list but keeps the nested dictionary shared.',
    },
    {
      id: 'python-tuple-shallow-immutability',
      topic: 'References & values',
      question: 'Does `cfg = ({"lr": 1e-3},); cfg[0]["lr"] = 1e-4` succeed?',
      answer: 'Yes',
      explanation: 'A tuple fixes its references but does not freeze the mutable objects stored in its slots.',
    },
    {
      id: 'python-falsy-valid-value',
      topic: 'References & values',
      question: 'How should `lr` default when `0.0` is valid and `None` means missing?',
      answer: 'Explicit `None` check',
      acceptedAnswers: ['if lr is None', 'is None'],
      explanation: '`supplied_lr or 1e-3` treats every falsy value as missing, including the valid value `0.0`.',
    },
    {
      id: 'python-nan-equality',
      topic: 'References & values',
      question: 'What does `x == x` return after `x = float("nan")`?',
      answer: '`False`',
      explanation: 'NaN is not equal to itself; detect it with `math.isnan(x)`.',
    },
    {
      id: 'python-float-comparison',
      topic: 'References & values',
      question: 'How should code compare `0.1 + 0.2` with `0.3`?',
      answer: '`math.isclose()`',
      acceptedAnswers: ['math.isclose', 'isclose'],
      explanation: 'Binary floating-point arithmetic is approximate, so equality checks need explicit relative and absolute tolerances.',
    },

    {
      id: 'python-list-vs-tuple',
      topic: 'Collections',
      question: 'Which types fit a mutable transform pipeline and a fixed `(scene_id, frame_id)` key?',
      answer: 'List / tuple',
      acceptedAnswers: ['list and tuple', 'list, tuple'],
      explanation: 'Use a list for a mutable sequence and a tuple for a fixed record or hashable composite key.',
    },
    {
      id: 'python-dict-key-contract',
      topic: 'Collections',
      question: 'What property must every dictionary key have?',
      answer: 'Hashable',
      acceptedAnswers: ['stable hash'],
      explanation: 'A key needs a stable hash and equality contract; strings, integers, and hashable tuples qualify, but lists do not.',
    },
    {
      id: 'python-set-deduplication',
      topic: 'Collections',
      question: 'Which collection should deduplicate IDs and support fast membership checks?',
      answer: '`set`',
      acceptedAnswers: ['set(ids)'],
      explanation: 'A set enforces uniqueness and supports average-case constant-time membership; sort it before deterministic output.',
    },
    {
      id: 'python-split-leakage-intersection',
      topic: 'Collections',
      question: 'What does `train_ids & val_ids` reveal when both values are sets?',
      answer: 'Split leakage',
      acceptedAnswers: ['set intersection', 'overlapping ids', 'intersection'],
      explanation: 'Set intersection returns the IDs present in both dataset splits.',
    },
    {
      id: 'python-dict-iteration-order',
      topic: 'Collections',
      question: 'Does iterating a dictionary produce keys in sorted order?',
      answer: 'No',
      explanation: 'Dictionaries preserve insertion order, which is distinct from sorted order.',
    },
    {
      id: 'python-sort-vs-sorted',
      topic: 'Collections',
      question: 'How do `xs.sort()` and `sorted(xs)` differ?',
      answer: 'In-place / new list',
      acceptedAnswers: ['mutates / copies', 'in place and copy'],
      explanation: '`sort()` mutates and returns `None`; `sorted()` returns a stable new list.',
    },
    {
      id: 'python-zip-strict',
      topic: 'Collections',
      question: 'How should labels and predictions be zipped when their lengths must match?',
      answer: '`zip(..., strict=True)`',
      acceptedAnswers: ['strict zip', 'zip strict true'],
      explanation: 'Plain `zip` silently stops at the shorter input, while strict mode raises `ValueError` on a mismatch.',
    },
    {
      id: 'python-counter-labels',
      topic: 'Collections',
      question: 'Which standard collection counts each label in a dataset?',
      answer: '`Counter`',
      acceptedAnswers: ['collections.Counter'],
      explanation: '`Counter(labels)` maps each distinct label to its frequency.',
    },
    {
      id: 'python-defaultdict-grouping',
      topic: 'Collections',
      question: 'Which collection groups paths by scene without manual list initialization?',
      answer: '`defaultdict(list)`',
      acceptedAnswers: ['defaultdict'],
      explanation: 'A `defaultdict(list)` calls `list()` for each missing scene key.',
    },
    {
      id: 'python-bounded-loss-history',
      topic: 'Collections',
      question: 'Which collection should retain only the most recent 100 losses?',
      answer: '`deque(maxlen=100)`',
      acceptedAnswers: ['bounded deque', 'deque'],
      explanation: 'A bounded deque automatically discards the oldest item and supports efficient operations at both ends.',
    },

    {
      id: 'python-iterable-vs-iterator',
      topic: 'Functions & iteration',
      question: 'How does an iterable differ from an iterator?',
      answer: '`iter()` / `next()`',
      acceptedAnswers: ['iterable creates iterator', 'source / cursor'],
      explanation: 'An iterable can create an iterator; an iterator stores traversal state and advances with `next()`.',
    },
    {
      id: 'python-generator-exhaustion',
      topic: 'Functions & iteration',
      code: 'g = (load(path) for path in paths)\nfirst_pass = list(g)\nsecond_pass = list(g)',
      question: 'What is `second_pass` after the first pass exhausts `g`?',
      answer: '`[]`',
      acceptedAnswers: ['empty list'],
      explanation: 'A generator is a one-shot iterator and remains exhausted after completion.',
    },
    {
      id: 'python-eager-vs-lazy-comprehension',
      topic: 'Functions & iteration',
      question: 'How do `[decode(p) for p in paths]` and `(decode(p) for p in paths)` evaluate?',
      answer: 'Eager / lazy',
      acceptedAnswers: ['list eager generator lazy'],
      explanation: 'The list computes and stores every result immediately; the generator computes during iteration.',
    },
    {
      id: 'python-yield-generator-function',
      topic: 'Functions & iteration',
      question: 'What does calling a function that contains `yield batch` return?',
      answer: 'Generator iterator',
      acceptedAnswers: ['generator'],
      explanation: 'Calling a generator function returns an iterator whose local frame resumes after each `yield`.',
    },
    {
      id: 'python-first-match',
      topic: 'Functions & iteration',
      question: 'What does `next((s for s in samples if s.id == target), None)` return?',
      answer: 'First match or `None`',
      acceptedAnswers: ['match or none', 'first match'],
      explanation: 'The generator stops at the first match and avoids constructing a temporary list.',
    },
    {
      id: 'python-keyword-only-hyperparameters',
      topic: 'Functions & iteration',
      code: 'def train(model: Model, *, epochs: int, lr: float) -> None:\n    ...',
      question: 'What does the bare `*` require for `epochs` and `lr`?',
      answer: 'Keyword-only arguments',
      acceptedAnswers: ['keyword only', 'keywords'],
      explanation: 'Callers must name the hyperparameters, which prevents two positional values from being silently swapped.',
    },
    {
      id: 'python-closure-late-binding',
      topic: 'Functions & iteration',
      question: 'What does `[f() for f in [lambda: i for i in range(3)]]` return?',
      answer: '`[2, 2, 2]`',
      acceptedAnswers: ['[2,2,2]'],
      explanation: 'Closures look up `i` when called; capture each loop value with `lambda i=i: i`.',
    },
    {
      id: 'python-partial-callable',
      topic: 'Functions & iteration',
      question: 'What does `partial(resize, size=224)` create?',
      answer: 'Pre-bound callable',
      acceptedAnswers: ['partial function', 'functools.partial', 'callable'],
      explanation: '`functools.partial` creates a callable with selected arguments already bound.',
    },
    {
      id: 'python-wraps-decorator',
      topic: 'Functions & iteration',
      question: 'Which decorator preserves a wrapped function’s metadata?',
      answer: '`@wraps`',
      acceptedAnswers: ['functools.wraps', 'wraps'],
      explanation: '`functools.wraps` preserves metadata such as `__name__`, `__doc__`, annotations, and `__wrapped__`.',
    },
    {
      id: 'python-lru-cache-contract',
      topic: 'Functions & iteration',
      question: 'When is `@lru_cache` appropriate for `load_schema(path)`?',
      answer: 'Pure, hashable calls',
      acceptedAnswers: ['pure function', 'hashable arguments'],
      explanation: 'Memoization assumes equivalent hashable arguments produce reusable results, and the cache retains arguments and return values.',
    },

    {
      id: 'python-instance-shadows-class',
      topic: 'Classes & interfaces',
      code: 'class C:\n    timeout = 30\n\na = C()\nb = C()\na.timeout = 10',
      question: 'What is `b.timeout` after assigning `a.timeout = 10`?',
      answer: '`30`',
      acceptedAnswers: ['30'],
      explanation: 'Assigning through `a` creates an instance attribute that shadows the shared class attribute only for `a`.',
    },
    {
      id: 'python-mutable-class-attribute',
      topic: 'Classes & interfaces',
      code: 'class Registry:\n    names: list[str] = []\n\na = Registry()\nb = Registry()\na.names.append("x")',
      question: 'What is `b.names` after mutating `a.names`?',
      answer: '`["x"]`',
      acceptedAnswers: ['[x]'],
      explanation: 'Both instances resolve `names` to the same mutable class attribute.',
    },
    {
      id: 'python-bound-method-self',
      topic: 'Classes & interfaces',
      question: 'What does accessing `obj.run` bind automatically?',
      answer: '`self`',
      acceptedAnswers: ['instance'],
      explanation: 'Instance attribute access turns the function on the class into a bound method carrying `obj` as `self`.',
    },
    {
      id: 'python-classmethod-constructor',
      topic: 'Classes & interfaces',
      question: 'What pattern does `@classmethod def from_dict(cls, data) -> Self` implement?',
      answer: 'Alternative constructor',
      acceptedAnswers: ['factory method'],
      explanation: 'Constructing through `cls` preserves the correct runtime class for subclasses.',
    },
    {
      id: 'python-staticmethod-helper',
      topic: 'Classes & interfaces',
      question: 'When should `validate_name` be a `staticmethod`?',
      answer: 'No receiver needed',
      acceptedAnswers: ['needs neither self nor cls', 'no self or cls'],
      explanation: 'A static method is a namespace-local helper that needs neither instance state nor class state.',
    },
    {
      id: 'python-property-boundary',
      topic: 'Classes & interfaces',
      question: 'When is `@property def num_samples(self)` a good interface?',
      answer: 'Cheap derived state',
      acceptedAnswers: ['computed attribute', 'cheap computation'],
      explanation: 'Properties fit cheap, unsurprising derived values; hidden expensive I/O should remain an explicit method.',
    },
    {
      id: 'python-callable-transform',
      topic: 'Classes & interfaces',
      question: 'Which method lets a configured transform object support `transform(sample)`?',
      answer: '`__call__`',
      explanation: '`__call__` makes an instance callable while keeping its configuration and state on the object.',
    },
    {
      id: 'python-composition-pipeline',
      topic: 'Classes & interfaces',
      question: 'Which design combines `Decode`, `Resize`, and `Normalize` without deep inheritance?',
      answer: 'Composition',
      acceptedAnswers: ['object composition'],
      explanation: 'A pipeline composes swappable behaviors and keeps each transform independently testable.',
    },
    {
      id: 'python-protocol-interface',
      topic: 'Classes & interfaces',
      question: 'Which typing construct accepts any object with `transform(sample)` without inheritance?',
      answer: '`Protocol`',
      acceptedAnswers: ['typing.Protocol', 'structural protocol'],
      explanation: 'A protocol defines a structural static interface based on available members.',
    },
    {
      id: 'python-super-mro',
      topic: 'Classes & interfaces',
      question: 'Where does `super().run()` dispatch?',
      answer: 'Next in the MRO',
      acceptedAnswers: ['method resolution order', 'next MRO implementation'],
      explanation: '`super()` continues after the current class in the runtime method resolution order, not necessarily at the textual parent.',
    },

    {
      id: 'python-annotations-runtime',
      topic: 'Typing',
      question: 'Does `def train(epochs: int): ...; train("10")` fail because of the annotation?',
      answer: 'No',
      explanation: 'Python stores annotations but does not enforce them at runtime unless another tool participates.',
    },
    {
      id: 'python-any-vs-object',
      topic: 'Typing',
      question: 'How do `Any` and `object` differ to a static type checker?',
      answer: 'Unchecked / unknown',
      acceptedAnswers: ['Any disables checking', 'dynamic / narrowing required'],
      explanation: '`Any` permits unchecked operations; `object` accepts every value but requires narrowing before type-specific operations.',
    },
    {
      id: 'python-nullable-not-optional',
      topic: 'Typing',
      question: 'Does `cache_dir: Path | None` make the function argument optional?',
      answer: 'No',
      explanation: 'The annotation permits `None`; the argument becomes optional to callers only when the signature also supplies a default.',
    },
    {
      id: 'python-sequence-parameter',
      topic: 'Typing',
      question: 'Which parameter type fits a collator that only indexes samples and reads their length?',
      answer: '`Sequence[Sample]`',
      acceptedAnswers: ['Sequence'],
      explanation: '`Sequence` promises ordered access and length without claiming the function will mutate the input.',
    },
    {
      id: 'python-iterable-vs-iterator-type',
      topic: 'Typing',
      question: 'What extra contract does `Iterator[Sample]` add beyond `Iterable[Sample]`?',
      answer: '`next()` and consumption',
      acceptedAnswers: ['next', 'stateful cursor'],
      explanation: 'An iterator is its own advancing traversal cursor, while an iterable only needs to produce an iterator.',
    },
    {
      id: 'python-mapping-parameter',
      topic: 'Typing',
      question: 'Which parameter type accepts dictionary-like configuration without promising mutation?',
      answer: '`Mapping[str, object]`',
      acceptedAnswers: ['Mapping'],
      explanation: '`Mapping` exposes read-only mapping operations and accepts more implementations than a concrete `dict` annotation.',
    },
    {
      id: 'python-callable-signature',
      topic: 'Typing',
      question: 'What does `Callable[[Sample], Sample]` require?',
      answer: 'Sample-to-Sample callable',
      acceptedAnswers: ['callable from Sample to Sample', 'function signature'],
      explanation: 'The value must be callable with one `Sample` and statically return a `Sample`.',
    },
    {
      id: 'python-typeddict-runtime',
      topic: 'Typing',
      question: 'Does `TypedDict` validate a dictionary loaded from JSON at runtime?',
      answer: 'No',
      explanation: '`TypedDict` describes dictionary shape to static checkers; the runtime value remains a normal dictionary.',
    },
    {
      id: 'python-literal-optimizer',
      topic: 'Typing',
      question: 'Which type restricts `optimizer` to the exact strings `"adam"` and `"sgd"`?',
      answer: '`Literal["adam", "sgd"]`',
      acceptedAnswers: ['Literal', 'typing.Literal'],
      explanation: '`Literal` lets a static checker reject other string values.',
    },
    {
      id: 'python-annotated-field',
      topic: 'Typing',
      question: 'What does `Annotated[int, Field(gt=0)]` communicate?',
      answer: '`int` plus metadata',
      acceptedAnswers: ['Annotated metadata', 'int with validation metadata'],
      explanation: 'Static type checkers see `int`, while Pydantic consumes the attached runtime constraint.',
    },
    {
      id: 'python-typevar-relationship',
      topic: 'Typing',
      code: 'T = TypeVar("T")\n\ndef first(xs: Sequence[T]) -> T:\n    return xs[0]',
      question: 'What relationship does `T` preserve in `first`?',
      answer: 'Element-to-return type',
      acceptedAnswers: ['same input and output type', 'generic relationship'],
      explanation: 'The return type stays tied to the sequence element type instead of collapsing to `object` or `Any`.',
    },

    {
      id: 'python-dataclass-generated-methods',
      topic: 'Dataclasses',
      question: 'What does plain `@dataclass` normally generate?',
      answer: '`__init__`, `__repr__`, `__eq__`',
      acceptedAnswers: ['init repr eq'],
      explanation: 'A standard dataclass generates common methods from annotated fields but does not validate field types at runtime.',
    },
    {
      id: 'python-dataclass-mutable-default',
      topic: 'Dataclasses',
      question: 'How should a dataclass declare `tags` with a fresh empty list per instance?',
      answer: '`field(default_factory=list)`',
      acceptedAnswers: ['default_factory=list', 'default factory'],
      explanation: 'A default factory creates a new list for each instance; an unhashable list default is rejected.',
    },
    {
      id: 'python-dataclass-post-init',
      topic: 'Dataclasses',
      question: 'Where should a dataclass enforce `warmup_steps < total_steps`?',
      answer: '`__post_init__`',
      acceptedAnswers: ['post init'],
      explanation: 'The generated initializer assigns all fields before `__post_init__` checks cross-field invariants.',
    },
    {
      id: 'python-dataclass-classvar',
      topic: 'Dataclasses',
      question: 'What does `VERSION: ClassVar[str] = "v2"` declare in a dataclass?',
      answer: 'Class variable',
      acceptedAnswers: ['ClassVar'],
      explanation: '`ClassVar` excludes the name from dataclass fields and the generated initializer.',
    },
    {
      id: 'python-dataclass-frozen-shallow',
      topic: 'Dataclasses',
      question: 'Can a list field inside `@dataclass(frozen=True)` still mutate?',
      answer: 'Yes',
      explanation: 'Frozen dataclasses block normal field rebinding but do not recursively freeze referenced objects.',
    },
    {
      id: 'python-dataclass-kw-only',
      topic: 'Dataclasses',
      question: 'What does `@dataclass(kw_only=True)` require at construction?',
      answer: 'Named fields',
      acceptedAnswers: ['keyword arguments', 'keyword-only fields'],
      explanation: 'Every generated initializer parameter must be supplied by keyword.',
    },
    {
      id: 'python-dataclass-slots',
      topic: 'Dataclasses',
      question: 'What is the usual effect of `@dataclass(slots=True)`?',
      answer: 'Generated slots',
      acceptedAnswers: ['__slots__', 'lower instance overhead'],
      explanation: 'The decorator generates slots, which usually reduce per-instance overhead and prevent undeclared attributes.',
    },
    {
      id: 'python-dataclass-replace',
      topic: 'Dataclasses',
      question: 'How should code create a modified configuration without mutating the dataclass instance?',
      answer: '`dataclasses.replace()`',
      acceptedAnswers: ['replace', 'dataclasses.replace'],
      explanation: '`replace(cfg, lr=...)` creates a new instance through the initializer and reruns `__post_init__`.',
    },
    {
      id: 'python-dataclass-asdict',
      topic: 'Dataclasses',
      question: 'Why can `asdict(state)` be risky when fields hold large runtime objects?',
      answer: 'Recursive deep copy',
      acceptedAnswers: ['deep copy', 'recursive conversion'],
      explanation: '`asdict` recurses through nested containers and deep-copies other objects; serialize selected metadata instead.',
    },

    {
      id: 'python-pydantic-boundary-choice',
      topic: 'Pydantic v2',
      question: 'Which defaults fit a trusted internal record and an external configuration boundary?',
      answer: 'Dataclass / `BaseModel`',
      acceptedAnswers: ['dataclass and BaseModel', 'dataclass, BaseModel'],
      explanation: 'Use the lightweight record internally and Pydantic runtime validation where untrusted or serialized data enters.',
    },
    {
      id: 'python-pydantic-dataclass',
      topic: 'Pydantic v2',
      question: 'What does `@pydantic.dataclasses.dataclass` add to dataclass ergonomics?',
      answer: 'Runtime validation',
      acceptedAnswers: ['validated dataclass', 'Pydantic validation'],
      explanation: 'Pydantic validates construction; use `TypeAdapter` when model-style validation, dump, or schema APIs are needed.',
    },
    {
      id: 'python-pydantic-default-coercion',
      topic: 'Pydantic v2',
      question: 'What is `RunConfig(epochs="10").epochs` under default Pydantic settings?',
      answer: '`10` as an `int`',
      acceptedAnswers: ['10', 'integer 10', 'int 10'],
      explanation: 'Pydantic uses coercive validation by default and converts compatible strings to integers.',
    },
    {
      id: 'python-pydantic-strict-mode',
      topic: 'Pydantic v2',
      question: 'How should a model reject the string `"10"` for an integer field?',
      answer: 'Strict mode',
      acceptedAnswers: ['strict=True', 'ConfigDict(strict=True)'],
      explanation: 'Enable strict validation on the model, field, or individual validation call.',
    },
    {
      id: 'python-pydantic-extra-forbid',
      topic: 'Pydantic v2',
      question: 'Which configuration catches a misspelled key such as `batch_szie`?',
      answer: '`ConfigDict(extra="forbid")`',
      acceptedAnswers: ['extra forbid', 'extra="forbid"'],
      explanation: 'Forbidding extra fields turns unknown keys into validation errors instead of silently ignoring them.',
    },
    {
      id: 'python-pydantic-positive-field',
      topic: 'Pydantic v2',
      question: 'How should a Pydantic field require `batch_size > 0`?',
      answer: '`Field(gt=0)`',
      acceptedAnswers: ['gt=0', 'Field greater than zero'],
      explanation: 'A declarative field constraint produces validation and schema metadata from the same rule.',
    },
    {
      id: 'python-pydantic-default-factory',
      topic: 'Pydantic v2',
      question: 'How should a Pydantic model give every instance a fresh `tags` list?',
      answer: '`Field(default_factory=list)`',
      acceptedAnswers: ['default_factory=list', 'default factory'],
      explanation: 'The factory runs for each model instance instead of sharing one mutable list.',
    },
    {
      id: 'python-pydantic-field-validator',
      topic: 'Pydantic v2',
      question: 'Which validator should normalize one field such as `model_name`?',
      answer: '`@field_validator`',
      acceptedAnswers: ['field_validator', 'field validator'],
      explanation: 'A field validator checks or transforms one field; `mode="before"` receives the raw input.',
    },
    {
      id: 'python-pydantic-model-validator',
      topic: 'Pydantic v2',
      question: 'Which validator should enforce `warmup_steps < total_steps`?',
      answer: '`@model_validator`',
      acceptedAnswers: ['model_validator', 'model validator'],
      explanation: 'An after-model validator sees the parsed model and can enforce invariants across fields.',
    },
    {
      id: 'python-pydantic-assignment-validation',
      topic: 'Pydantic v2',
      question: 'Which configuration revalidates `cfg.batch_size = "bad"` after construction?',
      answer: '`validate_assignment=True`',
      acceptedAnswers: ['validate assignment', 'ConfigDict(validate_assignment=True)'],
      explanation: 'Pydantic does not revalidate ordinary field assignment unless assignment validation is enabled.',
    },
    {
      id: 'python-pydantic-io-api',
      topic: 'Pydantic v2',
      question: 'Which Pydantic v2 API pair validates Python input and returns Python output?',
      answer: '`model_validate` / `model_dump`',
      acceptedAnswers: ['model_validate and model_dump', 'validate / dump'],
      explanation: 'Use `model_validate_json` and `model_dump_json` at JSON byte or string boundaries.',
    },
    {
      id: 'python-pydantic-type-adapter',
      topic: 'Pydantic v2',
      question: 'How should code validate `list[Sample]` without a wrapper model?',
      answer: '`TypeAdapter(list[Sample])`',
      acceptedAnswers: ['TypeAdapter', 'type adapter'],
      explanation: 'A reusable `TypeAdapter` validates, serializes, and produces schemas for arbitrary annotated types.',
    },
    {
      id: 'python-pydantic-private-attr',
      topic: 'Pydantic v2',
      question: 'How should a model store a runtime-only cache or database client?',
      answer: '`PrivateAttr`',
      acceptedAnswers: ['private attribute'],
      explanation: 'Private attributes stay outside normal fields, validation, schema generation, and serialization.',
    },
    {
      id: 'python-pydantic-arbitrary-tensor',
      topic: 'Pydantic v2',
      question: 'What does `arbitrary_types_allowed=True` validate for a `torch.Tensor` field?',
      answer: '`isinstance` only',
      acceptedAnswers: ['instance type only', 'type only'],
      explanation: 'The setting checks the runtime class, not tensor shape, dtype, values, layout, or device.',
    },
    {
      id: 'python-pydantic-model-construct',
      topic: 'Pydantic v2',
      question: 'Which API constructs a model from already trusted data without validation?',
      answer: '`model_construct()`',
      acceptedAnswers: ['model_construct'],
      explanation: '`model_construct()` bypasses validation; use it only for trusted data and profile before assuming it is faster.',
    },
    {
      id: 'python-pydantic-model-copy',
      topic: 'Pydantic v2',
      question: 'Does `cfg.model_copy()` normally copy nested model state deeply?',
      answer: 'No',
      explanation: '`model_copy()` is shallow by default; pass `deep=True` when nested objects must be copied.',
    },
    {
      id: 'python-pydantic-discriminated-union',
      topic: 'Pydantic v2',
      question: 'Which construct models Adam and SGD configurations with different required fields?',
      answer: 'Discriminated union',
      acceptedAnswers: ['tagged union', 'Field discriminator'],
      explanation: 'Give each model a shared `Literal` tag and select the variant with `Field(discriminator="type")`.',
    },

    {
      id: 'python-narrow-exception',
      topic: 'Reliability & I/O',
      question: 'Should configuration parsing catch every `Exception`?',
      answer: 'No',
      explanation: 'Catch the failures the boundary can handle and let unrelated programming errors remain visible.',
    },
    {
      id: 'python-explicit-exception-cause',
      topic: 'Reliability & I/O',
      question: 'What does `raise ConfigError(path) from exc` preserve?',
      answer: 'Explicit cause',
      acceptedAnswers: ['exception cause', 'traceback chain', '__cause__'],
      explanation: 'Exception chaining preserves the original failure and its traceback while adding boundary-specific context.',
    },
    {
      id: 'python-context-manager-cleanup',
      topic: 'Reliability & I/O',
      question: 'What guarantee does `with open(path) as handle:` provide?',
      answer: 'Exit-time cleanup',
      acceptedAnswers: ['file cleanup', 'close on exit', 'context manager'],
      explanation: 'The context manager runs its exit logic on both normal completion and exceptions.',
    },
    {
      id: 'python-assert-input-validation',
      topic: 'Reliability & I/O',
      question: 'Should `assert` validate user configuration or file contents?',
      answer: 'No',
      explanation: 'Optimization can remove assertions; raise an explicit exception for runtime input validation.',
    },
    {
      id: 'python-str-vs-bytes',
      topic: 'Reliability & I/O',
      question: 'How do `str` and `bytes` differ at an I/O boundary?',
      answer: 'Unicode / raw bytes',
      acceptedAnswers: ['text / bytes', 'Unicode text / octets'],
      explanation: 'A string holds Unicode text, while bytes hold raw octets; encode and decode explicitly at the boundary.',
    },
    {
      id: 'python-sorted-glob',
      topic: 'Reliability & I/O',
      question: 'How should reproducible ingestion consume `Path(root).glob("*.json")`?',
      answer: '`sorted(...)`',
      acceptedAnswers: ['sort the paths', 'sorted'],
      explanation: 'Filesystem enumeration order is not a reproducibility guarantee.',
    },
    {
      id: 'python-untrusted-pickle',
      topic: 'Reliability & I/O',
      question: 'Should code unpickle a checkpoint or cache from an untrusted source?',
      answer: 'No',
      explanation: 'Pickle can execute attacker-controlled code during loading, so only unpickle data you trust.',
    },
    {
      id: 'python-stable-experiment-id',
      topic: 'Reliability & I/O',
      question: 'How should code derive a persistent experiment ID from canonical configuration bytes?',
      answer: '`hashlib` digest',
      acceptedAnswers: ['cryptographic hash', 'stable digest', 'hashlib'],
      explanation: 'A stable cryptographic digest survives processes and runs; object identity and Python\'s process-local hash do not.',
    },
    {
      id: 'python-multiprocessing-entrypoint',
      topic: 'Reliability & I/O',
      question: 'What makes a multiprocessing script safe under the spawn start method?',
      answer: 'Main guard and top-level worker',
      acceptedAnswers: ['if __name__ main', 'main guard', 'spawn-safe entrypoint'],
      explanation: 'Protect process creation with `if __name__ == "__main__"` and keep worker callables importable and picklable.',
    },
    {
      id: 'python-concurrency-choice',
      topic: 'Reliability & I/O',
      question: 'Which defaults fit blocking downloads, CPU-heavy Python preprocessing, and cooperative network I/O?',
      answer: 'Threads / processes / `asyncio`',
      acceptedAnswers: ['threads, processes, asyncio', 'threads processes asyncio'],
      explanation: 'Threads overlap blocking I/O, processes bypass the traditional GIL for Python CPU work, and `asyncio` coordinates nonblocking I/O.',
    },
  ],
} satisfies TriviaDeckData;
