import type { TriviaDeckData } from './trivia-decks';
import { expandedPythonTriviaCards } from './python-expanded-trivia';
import { pythonTriviaDetails } from './python-trivia-details';

/**
 * Practical Python recall for ML engineering work.
 *
 * Each card keeps the scenario and concept together: `answer` is the short
 * phrase the grader checks, while `explanation` supplies the production rule.
 */
const practicalPythonTriviaSourceDeck = {
  id: 'python-interview-trivia-v4',
  title: 'Practical Python for ML engineering',
  cards: [
    {
      id: 'python-aliasing-append',
      topic: 'References & values',
      code: 'a: list[str] = []\nb = a\na.append("sample")',
      question: 'What value does `b` contain?',
      answer: '`["sample"]`',
      acceptedAnswers: ['[sample]'],
      explanation: 'Assignment aliases the same list instead of copying it, so mutation is visible through both names.',
    },
    {
      id: 'python-mutation-vs-rebinding',
      topic: 'References & values',
      code: 'def f(xs: list[int]) -> None:\n    xs.append(1)\n    xs = []\n\nitems: list[int] = []\nf(items)',
      question: 'What is `items` after `f(items)` returns?',
      answer: '`[1]`',
      acceptedAnswers: ['[1] because mutation is visible'],
      explanation: 'The append mutates the caller\'s list; assigning `xs = []` only rebinds the local name.',
    },
    {
      id: 'python-identity-vs-equality',
      topic: 'References & values',
      code: 'cached ___ None\nprediction ___ target',
      question: 'Which operator belongs in each blank?',
      answer: '`is` / `==`',
      acceptedAnswers: ['is and ==', 'is, =='],
      explanation: 'Use identity for `None` and sentinels, and equality for values.',
    },
    {
      id: 'python-missing-sentinel',
      topic: 'References & values',
      code: 'MISSING = object()\n\ndef load(value: object = MISSING) -> object:\n    ...',
      question: 'What should represent “not supplied” when `None` is a valid value?',
      answer: 'Sentinel',
      acceptedAnswers: ['MISSING', 'object sentinel'],
      explanation: 'A private object such as `MISSING = object()` creates a state distinct from every valid input.',
    },
    {
      id: 'python-shared-mutable-default',
      topic: 'References & values',
      code: 'def add(x: int, xs: list[int] = []) -> list[int]:\n    xs.append(x)\n    return xs',
      question: 'Why does `add` retain values across calls?',
      answer: 'Shared mutable default',
      acceptedAnswers: ['mutable default', 'default evaluated once'],
      explanation: 'Python creates the default list once when the function is defined; use `None` and allocate inside.',
    },
    {
      id: 'python-repeated-inner-list',
      topic: 'References & values',
      code: 'rows: list[list[int]] = [[]] * 3\nrows[0].append(1)',
      question: 'What value does `rows` contain?',
      answer: '`[[1], [1], [1]]`',
      acceptedAnswers: ['[[1],[1],[1]]'],
      explanation: 'List repetition copied one reference three times, so every row names the same inner list.',
    },
    {
      id: 'python-shallow-list-copy',
      topic: 'References & values',
      code: 'a = [{"lr": 1e-3}]\nb = a.copy()\nb[0]["lr"] = 1e-4',
      question: 'What value does `a[0]["lr"]` hold after the update through `b`?',
      answer: '`1e-4`',
      acceptedAnswers: ['0.0001'],
      explanation: '`list.copy()` creates a new outer list but keeps the nested dictionary shared.',
    },
    {
      id: 'python-tuple-shallow-immutability',
      topic: 'References & values',
      code: 'cfg = ({"lr": 1e-3},)\ncfg[0]["lr"] = 1e-4',
      question: 'Does the assignment succeed?',
      answer: 'Yes',
      explanation: 'A tuple fixes its references but does not freeze the mutable objects stored in its slots.',
    },
    {
      id: 'python-falsy-valid-value',
      topic: 'References & values',
      code: 'lr = 1e-3 if supplied_lr is None else supplied_lr',
      question: 'How should `lr` default when `0.0` is valid and `None` means missing?',
      answer: 'Explicit `None` check',
      acceptedAnswers: ['if lr is None', 'is None'],
      explanation: '`supplied_lr or 1e-3` treats every falsy value as missing, including the valid value `0.0`.',
    },
    {
      id: 'python-nan-equality',
      topic: 'References & values',
      code: 'x = float("nan")\nresult = x == x',
      question: 'What value does `result` contain?',
      answer: '`False`',
      explanation: 'NaN is not equal to itself; detect it with `math.isnan(x)`.',
    },
    {
      id: 'python-float-comparison',
      topic: 'References & values',
      code: 'actual = 0.1 + 0.2\nexpected = 0.3',
      question: 'How should code compare `actual` with `expected`?',
      answer: '`math.isclose()`',
      acceptedAnswers: ['math.isclose', 'isclose'],
      explanation: 'Binary floating-point arithmetic is approximate, so equality checks need explicit relative and absolute tolerances.',
    },

    {
      id: 'python-list-vs-tuple',
      topic: 'Collections',
      code: 'pipeline = [decode, resize, normalize]\ncache_key = (scene_id, frame_id)',
      question: 'Which collection contract fits each value?',
      answer: 'List / tuple',
      acceptedAnswers: ['list and tuple', 'list, tuple'],
      explanation: 'Use a list for a mutable sequence and a tuple for a fixed record or hashable composite key.',
    },
    {
      id: 'python-dict-key-contract',
      topic: 'Collections',
      question: 'What property must every dictionary key have?',
      answer: 'Hashable',
      acceptedAnswers: ['stable hash'],
      explanation: 'A key needs a stable hash and equality contract; strings, integers, and hashable tuples qualify, but lists do not.',
    },
    {
      id: 'python-set-deduplication',
      topic: 'Collections',
      question: 'Which collection should deduplicate IDs and support fast membership checks?',
      answer: '`set`',
      acceptedAnswers: ['set(ids)'],
      explanation: 'A set enforces uniqueness and supports average-case constant-time membership; sort it before deterministic output.',
    },
    {
      id: 'python-split-leakage-intersection',
      topic: 'Collections',
      code: 'overlap = train_ids & val_ids',
      question: 'Which dataset-splitting problem does a nonempty intersection of `train_ids` and `val_ids` indicate?',
      answer: 'Split leakage',
      acceptedAnswers: ['set intersection', 'overlapping ids', 'intersection'],
      explanation: 'Set intersection returns the IDs present in both dataset splits.',
    },
    {
      id: 'python-dict-iteration-order',
      topic: 'Collections',
      question: 'Does iterating a dictionary produce keys in sorted order?',
      answer: 'No',
      explanation: 'Dictionaries preserve insertion order, which is distinct from sorted order.',
    },
    {
      id: 'python-sort-vs-sorted',
      topic: 'Collections',
      code: 'result_a = xs.sort()\nresult_b = sorted(xs)',
      question: 'How do the two operations differ?',
      answer: 'In-place / new list',
      acceptedAnswers: ['mutates / copies', 'in place and copy'],
      explanation: '`sort()` mutates and returns `None`; `sorted()` returns a stable new list.',
    },
    {
      id: 'python-zip-strict',
      topic: 'Collections',
      code: 'for label, prediction in zip(labels, predictions):\n    evaluate(label, prediction)',
      question: 'How should this loop change so unequal input lengths raise an error instead of silently dropping data?',
      answer: '`zip(..., strict=True)`',
      acceptedAnswers: ['strict zip', 'zip strict true'],
      explanation: 'Plain `zip` silently stops at the shorter input, while strict mode raises `ValueError` on a mismatch.',
    },
    {
      id: 'python-counter-labels',
      topic: 'Collections',
      question: 'Which standard collection counts each label in a dataset?',
      answer: '`Counter`',
      acceptedAnswers: ['collections.Counter'],
      explanation: '`Counter(labels)` maps each distinct label to its frequency.',
    },
    {
      id: 'python-defaultdict-grouping',
      topic: 'Collections',
      code: 'paths_by_scene[scene_id].append(path)',
      question: 'Which collection lets this append work when `scene_id` does not yet have a list?',
      answer: '`defaultdict(list)`',
      acceptedAnswers: ['defaultdict'],
      explanation: 'A `defaultdict(list)` calls `list()` the first time a `scene_id` key is missing.',
    },
    {
      id: 'python-bounded-loss-history',
      topic: 'Collections',
      question: 'Which collection retains only the 100 most recently appended items?',
      answer: '`deque(maxlen=100)`',
      acceptedAnswers: ['bounded deque', 'deque'],
      explanation: 'A bounded deque automatically discards the oldest item and supports efficient operations at both ends.',
    },

    {
      id: 'python-iterable-vs-iterator',
      topic: 'Functions & iteration',
      question: 'How does an iterable differ from an iterator?',
      answer: 'An iterable produces an iterator; an iterator tracks progress',
      acceptedAnswers: ['iterable creates iterator', 'source / cursor', 'iterable is a source, iterator is stateful'],
      explanation: 'An iterable can create an iterator; an iterator stores traversal state and advances with `next()`.',
    },
    {
      id: 'python-generator-exhaustion',
      topic: 'Functions & iteration',
      code: 'g = (x * 2 for x in [1, 2, 3])\nfirst_pass = list(g)\nsecond_pass = list(g)',
      question: 'What value is assigned to `second_pass` after `first_pass` consumes `g`?',
      answer: '`[]` because `g` is exhausted',
      acceptedAnswers: ['[]', 'empty list', 'generator exhausted'],
      explanation: '`first_pass` consumes all values from `g` and becomes `[2, 4, 6]`. The same generator has no values left, so `second_pass` becomes `[]`.',
    },
    {
      id: 'python-eager-vs-lazy-comprehension',
      topic: 'Functions & iteration',
      code: 'def double(x: int) -> int:\n    print(f"processing {x}")\n    return x * 2\n\neager = [double(x) for x in [1, 2, 3]]\nlazy = (double(x) for x in [1, 2, 3])\nfirst = next(lazy)',
      question: 'When does `double` run for `eager` and `lazy`?',
      answer: 'Immediately for `eager`; on demand for `lazy`',
      acceptedAnswers: ['eager / lazy', 'list eager generator lazy', 'during construction / during iteration'],
      explanation: '`eager` calls `double` three times when the list is created. Creating `lazy` calls it zero times; `next(lazy)` calls it once and returns `2`.',
    },
    {
      id: 'python-yield-generator-function',
      topic: 'Functions & iteration',
      code: 'def count_up_to(limit: int) -> Iterator[int]:\n    print("started")\n    for value in range(limit):\n        yield value\n\nresult = count_up_to(3)',
      question: 'What is `result`, and when will `started` print?',
      answer: 'Generator; when iteration starts',
      acceptedAnswers: ['generator', 'generator iterator', 'generator object', 'lazy iterator'],
      explanation: '`result` is a generator object. Calling `count_up_to` does not run its body; `started` prints when `next(result)` or a loop first advances it.',
    },
    {
      id: 'python-first-match',
      topic: 'Functions & iteration',
      code: 'values = [3, 8, 10]\nfirst_even = next((x for x in values if x % 2 == 0), None)\nfirst_negative = next((x for x in values if x < 0), None)',
      question: 'What values are assigned to `first_even` and `first_negative`?',
      answer: '`8` / `None`',
      acceptedAnswers: ['8 and none', '8, none', 'first even is 8, first negative is none'],
      explanation: 'The first search stops at `8`, the first even value. The second finds no negative value, so `next` returns its explicit `None` default.',
    },
    {
      id: 'python-keyword-only-hyperparameters',
      topic: 'Functions & iteration',
      code: 'def train(model: Model, *, epochs: int, lr: float) -> None:\n    ...\n\ntrain(model, epochs=10, lr=1e-3)',
      question: 'How must callers pass `epochs` and `lr`?',
      answer: 'By keyword: `epochs=...` and `lr=...`',
      acceptedAnswers: ['keyword-only arguments', 'keyword only', 'keywords', 'must name them', 'by keyword'],
      explanation: 'The bare `*` is a separator: parameters after it cannot be positional. Unlike `**kwargs`, it does not collect extra arguments; `train(model, 10, 1e-3)` raises `TypeError`.',
    },
    {
      id: 'python-closure-late-binding',
      topic: 'Functions & iteration',
      code: 'functions_a = [lambda: i for i in range(3)]\nfunctions_b = [lambda i=i: i for i in range(3)]\n\nresult_a = [function() for function in functions_a]\nresult_b = [function() for function in functions_b]',
      question: 'What values do `result_a` and `result_b` contain?',
      answer: '`[2, 2, 2]` / `[0, 1, 2]`',
      acceptedAnswers: ['[2,2,2] and [0,1,2]', '[2, 2, 2], [0, 1, 2]'],
      explanation: 'Every lambda in `functions_a` reads the same `i` after the loop ends at `2`. In `functions_b`, each default argument is evaluated during its loop iteration, storing `0`, `1`, or `2` separately.',
    },
    {
      id: 'python-partial-callable',
      topic: 'Functions & iteration',
      code: 'from functools import partial\n\ndef scale(value: int, factor: int) -> int:\n    return value * factor\n\ndouble = partial(scale, factor=2)\nresult = double(5)',
      question: 'What value does `result` contain, and which argument did `partial` store?',
      answer: '`10` / `factor=2`',
      acceptedAnswers: ['10 and factor 2', '10, factor=2', 'result is 10, factor is 2'],
      explanation: '`partial` stores `scale` together with `factor=2` and returns a new callable named `double`. Calling `double(5)` then invokes `scale(value=5, factor=2)`.',
    },
    {
      id: 'python-wraps-decorator',
      topic: 'Functions & iteration',
      code: 'def trace(function):\n    def wrapper(*args, **kwargs):\n        return function(*args, **kwargs)\n    return wrapper\n\n@trace\ndef add(a, b):\n    return a + b',
      question: 'What is `add.__name__` after decoration, and what should decorate `wrapper` to preserve the original name?',
      answer: '`wrapper` / `@wraps(function)`',
      acceptedAnswers: ['wrapper and wraps', 'wrapper, @wraps(function)', 'wrapper / functools.wraps'],
      explanation: '`trace` replaces the name `add` with its inner `wrapper`, so the visible name becomes `wrapper`. Applying `@functools.wraps(function)` to that inner function copies metadata from the original `add`.',
    },
    {
      id: 'python-lru-cache-contract',
      topic: 'Functions & iteration',
      code: '@lru_cache(maxsize=128)\ndef load_schema(path: Path) -> Schema:\n    ...',
      question: 'Why can this return a stale `Schema` even though `path` is hashable?',
      answer: 'The file can change while the cached `path` key stays the same',
      acceptedAnswers: ['file contents can change', 'same path, changed file', 'path does not include file contents', 'cache is stale'],
      explanation: '`lru_cache` keys this call by the `Path` value. If the file changes at that path, the next call finds the same key and returns the old `Schema` without reading the file again.',
    },

    {
      id: 'python-instance-shadows-class',
      topic: 'Classes & interfaces',
      code: 'class C:\n    timeout = 30\n\na = C()\nb = C()\na.timeout = 10',
      question: 'What are `a.timeout`, `b.timeout`, and `C.timeout` after the assignment?',
      answer: '`10` / `30` / `30`',
      acceptedAnswers: ['10, 30, 30', 'a is 10, b is 30, c is 30'],
      explanation: '`a.timeout = 10` writes `{"timeout": 10}` into `a.__dict__`; it does not change `C.timeout`. Because `b.__dict__` has no `timeout`, `b.timeout` falls back to the class value `30`.',
    },
    {
      id: 'python-mutable-class-attribute',
      topic: 'Classes & interfaces',
      code: 'class Registry:\n    names: list[str] = []\n\na = Registry()\nb = Registry()\na.names.append("x")',
      question: 'What are `a.names`, `b.names`, and `Registry.names` after the append?',
      answer: '`["x"]` / `["x"]` / `["x"]`',
      acceptedAnswers: ['[x], [x], [x]', '["x"], ["x"], ["x"]', 'all contain x'],
      explanation: '`a.names.append("x")` performs no attribute assignment, so `a.__dict__` and `b.__dict__` stay empty. Both instances find the same list at `Registry.names`, and the append mutates that shared object.',
    },
    {
      id: 'python-bound-method-self',
      topic: 'Classes & interfaces',
      code: 'class Counter:\n    def __init__(self, value: int) -> None:\n        self.value = value\n\n    def add(self, amount: int) -> int:\n        return self.value + amount\n\ncounter = Counter(10)\nbound_add = counter.add\nresult = bound_add(5)',
      question: 'When `bound_add(5)` calls `Counter.add`, what values arrive as `self` and `amount`?',
      answer: '`self=counter` / `amount=5`',
      acceptedAnswers: ['counter and 5', 'self is counter, amount is 5', 'counter / 5'],
      explanation: 'Reading `counter.add` binds the instance `counter` to the method. The later call supplies only `5`, so Python invokes the underlying function like `Counter.add(counter, 5)`.',
    },
    {
      id: 'python-classmethod-constructor',
      topic: 'Classes & interfaces',
      code: 'class Job:\n    @classmethod\n    def from_dict(cls, data: dict[str, str]) -> Self:\n        return cls(**data)\n\nclass BatchJob(Job):\n    pass\n\njob = BatchJob.from_dict({"name": "train"})',
      question: 'What class is `job`, and why does the inherited method create that class?',
      answer: '`BatchJob`; `cls` is the class used for the call',
      acceptedAnswers: ['BatchJob', 'BatchJob because cls is BatchJob', 'cls is BatchJob'],
      explanation: '`BatchJob.from_dict(...)` passes `BatchJob` as `cls`, even though the method is defined on `Job`. Therefore `cls(**data)` creates a `BatchJob`; hard-coding `Job(**data)` would create a `Job` instead.',
    },
    {
      id: 'python-staticmethod-helper',
      topic: 'Classes & interfaces',
      code: 'class User:\n    @staticmethod\n    def validate_name(name: str) -> bool:\n        return bool(name.strip()) and len(name) <= 50',
      question: 'Why does `validate_name` need neither `self` nor `cls`?',
      answer: 'It uses only the supplied `name`',
      acceptedAnswers: ['it does not use instance or class state', 'no instance or class state', 'only uses name'],
      explanation: 'The result depends only on the `name` argument. The method does not read a particular `User` instance or any state stored on the `User` class, so `staticmethod` is appropriate.',
    },
    {
      id: 'python-property-boundary',
      topic: 'Classes & interfaces',
      code: 'class Dataset:\n    @property\n    def num_samples(self) -> int:\n        return len(self.samples)\n\ncount = dataset.num_samples',
      question: 'Why is attribute access appropriate for `num_samples`?',
      answer: 'It is fast, local, and has no side effects',
      acceptedAnswers: ['it only reads the in-memory list', 'cheap side-effect-free calculation', 'fast derived value'],
      explanation: '`len(self.samples)` computes an immediate value from data already in memory and changes nothing. If reading the value required disk access, a network request, or other expensive work, an explicit method such as `fetch_num_samples()` would make that cost visible.',
    },
    {
      id: 'python-callable-transform',
      topic: 'Classes & interfaces',
      code: 'class Center:\n    def __init__(self, offset: float) -> None:\n        self.offset = offset\n\n    def __call__(self, value: float) -> float:\n        return value - self.offset\n\ncenter = Center(offset=10.0)\nresult = center(13.0)',
      question: 'Which method runs for `center(13.0)`, and what is `result`?',
      answer: '`__call__`; `3.0`',
      acceptedAnswers: ['__call__, 3.0', '__call__ and 3', 'Center.__call__; 3.0'],
      explanation: '`center` is an object, but `center(13.0)` invokes `Center.__call__(center, 13.0)`. That method can use the `offset` stored earlier by `__init__`, so it returns `13.0 - 10.0 = 3.0`.',
    },
    {
      id: 'python-composition-pipeline',
      topic: 'Classes & interfaces',
      code: 'class Pipeline:\n    def __init__(self, steps: list[Callable]) -> None:\n        self.steps = steps\n\n    def __call__(self, value):\n        for step in self.steps:\n            value = step(value)\n        return value\n\npipeline = Pipeline([Decode(), Resize(224), Normalize()])',
      question: 'How does `Pipeline` reuse the three transforms without inheriting from them?',
      answer: 'It stores and calls them as component objects',
      acceptedAnswers: ['composition', 'object composition', 'stores the transforms and calls them in sequence'],
      explanation: '`Pipeline` contains `Decode`, `Resize`, and `Normalize` objects, then calls each object in sequence. This is composition: behavior is assembled from contained objects rather than inherited from parent classes.',
    },
    {
      id: 'python-protocol-interface',
      topic: 'Classes & interfaces',
      code: 'class Transform(Protocol):\n    def __call__(self, sample: Sample) -> Sample:\n        ...\n\nclass Normalize:\n    def __call__(self, sample: Sample) -> Sample:\n        return normalize(sample)\n\ndef apply(transform: Transform, sample: Sample) -> Sample:\n    return transform(sample)\n\nresult = apply(Normalize(), sample)',
      question: 'Why does a type checker accept `Normalize()` as a `Transform` without inheritance?',
      answer: 'Its `__call__` method matches the protocol',
      acceptedAnswers: ['structural typing', 'Normalize has the required __call__ signature', 'it matches the Transform protocol'],
      explanation: '`Transform` requires a callable with the shown input and output types. `Normalize` provides that method, so it satisfies the protocol by structure; it does not need to inherit from `Transform` or register with it.',
    },
    {
      id: 'python-super-mro',
      topic: 'Classes & interfaces',
      code: 'class Stage:\n    def run(self) -> list[str]:\n        return ["stage"]\n\nclass TimedStage(Stage):\n    def run(self) -> list[str]:\n        return ["timed", *super().run()]\n\nclass LoggedStage(Stage):\n    def run(self) -> list[str]:\n        return ["logged", *super().run()]\n\nclass Pipeline(TimedStage, LoggedStage):\n    pass\n\nresult = Pipeline().run()',
      question: 'Which `run` does `super()` call inside `TimedStage.run`, and what is `result`?',
      answer: '`LoggedStage.run`; `["timed", "logged", "stage"]`',
      acceptedAnswers: ['LoggedStage.run and [timed, logged, stage]', 'LoggedStage, then Stage', '["timed", "logged", "stage"]'],
      explanation: '`Pipeline` has the MRO `Pipeline → TimedStage → LoggedStage → Stage → object`. Therefore `super()` inside `TimedStage` continues to `LoggedStage`, not directly to the `Stage` named in `class TimedStage(Stage)`.',
    },

    {
      id: 'python-annotations-runtime',
      topic: 'Typing',
      code: 'def double(value: int) -> int:\n    return value * 2\n\nresult = double("10")',
      question: 'What is `result` in ordinary Python, and does the annotation convert or reject `"10"`?',
      answer: '`"1010"`; it does neither',
      acceptedAnswers: ['1010; no conversion or rejection', '"1010" because annotations are not enforced', 'string 1010'],
      explanation: 'Python passes the string into the function unchanged. String multiplication repeats it, so `"10" * 2` produces `"1010"`; the `int` annotations are available to type checkers but do not validate or convert values by themselves.',
    },
    {
      id: 'python-any-vs-object',
      topic: 'Typing',
      code: 'def shout_unchecked(value: Any) -> str:\n    return value.upper()\n\ndef shout_unknown(value: object) -> str:\n    return value.upper()',
      question: 'Which `.upper()` call does a type checker reject, and why?',
      answer: 'The `object` one; `object` does not guarantee `.upper()`',
      acceptedAnswers: ['shout_unknown because object must be narrowed', 'the second call; Any disables checking', 'object has no guaranteed upper method'],
      explanation: '`Any` tells the checker to allow operations without proving they exist. `object` can hold a value of any type, but the only safe operations are those available on every object. Narrow `value` with `isinstance(value, str)` before calling `.upper()`.',
    },
    {
      id: 'python-nullable-not-optional',
      topic: 'Typing',
      code: 'def load(cache_dir: Path | None) -> Dataset:\n    ...\n\na = load(None)\nb = load()',
      question: 'Which call is valid: `load(None)` or `load()`?',
      answer: '`load(None)` only',
      acceptedAnswers: ['load(None)', 'load None; load() is missing an argument', 'the first call'],
      explanation: '`Path | None` allows `None` as the argument value, so `load(None)` is valid. The parameter has no default, so `load()` omits a required argument and raises `TypeError`. Use `cache_dir: Path | None = None` to permit omission.',
    },
    {
      id: 'python-sequence-parameter',
      topic: 'Typing',
      code: 'def inspect_batch(samples) -> tuple[int, Sample]:\n    size = len(samples)\n    first = samples[0]\n    return size, first',
      question: 'Which annotation for `samples` supports these operations and accepts both lists and tuples?',
      answer: '`Sequence[Sample]`',
      acceptedAnswers: ['Sequence', 'collections.abc.Sequence[Sample]'],
      explanation: '`Sequence[Sample]` guarantees `len(samples)` and indexed reads such as `samples[0]`. `Iterable[Sample]` is too weak because it guarantees neither operation, while `list[Sample]` unnecessarily rejects tuples and other sequences.',
    },
    {
      id: 'python-iterable-vs-iterator-type',
      topic: 'Typing',
      code: 'source: Iterable[int] = [10, 20, 30]\ncursor: Iterator[int] = iter(source)\n\nfirst = next(cursor)\nremaining = list(cursor)\nfrom_start = list(source)',
      question: 'What are `first`, `remaining`, and `from_start`?',
      answer: '`10`, `[20, 30]`, and `[10, 20, 30]`',
      acceptedAnswers: ['10; [20, 30]; [10, 20, 30]', '10, 20 30, 10 20 30'],
      explanation: '`cursor` remembers that `10` was consumed, so only `[20, 30]` remain in that iterator. The actual `source` is a list, and iterating the list creates another iterator starting at the beginning. An arbitrary `Iterable` is not necessarily replayable; this example restarts because the iterable is a list.',
    },
    {
      id: 'python-mapping-parameter',
      topic: 'Typing',
      code: 'def optimizer_name(config) -> str:\n    return str(config["optimizer"])',
      question: 'Which annotation accepts a `dict` or another mapping while exposing only key reads?',
      answer: '`Mapping[str, object]`',
      acceptedAnswers: ['Mapping', 'collections.abc.Mapping[str, object]'],
      explanation: '`Mapping[str, object]` supports reads such as `config["optimizer"]` without including item assignment in the static interface. It does not freeze a mutable `dict` at runtime; it tells the type checker that this function should not rely on mutation. Use `MutableMapping` when writes are required.',
    },
    {
      id: 'python-callable-signature',
      topic: 'Typing',
      code: 'def resize(sample: Sample) -> Sample:\n    return sample\n\ndef score(sample: Sample) -> float:\n    return 0.95\n\ntransform: Callable[[Sample], Sample]\ntransform = resize\ntransform = score',
      question: 'Which assignment does a type checker accept for `transform`?',
      answer: '`transform = resize` only',
      acceptedAnswers: ['resize', 'the resize assignment', 'resize because it returns Sample'],
      explanation: 'In `Callable[[Sample], Sample]`, the inner list describes the argument types and the final type describes the return value. Both functions accept one `Sample`, but only `resize` returns a `Sample`; `score` returns `float`.',
    },
    {
      id: 'python-typeddict-runtime',
      topic: 'Typing',
      code: 'class TrainConfig(TypedDict):\n    epochs: int\n    lr: float\n\nraw = json.loads("{\\"epochs\\": \\"ten\\", \\"lr\\": 0.001}")\nconfig: TrainConfig = raw',
      question: 'Does assigning `raw` to `config` reject the string `"ten"` at runtime?',
      answer: 'No; `config` is still an ordinary `dict`',
      acceptedAnswers: ['no', 'no runtime validation', 'no; TypedDict is only for static checking'],
      explanation: '`TrainConfig` tells a type checker that code expects `epochs` to be an `int` and `lr` to be a `float`. It does not inspect data returned by `json.loads`, so the invalid string remains in the ordinary dictionary. External data needs explicit runtime validation before it is trusted.',
    },
    {
      id: 'python-literal-optimizer',
      topic: 'Typing',
      code: 'def train(optimizer) -> None:\n    ...\n\ntrain("adam")\ntrain("sgd")\ntrain("rmsprop")',
      question: 'Which annotation for `optimizer` makes a type checker accept the first two calls and reject the third?',
      answer: '`Literal["adam", "sgd"]`',
      acceptedAnswers: ['Literal', 'typing.Literal'],
      explanation: '`Literal["adam", "sgd"]` means the argument must be one of those two exact string values, not merely any `str`. A type checker therefore flags `"rmsprop"`. Like other annotations, `Literal` does not perform runtime validation by itself.',
    },
    {
      id: 'python-annotated-field',
      topic: 'Typing',
      code: 'class TrainConfig(BaseModel):\n    batch_size: Annotated[int, Field(gt=0)]\n\na = TrainConfig(batch_size=32)\nb = TrainConfig(batch_size=0)',
      question: 'Which construction passes Pydantic validation, and what does `Field(gt=0)` require?',
      answer: '`a` only; `batch_size` must be greater than `0`',
      acceptedAnswers: ['a; greater than zero', 'batch_size 32 passes and 0 fails', 'only the first construction'],
      explanation: '`int` is the field’s base type. `Annotated` attaches `Field(gt=0)` as metadata, and Pydantic interprets that metadata as a runtime constraint. `32` passes; `0` fails because it is not greater than zero. `Annotated` alone performs no validation.',
    },
    {
      id: 'python-typevar-relationship',
      topic: 'Typing',
      code: 'T = TypeVar("T")\n\ndef first(xs: Sequence[T]) -> T:\n    return xs[0]\n\nname = first(["Ada", "Lin"])\nscore = first([0.9, 0.8])',
      question: 'What static types does a type checker infer for `name` and `score`?',
      answer: '`str` for `name`; `float` for `score`',
      acceptedAnswers: ['name is str and score is float', 'str, float'],
      explanation: 'For each call, the type checker replaces `T` with the sequence’s element type. The string list makes `T = str`, so `name` is `str`; the float list makes `T = float`, so `score` is `float`. `TypeVar` links the input element type to the return type.',
    },

    {
      id: 'python-dataclass-generated-methods',
      topic: 'Dataclasses',
      code: '@dataclass\nclass RunConfig:\n    epochs: int\n    lr: float\n\na = RunConfig(epochs=10, lr=0.01)\nb = RunConfig(epochs=10, lr=0.01)\n\nshown = repr(a)\nsame = a == b',
      question: 'What are `shown` and `same`, even though `RunConfig` defines no methods?',
      answer: '`RunConfig(epochs=10, lr=0.01)` and `True`',
      acceptedAnswers: ['RunConfig(epochs=10, lr=0.01); True', 'the field repr and true'],
      explanation: '`@dataclass` generated the constructor used to create `a` and `b`, a field-based `__repr__`, and field-based `__eq__`. It saves boilerplate; it does not validate that runtime values match the annotations.',
    },
    {
      id: 'python-dataclass-mutable-default',
      topic: 'Dataclasses',
      code: '@dataclass\nclass Sample:\n    tags: list[str] = ???\n\na = Sample()\nb = Sample()\na.tags.append("train")',
      question: 'What should replace `???` so `a.tags` is `["train"]` while `b.tags` remains `[]`?',
      answer: '`field(default_factory=list)`',
      acceptedAnswers: ['default_factory=list', 'default factory'],
      explanation: '`field(default_factory=list)` stores the `list` function as a factory. The generated initializer calls it separately for each `Sample()`, so `a.tags` and `b.tags` refer to different lists. A shared list default would let one instance’s mutation appear in another.',
    },
    {
      id: 'python-dataclass-post-init',
      topic: 'Dataclasses',
      code: '@dataclass\nclass Schedule:\n    total_steps: int\n    warmup_steps: int\n\n    def __post_init__(self) -> None:\n        if self.warmup_steps >= self.total_steps:\n            raise ValueError("warmup must end before training")\n\nvalid = Schedule(total_steps=100, warmup_steps=10)\ninvalid = Schedule(total_steps=100, warmup_steps=100)',
      question: 'Which construction raises `ValueError`, and when does this check run?',
      answer: '`invalid`; after the generated `__init__` assigns both fields',
      acceptedAnswers: ['invalid; after init', 'the second construction in post init', 'warmup 100 raises after initialization'],
      explanation: 'The generated `__init__` first assigns `total_steps` and `warmup_steps`, then automatically calls `__post_init__`. That timing lets the method compare both fields. `10 < 100` passes, while `100 >= 100` raises `ValueError` before the invalid object is returned.',
    },
    {
      id: 'python-dataclass-classvar',
      topic: 'Dataclasses',
      code: '@dataclass\nclass RunConfig:\n    name: str\n    VERSION: ClassVar[str] = "v2"\n\nconfig = RunConfig(name="train")\nshown = repr(config)\nversion = config.VERSION',
      question: 'What are `shown` and `version`, and why is `VERSION` absent from `shown`?',
      answer: '`RunConfig(name=\'train\')` and `"v2"`; `VERSION` is not a dataclass field',
      acceptedAnswers: ['RunConfig(name=train), v2; ClassVar', 'repr omits VERSION and version is v2', 'VERSION is a class variable'],
      explanation: '`ClassVar` tells dataclasses that `VERSION` belongs to the class rather than each instance’s field data. It remains accessible as `config.VERSION`, but dataclasses exclude it from the generated constructor, representation, comparison, and field list.',
    },
    {
      id: 'python-dataclass-frozen-shallow',
      topic: 'Dataclasses',
      code: '@dataclass(frozen=True)\nclass Config:\n    tags: list[str]\n\nconfig = Config(tags=["train"])\nconfig.tags.append("eval")\nconfig.tags = ["test"]',
      question: 'Which operation succeeds: appending to `tags` or assigning a new list?',
      answer: 'Appending succeeds; assignment raises `FrozenInstanceError`',
      acceptedAnswers: ['append succeeds and assignment fails', 'the append only', 'list mutation works but field rebinding fails'],
      explanation: '`frozen=True` blocks rebinding `config.tags`, so assigning a different list raises `FrozenInstanceError`. It does not freeze the list object already stored there, so `append` succeeds and leaves `config.tags == ["train", "eval"]`.',
    },
    {
      id: 'python-dataclass-kw-only',
      topic: 'Dataclasses',
      code: '@dataclass(kw_only=True)\nclass RunConfig:\n    epochs: int\n    lr: float\n\na = RunConfig(10, 0.001)\nb = RunConfig(epochs=10, lr=0.001)',
      question: 'Which construction succeeds: `a` or `b`?',
      answer: '`b`',
      acceptedAnswers: ['b', 'the named-argument call', 'RunConfig(epochs=10, lr=0.001)'],
      explanation: '`kw_only=True` makes the generated initializer parameters keyword-only. Call `b` names both arguments, while call `a` passes them by position and raises `TypeError`. This is not `**kwargs`: only the declared names, `epochs` and `lr`, are accepted.',
    },
    {
      id: 'python-dataclass-slots',
      topic: 'Dataclasses',
      code: '@dataclass(slots=True)\nclass Point:\n    x: float\n    y: float\n\npoint = Point(1.0, 2.0)\npoint.xx = 3.0  # meant point.x',
      question: 'What happens when the misspelled assignment runs?',
      answer: '`AttributeError`',
      acceptedAnswers: ['AttributeError', 'it raises AttributeError', 'the assignment is rejected'],
      explanation: '`slots=True` gives `Point` a fixed set of instance attributes, so there is no place to store `xx` and Python raises `AttributeError`. Without slots, an ordinary dataclass would usually create a new `xx` attribute silently while leaving `x` unchanged. The fixed layout can also reduce memory when many instances are created.',
    },
    {
      id: 'python-dataclass-replace',
      topic: 'Dataclasses',
      code: '@dataclass(frozen=True)\nclass RunConfig:\n    lr: float\n\noriginal = RunConfig(lr=1e-3)\nupdated = replace(original, lr=1e-4)',
      question: 'What are `original.lr` and `updated.lr`?',
      answer: '`1e-3` and `1e-4`',
      acceptedAnswers: ['0.001 and 0.0001', 'original is 1e-3, updated is 1e-4'],
      explanation: '`dataclasses.replace` creates a new instance with selected fields changed; it does not mutate the original. It calls the generated initializer, so `__post_init__` runs for the new object too.',
    },
    {
      id: 'python-dataclass-asdict',
      topic: 'Dataclasses',
      code: '@dataclass\nclass TrainingState:\n    weights: Tensor\n\nweights = torch.zeros(10_000_000)\npayload = asdict(TrainingState(weights=weights))',
      question: 'Does `payload["weights"]` reuse the original tensor object?',
      answer: 'No; `asdict` deep-copies it',
      acceptedAnswers: ['no', 'no, it is deep copied', 'deep copy'],
      explanation: '`dataclasses.asdict` recursively converts nested dataclasses, lists, tuples, and dictionaries, then uses `deepcopy` for other values. That can duplicate a large tensor—or fail for a runtime object that cannot be deep-copied—so serialization code should often select only the metadata it needs.',
    },

    {
      id: 'python-pydantic-boundary-choice',
      topic: 'Pydantic v2',
      code: 'internal = SchedulerState(step=10)\nexternal = json.loads(request_body)',
      question: 'Which value needs runtime validation before the training code trusts its fields?',
      answer: '`external`',
      acceptedAnswers: ['external', 'the JSON payload', 'request_body'],
      explanation: '`internal` was created by trusted program code, so a plain dataclass can be enough. `external` crossed a JSON boundary and may contain missing, extra, or wrongly typed values; a Pydantic `BaseModel` can parse and validate it before use.',
    },
    {
      id: 'python-pydantic-dataclass',
      topic: 'Pydantic v2',
      code: '@pydantic.dataclasses.dataclass\nclass RunConfig:\n    epochs: int\n\nconfig = RunConfig(epochs="ten")',
      question: 'Does construction return a config object?',
      answer: 'No; it raises `ValidationError`',
      acceptedAnswers: ['no', 'ValidationError', 'it raises a validation error'],
      explanation: 'A Pydantic dataclass keeps normal dataclass features but validates constructor input at runtime. The string `"ten"` cannot be parsed as an integer, so construction raises `ValidationError` instead of storing the bad value.',
    },
    {
      id: 'python-pydantic-default-coercion',
      topic: 'Pydantic v2',
      code: 'config = RunConfig(epochs="10")\nresult = config.epochs',
      question: 'What value and runtime type does `result` have under default settings?',
      answer: '`10` as an `int`',
      acceptedAnswers: ['10', 'integer 10', 'int 10'],
      explanation: 'Pydantic uses coercive validation by default and converts compatible strings to integers.',
    },
    {
      id: 'python-pydantic-strict-mode',
      topic: 'Pydantic v2',
      code: 'class RunConfig(BaseModel):\n    model_config = ConfigDict(strict=True)\n    epochs: int\n\nconfig = RunConfig(epochs="10")',
      question: 'What happens at construction?',
      answer: '`ValidationError`',
      acceptedAnswers: ['ValidationError', 'it raises a validation error', 'the string is rejected'],
      explanation: 'Strict mode requires the input to already have the declared runtime type. It rejects `"10"` instead of coercing that string to the integer `10`.',
    },
    {
      id: 'python-pydantic-extra-forbid',
      topic: 'Pydantic v2',
      code: 'class RunConfig(BaseModel):\n    model_config = ConfigDict(extra="forbid")\n    batch_size: int = 32\n\nconfig = RunConfig(batch_szie=64)',
      question: 'Does the misspelled input silently fall back to `batch_size=32`?',
      answer: 'No; it raises `ValidationError`',
      acceptedAnswers: ['no', 'ValidationError', 'the extra key is rejected'],
      explanation: '`extra="forbid"` rejects input keys that are not declared model fields. It catches `batch_szie` as an error instead of ignoring the typo and quietly using the default batch size.',
    },
    {
      id: 'python-pydantic-positive-field',
      topic: 'Pydantic v2',
      code: 'class RunConfig(BaseModel):\n    batch_size: int = Field(gt=0)\n\nconfig = RunConfig(batch_size=0)',
      question: 'Does the model accept `batch_size=0`?',
      answer: 'No; it raises `ValidationError`',
      acceptedAnswers: ['no', 'ValidationError', 'zero is rejected'],
      explanation: '`Field(gt=0)` attaches a greater-than-zero constraint to `batch_size`. Pydantic checks the constraint during validation and reports the error at that field.',
    },
    {
      id: 'python-pydantic-default-factory',
      topic: 'Pydantic v2',
      code: 'class Sample(BaseModel):\n    tags: list[str] = Field(default_factory=list)\n\na = Sample()\nb = Sample()\na.tags.append("train")',
      question: 'What value does `b.tags` contain?',
      answer: '`[]`',
      acceptedAnswers: ['[]', 'an empty list'],
      explanation: '`default_factory=list` calls `list()` for each new model, so `a` and `b` receive different list objects. Mutating `a.tags` therefore cannot change `b.tags`.',
    },
    {
      id: 'python-pydantic-field-validator',
      topic: 'Pydantic v2',
      code: '@field_validator("model_name")\n@classmethod\ndef normalize_name(cls, value: str) -> str:\n    return value.strip().lower()\n\nconfig = RunConfig(model_name="  ResNet50  ")',
      question: 'What value is stored in `config.model_name`?',
      answer: '`"resnet50"`',
      acceptedAnswers: ['resnet50', '"resnet50"'],
      explanation: 'A field validator checks or transforms one named field during model validation. Here it strips surrounding whitespace and lowercases the value before Pydantic stores it.',
    },
    {
      id: 'python-pydantic-model-validator',
      topic: 'Pydantic v2',
      code: '@model_validator(mode="after")\ndef validate_schedule(self) -> Self:\n    if self.warmup_steps >= self.total_steps:\n        raise ValueError("invalid schedule")\n    return self\n\nschedule = Schedule(warmup_steps=100, total_steps=100)',
      question: 'Does construction return a `Schedule`?',
      answer: 'No; it raises `ValidationError`',
      acceptedAnswers: ['no', 'ValidationError', 'the schedule is rejected'],
      explanation: 'A model validator can inspect several parsed fields together. This after-validator rejects the object because warmup does not end before the final training step; Pydantic reports the raised `ValueError` as a `ValidationError`.',
    },
    {
      id: 'python-pydantic-assignment-validation',
      topic: 'Pydantic v2',
      code: 'class RunConfig(BaseModel):\n    model_config = ConfigDict(validate_assignment=True)\n    batch_size: int\n\nconfig = RunConfig(batch_size=32)\nconfig.batch_size = "bad"',
      question: 'What happens on the final line?',
      answer: '`ValidationError`; `batch_size` remains `32`',
      acceptedAnswers: ['ValidationError', 'the assignment is rejected', 'it raises and stays 32'],
      explanation: '`validate_assignment=True` runs field validation again whenever an attribute is changed. Because `"bad"` cannot become an integer, the assignment raises `ValidationError` and leaves the previous value intact.',
    },
    {
      id: 'python-pydantic-io-api',
      topic: 'Pydantic v2',
      code: 'payload = {"epochs": "10"}\nconfig = RunConfig.model_validate(payload)\nnormalized = config.model_dump()',
      question: 'What Python value does `normalized["epochs"]` contain?',
      answer: '`10` as an `int`',
      acceptedAnswers: ['10', 'integer 10', 'int 10'],
      explanation: '`model_validate` parses a Python object into a validated model; `model_dump` converts that model back to Python containers and scalar values. Use the corresponding `_json` methods when the boundary itself is JSON text or bytes.',
    },
    {
      id: 'python-pydantic-type-adapter',
      topic: 'Pydantic v2',
      code: 'adapter = TypeAdapter(list[int])\nvalues = adapter.validate_python(["1", "2"])',
      question: 'What value does `values` contain under default coercion?',
      answer: '`[1, 2]`',
      acceptedAnswers: ['[1, 2]', '[1,2]'],
      explanation: '`TypeAdapter` applies Pydantic validation to an annotation without requiring a wrapper `BaseModel`. Here it validates the list shape and converts each compatible string to an integer.',
    },
    {
      id: 'python-pydantic-private-attr',
      topic: 'Pydantic v2',
      code: 'class Predictor(BaseModel):\n    name: str\n    _cache: dict[str, Tensor] = PrivateAttr(default_factory=dict)\n\npredictor = Predictor(name="resnet")\npayload = predictor.model_dump()',
      question: 'Does `payload` contain a `_cache` key?',
      answer: 'No',
      acceptedAnswers: ['no', 'no, private attributes are excluded'],
      explanation: '`PrivateAttr` stores runtime-only state on the model without making it a validated field. Private attributes are omitted from generated schemas and `model_dump()`, so a cache or client is not accidentally serialized.',
    },
    {
      id: 'python-pydantic-arbitrary-tensor',
      topic: 'Pydantic v2',
      code: 'class Batch(BaseModel):\n    model_config = ConfigDict(arbitrary_types_allowed=True)\n    features: torch.Tensor\n\nbatch = Batch(features=torch.zeros(3))  # expected shape: [32, 128]',
      question: 'Does Pydantic reject the tensor for having the wrong shape?',
      answer: 'No',
      acceptedAnswers: ['no', 'only the tensor class is checked'],
      explanation: '`arbitrary_types_allowed=True` accepts a field when its value is an instance of the annotated arbitrary class. It checks the tensor class, not tensor shape, dtype, values, layout, or device; those invariants need explicit validators.',
    },
    {
      id: 'python-pydantic-model-construct',
      topic: 'Pydantic v2',
      code: 'payload = {"epochs": "ten"}\nconfig = RunConfig.model_construct(**payload)\nresult = config.epochs',
      question: 'What value and runtime type does `result` have?',
      answer: '`"ten"` as a `str`',
      acceptedAnswers: ['ten as a string', 'str ten', '"ten"'],
      explanation: '`model_construct()` creates a model without running validation or coercion. It therefore stores the invalid string unchanged; use this bypass only when another trusted layer has already established every model invariant.',
    },
    {
      id: 'python-pydantic-model-copy',
      topic: 'Pydantic v2',
      code: 'copied = config.model_copy()',
      question: 'Does `copied` contain deep copies of nested model state by default?',
      answer: 'No',
      explanation: '`model_copy()` is shallow by default; pass `deep=True` when nested objects must be copied.',
    },
    {
      id: 'python-pydantic-discriminated-union',
      topic: 'Pydantic v2',
      code: 'OptimizerConfig = Annotated[\n    AdamConfig | SGDConfig,\n    Field(discriminator="type"),\n]\n\npayload = {"type": "sgd", "momentum": 0.9}\noptimizer = TypeAdapter(OptimizerConfig).validate_python(payload)',
      question: 'Which model type does Pydantic construct?',
      answer: '`SGDConfig`',
      acceptedAnswers: ['SGDConfig', 'an SGDConfig'],
      explanation: 'A discriminated union is a set of model variants selected by a shared tag field. Pydantic reads `type="sgd"`, chooses `SGDConfig`, and validates only the fields required by that variant.',
    },

    {
      id: 'python-narrow-exception',
      topic: 'Reliability & I/O',
      code: 'try:\n    config = parse_config(path)\nexcept Exception:\n    raise ConfigError("invalid config")',
      question: 'What debugging problem does this broad handler create?',
      answer: 'It mislabels unrelated bugs as configuration errors',
      acceptedAnswers: ['it hides programming errors', 'it catches too broadly', 'masks unrelated exceptions'],
      explanation: '`except Exception` catches expected parse failures and unrelated defects such as `AttributeError` or `NameError`. Catch only errors this boundary can translate or recover from, so programming bugs keep their original type and traceback.',
    },
    {
      id: 'python-explicit-exception-cause',
      topic: 'Reliability & I/O',
      code: 'try:\n    payload = read_config(path)\nexcept OSError as exc:\n    raise ConfigError(path) from exc',
      question: 'Where can code inspect the original `OSError` after `ConfigError` is raised?',
      answer: '`ConfigError.__cause__`',
      acceptedAnswers: ['__cause__', 'the exception cause', 'ConfigError.__cause__'],
      explanation: '`raise ... from exc` creates explicit exception chaining: the new `ConfigError` explains the failed operation, while its `__cause__` retains the original `OSError` and traceback.',
    },
    {
      id: 'python-context-manager-cleanup',
      topic: 'Reliability & I/O',
      code: 'try:\n    with path.open("rb") as handle:\n        payload = handle.read()\n        decode(payload)  # raises\nexcept DecodeError:\n    pass',
      question: 'Is `handle` closed after `decode` raises?',
      answer: 'Yes',
      acceptedAnswers: ['yes', 'yes, the context manager closes it'],
      explanation: 'A context manager pairs resource acquisition with cleanup. Leaving the `with` block calls the file object\'s exit method on normal completion, an early return, or an exception, so the handle is closed here.',
    },
    {
      id: 'python-assert-input-validation',
      topic: 'Reliability & I/O',
      code: 'def load_config(batch_size: int) -> Config:\n    assert batch_size > 0, "invalid batch size"\n    ...',
      question: 'Will this check always run when Python starts with `-O`?',
      answer: 'No',
      acceptedAnswers: ['no', 'assertions may be removed'],
      explanation: 'Python optimization can remove `assert` statements entirely. Assertions are for internal conditions that should already hold; user or file input needs an explicit conditional that raises a stable exception.',
    },
    {
      id: 'python-str-vs-bytes',
      topic: 'Reliability & I/O',
      code: 'payload = b"caf\\xc3\\xa9"\ntext = payload.decode("utf-8")',
      question: 'What value and runtime type does `text` have?',
      answer: '`"café"` as a `str`',
      acceptedAnswers: ['café', 'café as str', 'string café'],
      explanation: '`bytes` stores raw byte values; `str` stores Unicode text. `decode("utf-8")` interprets the incoming bytes as UTF-8 text, while `text.encode("utf-8")` would perform the reverse conversion.',
    },
    {
      id: 'python-sorted-glob',
      topic: 'Reliability & I/O',
      code: 'paths = list(Path(root).glob("*.json"))\ntrain_paths = paths[:100]',
      question: 'Can this code guarantee the same training split across filesystems?',
      answer: 'No',
      acceptedAnswers: ['no', 'glob order is not guaranteed'],
      explanation: 'Filesystem enumeration does not promise a stable order. Sort the paths before slicing so directory order cannot silently change which files enter the training split.',
    },
    {
      id: 'python-untrusted-pickle',
      topic: 'Reliability & I/O',
      code: 'checkpoint_bytes = download(url)\ncheckpoint = pickle.loads(checkpoint_bytes)',
      question: 'Is this safe when the download source is untrusted?',
      answer: 'No',
      acceptedAnswers: ['no', 'pickle can execute code'],
      explanation: 'A pickle is an object-construction program, not inert data. Loading it can execute attacker-controlled code, so only unpickle authenticated trusted input or use a format that cannot encode executable behavior.',
    },
    {
      id: 'python-stable-experiment-id',
      topic: 'Reliability & I/O',
      code: 'experiment_id = hash(config_json)\nsave_run(experiment_id)',
      question: 'Can this ID be relied on across separate Python processes?',
      answer: 'No',
      acceptedAnswers: ['no', 'Python hash is process-local', 'hash is randomized'],
      explanation: 'Python intentionally randomizes many built-in hashes between processes. For a persistent ID, first serialize the configuration canonically, then compute a stable digest such as `hashlib.sha256(config_bytes).hexdigest()`.',
    },
    {
      id: 'python-multiprocessing-entrypoint',
      topic: 'Reliability & I/O',
      code: 'def worker(item: Item) -> Result:\n    ...\n\nif __name__ == "__main__":\n    run_pool(worker)',
      question: 'Why is `run_pool(worker)` placed inside the main guard?',
      answer: 'To stop spawned children from creating more pools',
      acceptedAnswers: ['prevent recursive process creation', 'stop child processes spawning pools', 'main guard'],
      explanation: 'The spawn start method launches a fresh interpreter and imports the main module. The guard prevents that import from running `run_pool` again, while the top-level `worker` gives pickle an importable function name.',
    },
    {
      id: 'python-concurrency-choice',
      topic: 'Reliability & I/O',
      question: 'Which defaults fit blocking downloads, CPU-heavy Python preprocessing, and cooperative network I/O?',
      answer: 'Threads / processes / `asyncio`',
      acceptedAnswers: ['threads, processes, asyncio', 'threads processes asyncio'],
      explanation: 'Threads overlap blocking I/O, processes bypass the traditional GIL for Python CPU work, and `asyncio` coordinates nonblocking I/O.',
    },
    ...expandedPythonTriviaCards,
  ],
} satisfies TriviaDeckData;

const missingDetailIds = practicalPythonTriviaSourceDeck.cards
  .filter((card) => !('detail' in card && card.detail) && !pythonTriviaDetails[card.id])
  .map((card) => card.id);

if (missingDetailIds.length > 0) {
  throw new Error(`Python trivia cards missing mental models: ${missingDetailIds.join(', ')}`);
}

export const practicalPythonTriviaDeck = {
  ...practicalPythonTriviaSourceDeck,
  cards: practicalPythonTriviaSourceDeck.cards.map((card) => ({
    ...card,
    detail: 'detail' in card && card.detail ? card.detail : pythonTriviaDetails[card.id],
  })),
} satisfies TriviaDeckData;
