/**
 * The second teaching layer for each Python trivia card.
 *
 * The card-local explanation states the immediate rule. These details name the
 * mental model, boundary, or failure mode that makes the rule reusable.
 */
export const pythonTriviaDetails: Record<string, string> = {
  // References and values
  'python-aliasing-append': 'Python names point to objects. Assignment changes which object a name points to; it does not duplicate that object. Copy only when the two names must be allowed to evolve independently.',
  'python-mutation-vs-rebinding': 'A function receives another reference to the caller’s object. Mutating that object crosses the call boundary, while rebinding the local parameter changes only the function’s local name.',
  'python-identity-vs-equality': '`is` asks whether two names point to the same object. `==` asks whether their values compare equal and may invoke custom equality logic. Identity is the reliable test for `None` and unique sentinels.',
  'python-missing-sentinel': 'A sentinel adds a third state: missing, explicit `None`, or a concrete value. Compare a private sentinel by identity so no user value can accidentally equal it.',
  'python-shared-mutable-default': 'A function definition is executable code, so its default expressions run once when Python executes the `def`. Treat defaults as long-lived objects; allocate per-call mutable state inside the function.',
  'python-repeated-inner-list': 'Sequence multiplication repeats element references, not the objects behind those references. Use a comprehension such as `[[] for _ in range(3)]` when each position needs independent mutable state.',
  'python-shallow-list-copy': 'A shallow copy breaks aliasing at one container boundary only. Draw the object graph: `a` and `b` are different lists, but both outgoing edges still reach the same dictionary.',
  'python-tuple-shallow-immutability': 'Tuple immutability protects the tuple’s slots from rebinding. It says nothing about the mutability of objects reached through those slots, so nested dictionaries and lists can still change.',
  'python-falsy-valid-value': 'Truth testing merges several distinct values—`0`, `0.0`, `False`, empty containers, and `None`—into one branch. Test the exact missing-state contract instead of using truthiness as a substitute.',
  'python-nan-equality': 'IEEE NaN represents an undefined or unrepresentable numeric result, and comparisons involving it are intentionally unordered. Equality therefore cannot serve as a missing-value test.',
  'python-float-comparison': 'A useful tolerance has two parts: relative tolerance scales with the magnitude, while absolute tolerance handles values near zero. Choose both from the error budget of the computation.',

  // Collections
  'python-list-vs-tuple': 'Choose a collection by contract, not syntax alone. A list advertises changeable sequence state; a tuple advertises a fixed grouping and is hashable only when every contained value is hashable.',
  'python-dict-key-contract': 'A dictionary first selects a hash bucket and then uses equality to find the key. If a key’s hash-relevant state changes while stored, future lookups may search the wrong bucket.',
  'python-set-deduplication': 'Sets use the same hash-and-equality machinery as dictionaries. They make membership and uniqueness cheap, but they do not promise a presentation order; sort at output boundaries that require determinism.',
  'python-split-leakage-intersection': 'A nonempty intersection is a concrete witness that the same identity appears in both splits. Check the intersection before training so evaluation cannot benefit from duplicated examples.',
  'python-dict-iteration-order': 'Insertion order is a history of writes, not an ordering relation on keys. Two dictionaries with the same pairs can iterate differently if they were constructed in different orders.',
  'python-sort-vs-sorted': 'The mutating method returns `None` so code does not confuse the operation with a new value. Use `sorted` when the input must survive unchanged or when the source is any iterable rather than a list.',
  'python-zip-strict': 'Ordinary `zip` treats early exhaustion as normal control flow. At paired-data boundaries, strict mode converts a silent truncation bug into an immediate structural error.',
  'python-counter-labels': 'A `Counter` is a frequency mapping specialized for repeated observations. It keeps counting logic declarative and exposes operations such as `most_common` without a manual update loop.',
  'python-defaultdict-grouping': 'The factory defines how missing keys become values. Remember that reading a missing key also inserts it, so use ordinary `dict.get` when observation must not mutate the mapping.',
  'python-bounded-loss-history': 'A bounded deque makes retention part of the data structure rather than cleanup logic. Appending a new item evicts the oldest automatically, keeping memory bounded over an unbounded run.',

  // Functions and iteration
  'python-iterable-vs-iterator': 'An iterable is a source that can produce traversal state. An iterator is that stateful traversal itself: `iter(iterator) is iterator`, and each `next` consumes one position.',
  'python-generator-exhaustion': 'A generator stores one suspended execution frame, not a replayable recipe. Recreate the generator for another pass or materialize its values when repeated traversal is required.',
  'python-eager-vs-lazy-comprehension': 'A list comprehension pays all compute and memory up front. A generator expression defers work and can stream, but errors also move to consumption time and the values remain one-shot.',
  'python-yield-generator-function': 'Calling a generator function creates a suspended frame without running its body. Each `next` resumes execution until the next `yield`, preserving local variables between resumptions.',
  'python-first-match': 'The generator expression and `next` form a short-circuit search: production stops as soon as one item satisfies the predicate. The explicit default defines the no-match branch without an exception.',
  'python-keyword-only-hyperparameters': 'A bare `*` creates a boundary in the signature but stores nothing. Parameters after it must be named at the call site; `**kwargs` is the separate syntax that collects additional keyword arguments.',
  'python-closure-late-binding': 'A closure captures a variable cell, not a frozen snapshot of its current value. A default argument works here because its expression is evaluated when each lambda is created.',
  'python-partial-callable': '`partial` packages a function with selected arguments but does not call the function yet. Calling the new object combines fresh arguments with the stored ones; any stored mutable object remains shared across calls.',
  'python-wraps-decorator': 'A decorator replaces one callable with another. `wraps` copies the public metadata and records `__wrapped__`, allowing introspection, documentation, and tools to recover the original function.',
  'python-lru-cache-contract': 'Hashable means an argument can serve as a cache key; it does not mean the key captures every dependency. A file-backed cache must include a content version or modification signal in the key, or clear the cache when the file changes.',

  // Classes and interfaces
  'python-instance-shadows-class': 'Reading `a.timeout` checks `a.__dict__` first and then `C`. The assignment adds only `a.__dict__["timeout"]`; `b.__dict__` remains empty, so `b.timeout` still resolves to `C.timeout`.',
  'python-mutable-class-attribute': 'Both reads fall through empty instance dictionaries to the same `Registry.names` list. `append` mutates that class-owned object without creating `a.names`; use `self.names = []` in `__init__` when each instance needs its own list.',
  'python-bound-method-self': '`Counter.add` is a function that expects both `self` and `amount`. Accessing it as `counter.add` creates a bound method that already carries `counter`, making `bound_add(5)` equivalent to `Counter.add(counter, 5)`.',
  'python-classmethod-constructor': 'A class method receives the class used for the call. Here, `BatchJob.from_dict(...)` binds `cls` to `BatchJob`, so `cls(**data)` preserves the subclass. Writing `Job(**data)` instead would always return a `Job`.',
  'python-staticmethod-helper': '`User.validate_name` is related to `User`, but its calculation needs only the supplied string. A static method keeps that helper under the `User` namespace without automatically passing an instance as `self` or the class as `cls`.',
  'python-property-boundary': '`dataset.num_samples` looks like an ordinary field read, so callers expect it to be quick and free of side effects. Computing `len(self.samples)` meets that expectation. Disk access, network calls, or expensive computation should use an explicitly named method so the work is visible at the call site.',
  'python-callable-transform': '`Center(offset=10.0)` creates an object and stores its configuration. Calling that object as `center(13.0)` dispatches to `Center.__call__(center, 13.0)`, which can use the stored offset. The crux is that `__call__` gives an instance function-call syntax without turning the instance into a function.',
  'python-composition-pipeline': '`Pipeline` does not become a kind of `Decode`, `Resize`, or `Normalize`. It owns instances of those transforms and forwards the value through them. That containment relationship is composition, and it lets a caller replace or reorder steps without creating another subclass.',
  'python-protocol-interface': 'The type checker compares `Normalize` with the members required by `Transform`. Because `Normalize.__call__` has the compatible signature, `Normalize()` can be passed to `apply` even though the class never mentions `Transform`. This member-based check is structural typing.',
  'python-super-mro': 'For a `Pipeline` instance, Python follows `Pipeline → TimedStage → LoggedStage → Stage → object`. The `super()` call inside `TimedStage.run` starts after `TimedStage` in that sequence, so it invokes `LoggedStage.run`. Each implementation then forwards to the next class, producing `timed`, `logged`, then `stage`.',

  // Typing
  'python-annotations-runtime': 'The call passes the actual string into `double`; Python does not turn it into an integer or stop the call. The body therefore evaluates `"10" * 2` using string behavior and returns `"1010"`, despite the annotated return type. A type checker can flag the call before execution, while runtime enforcement requires separate validation.',
  'python-any-vs-object': 'Both annotations let callers pass any Python value. Inside the function, however, `Any` disables checking for `value.upper()`, while `object` makes the checker reject that call because not every object has `upper`. An `isinstance(value, str)` check narrows `object` to `str` and makes the call safe.',
  'python-nullable-not-optional': '`load(None)` supplies an argument whose value is `None`; `load()` supplies no argument. The union annotation permits the first case, while only a default such as `cache_dir: Path | None = None` permits the second. Allowing `None` and allowing omission are separate choices.',
  'python-sequence-parameter': 'The body needs two capabilities: `len(samples)` and integer indexing. `Sequence[Sample]` guarantees both for lists, tuples, and other sequence types. `Iterable[Sample]` guarantees only iteration, while `list[Sample]` promises a specific container the function does not require.',
  'python-iterable-vs-iterator-type': '`cursor` is one traversal with a current position. Calling `next(cursor)` advances that position, so later reads continue from `20`. `source` only promises that `iter(source)` is available; because this source is a list, a new traversal starts from `10`. The `Iterable` type alone does not guarantee that every source can be replayed.',
  'python-mapping-parameter': 'The function only reads `config["optimizer"]`, so it needs mapping behavior rather than a concrete `dict`. `Mapping[str, object]` accepts dictionaries and other mapping implementations, while a type checker rejects item assignment through that parameter. The annotation expresses a read-only interface; it does not make the underlying object immutable at runtime.',
  'python-callable-signature': 'Read `Callable[[Sample], Sample]` as two parts: `[Sample]` means one argument of type `Sample`, and the last `Sample` is the return type. `resize` matches both parts. `score` matches the input but returns `float`, so it cannot be assigned to `transform`.',
  'python-typeddict-runtime': '`TrainConfig` is a dictionary shape for static analysis: it documents the required keys and their expected value types. The annotation `config: TrainConfig` does not construct a special object or inspect `raw`; at runtime, `config` is the same ordinary dictionary containing `"ten"`. Validate JSON with explicit checks or a runtime validation library before treating it as trusted configuration.',
  'python-literal-optimizer': '`str` would allow every string, including `"rmsprop"` and misspellings. `Literal["adam", "sgd"]` gives the type checker a closed list of permitted values, so only the first two calls type-check. The annotation still needs separate validation if untyped data reaches the function at runtime.',
  'python-annotated-field': 'A type checker treats `batch_size` as an `int`. `Annotated` also carries `Field(gt=0)` alongside that type, and Pydantic reads the metadata when it constructs `TrainConfig`. That is why `32` passes and `0` raises a validation error; plain Python would not enforce the metadata by itself.',
  'python-typevar-relationship': 'Think of `T` as a per-call type blank used in multiple places. For `first(["Ada", "Lin"])`, the checker fills the blank with `str` in both `Sequence[T]` and the return type. For the float list, it fills both with `float`. Reusing `T` preserves that relationship; returning `object` would lose the specific result type.',

  // Dataclasses
  'python-dataclass-generated-methods': 'The field declarations give `@dataclass` enough information to generate `__init__`, so keyword construction works; `__repr__`, so the fields appear in `shown`; and `__eq__`, so two instances with equal fields compare equal. These are convenience methods on a normal class, not runtime type validation.',
  'python-dataclass-mutable-default': 'The important word is factory: dataclasses save the callable `list`, not one list object. Creating `a` calls `list()` once, and creating `b` calls it again. The two fields therefore hold separate mutable objects, so appending to `a.tags` cannot change `b.tags`.',
  'python-dataclass-post-init': 'Dataclasses insert a call to `self.__post_init__()` at the end of the generated initializer. By then, both step counts are available on `self`, so the method can enforce their relationship. Raising there prevents construction from returning a schedule whose warmup is as long as or longer than training.',
  'python-dataclass-classvar': '`name` is instance data, so it appears in `RunConfig(...)` and participates in generated dataclass behavior. `VERSION` is shared class-level information. `ClassVar` tells dataclasses to ignore it as a field, even though normal attribute lookup still lets `config.VERSION` resolve to `RunConfig.VERSION`.',
  'python-dataclass-frozen-shallow': '`frozen=True` protects the field binding: `config.tags = ...` is rejected. The binding still points to an ordinary mutable list, and `config.tags.append(...)` changes that list without assigning the field. Use an immutable field type such as `tuple[str, ...]` when the contents must also remain fixed.',
  'python-dataclass-kw-only': 'The generated initializer behaves like `def __init__(self, *, epochs: int, lr: float)`. The bare `*` forbids positional arguments after it, so `RunConfig(10, 0.001)` fails while `RunConfig(epochs=10, lr=0.001)` works. This is different from `**kwargs`, which collects arbitrary named arguments.',
  'python-dataclass-slots': 'A normal dataclass instance usually stores attributes in a flexible `__dict__`, so `point.xx = 3.0` can silently create the wrong attribute. Slots replace that open-ended storage with declared names such as `x` and `y`; because `xx` is not one of them, the assignment raises `AttributeError`. The fixed layout often uses less memory, especially when a program creates many small instances.',
  'python-dataclass-replace': '`dataclasses.replace(original, lr=...)` calls the dataclass type to create a separate object, copying unchanged fields and substituting the named changes. The original binding stays untouched, and the new construction reruns `__post_init__` checks.',
  'python-dataclass-asdict': '`dataclasses.asdict` recursively converts dataclass fields into dictionaries and deep-copies other leaves. That behavior is convenient for small value records but can duplicate a large tensor or fail on clients, locks, and other runtime resources that were never meant to be serialized.',

  // Pydantic v2
  'python-pydantic-boundary-choice': 'A dataclass removes boilerplate for a Python record but does not validate annotations at runtime. A Pydantic `BaseModel` parses and validates input, so it is useful where JSON, configuration files, or user input cross into trusted application code.',
  'python-pydantic-dataclass': 'A Pydantic dataclass keeps generated dataclass methods while adding runtime validation to construction. It still is not a `BaseModel`; use a `TypeAdapter` when the dataclass needs Pydantic schema or serialization operations.',
  'python-pydantic-default-coercion': 'Coercion is useful at text-heavy boundaries, but it can hide upstream schema drift. Decide deliberately whether a boundary should normalize compatible values or reject anything with the wrong runtime type.',
  'python-pydantic-strict-mode': 'Strictness changes the boundary contract from “convert if possible” to “require the expected type.” It can be applied globally or narrowly where coercion would make bad input look valid.',
  'python-pydantic-extra-forbid': 'Ignoring unknown keys makes forward compatibility easy but also hides typos. For configuration files, forbidding extras usually gives a safer failure: the misspelled control cannot silently fall back to its default.',
  'python-pydantic-positive-field': '`Field(gt=0)` means the value must be strictly greater than zero; unlike `ge=0`, it excludes zero itself. A field constraint keeps validation, generated schema, and the error location attached to the same declaration.',
  'python-pydantic-default-factory': 'The default factory runs for every successful model construction. It gives each model an independent mutable value and can also derive a default from already validated earlier fields when needed.',
  'python-pydantic-field-validator': 'A field validator owns one field’s normalization or local rule. Choose before-validation only when raw input must be transformed; after-validation can rely on the parsed field type.',
  'python-pydantic-model-validator': 'Cross-field rules belong at model scope because no single field owns the invariant. An after-model validator sees the completed typed model and can return it after checking the relationship.',
  'python-pydantic-assignment-validation': 'Construction-time validity does not guarantee lifetime validity when fields remain mutable. Assignment validation moves the boundary to each write, at an ongoing runtime cost.',
  'python-pydantic-io-api': '`model_validate` accepts Python objects such as dictionaries; `model_dump` returns Python containers and scalar values. Their `_json` counterparts accept or return JSON text or bytes, avoiding a redundant decode or encode step at a JSON boundary.',
  'python-pydantic-type-adapter': '`TypeAdapter(annotation)` gives a standalone type annotation Pydantic\'s validation, serialization, and schema operations. It avoids inventing a one-field wrapper model for values such as `list[int]` and should be reused when the same schema is validated repeatedly.',
  'python-pydantic-private-attr': '`PrivateAttr` stores operational state that is not part of the validated data model. Because a private attribute is absent from schemas and dumps, code must recreate caches and clients after loading a serialized model.',
  'python-pydantic-arbitrary-tensor': 'Allowing an arbitrary class only proves that the object has that class. Tensor invariants—rank, shape, dtype, device, finiteness, or value range—still need explicit validation.',
  'python-pydantic-model-construct': '`model_construct` assigns supplied values without parsing, coercion, or validators. The caller therefore owns every invariant; an invalid string can enter an integer field silently if the payload was not validated elsewhere.',
  'python-pydantic-model-copy': 'A shallow model copy creates a new outer model while retaining nested references. Choose `deep=True` only when nested isolation is required, because deep copying can be expensive or unsupported for runtime resources.',
  'python-pydantic-discriminated-union': 'A discriminated union uses one shared literal field, such as `type`, to choose among several model shapes. After Pydantic reads the tag, it validates only the selected variant and reports errors against that concrete configuration.',

  // Reliability and I/O
  'python-narrow-exception': 'An exception boundary should catch only failures it can translate, retry, or recover from. Broad catches turn programming defects into misleading configuration errors and make the original fault harder to locate.',
  'python-explicit-exception-cause': 'Exception chaining keeps both abstraction levels: the outer error explains the failed operation, while the cause preserves the low-level reason and traceback needed to diagnose it.',
  'python-context-manager-cleanup': 'A context manager encodes acquisition and release as one protocol. Its exit method runs while an exception is propagating, so resource cleanup does not depend on every control-flow path remembering to close.',
  'python-assert-input-validation': 'Assertions document conditions that should already be true if the program is correct. External data can always be wrong, so validate it with an explicit branch and stable exception regardless of optimization mode.',
  'python-str-vs-bytes': 'Encoding maps Unicode text to bytes; decoding maps bytes to text. Make the codec explicit at the boundary so the rest of the program operates on one representation with known meaning.',
  'python-sorted-glob': 'Directory iteration order can vary across filesystems, runs, and machines. Sorting converts that environmental accident into a stable ingestion order before it can affect splits, hashes, or outputs.',
  'python-untrusted-pickle': 'Pickle reconstructs Python objects by executing a serialization program, not by parsing inert data. Authentication or a safer data format is required when the producer is outside the trust boundary.',
  'python-stable-experiment-id': 'The digest is stable only if the serialized bytes are stable. Canonicalize key order, numeric representation, and omitted defaults before hashing so equivalent configurations produce the same identity.',
  'python-multiprocessing-entrypoint': 'Spawn starts a fresh interpreter that imports the main module. The guard prevents child imports from recursively creating more processes, and top-level callables give pickle an importable name.',
  'python-concurrency-choice': 'Match the tool to the waiting model. Threads help when native or blocking work releases the interpreter, processes isolate CPU-bound Python execution, and `asyncio` needs nonblocking libraries plus explicit cooperative scheduling.',
};
