export interface TriviaCard {
  id: string;
  topic: string;
  question: string;
  answer: string;
  code?: string;
  detail?: string;
}

export interface TriviaDeckData {
  id: string;
  title: string;
  cards: TriviaCard[];
}

export const pythonTriviaDeck: TriviaDeckData = {
  id: 'python-interview-trivia-v1',
  title: 'Python interview trivia',
  cards: [
    {
      id: 'python-pass-by-assignment',
      topic: 'Semantics',
      question: 'Are Python arguments passed by value or by reference?',
      answer: 'Python uses pass-by-assignment, also called object sharing. A function receives another binding to the same object. Mutating that object can affect the caller; rebinding the local name cannot.',
    },
    {
      id: 'python-is-equality',
      topic: 'Semantics',
      question: 'What is the difference between `is` and `==`?',
      answer: '`==` asks whether values compare equal. `is` asks whether both names refer to the exact same object. Use `is None` for the `None` singleton.',
    },
    {
      id: 'python-mutable-default',
      topic: 'Semantics',
      question: 'Why is a mutable default argument dangerous?',
      answer: 'Default expressions run once when the function is defined. Every call that omits the argument therefore reuses the same mutable object.',
      code: 'def add(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items',
    },
    {
      id: 'python-default-evaluation',
      topic: 'Semantics',
      question: 'When are function default arguments evaluated?',
      answer: 'Once, when the `def` statement executes—not each time the function is called. This also means a default can capture an earlier value of a global or enclosing expression.',
    },
    {
      id: 'python-shallow-deep-copy',
      topic: 'Semantics',
      question: 'How do shallow and deep copies differ?',
      answer: 'A shallow copy creates a new outer object but preserves references to nested objects. A deep copy recursively copies nested state, subject to custom copy behavior and memoization.',
    },
    {
      id: 'python-assignment-copy',
      topic: 'Semantics',
      question: 'Does `b = a` copy the object bound to `a`?',
      answer: 'No. It binds `b` to the same object. Whether later changes are visible through both names depends on mutation versus rebinding.',
    },
    {
      id: 'python-tuple-mutability',
      topic: 'Semantics',
      question: 'Does a tuple guarantee that everything inside it is immutable?',
      answer: 'No. A tuple fixes which object references occupy its slots, but a referenced object can still be mutable. A tuple containing a list cannot be hashed.',
    },
    {
      id: 'python-truthiness',
      topic: 'Semantics',
      question: 'What are `bool([])`, `bool("False")`, `bool(0)`, and `bool(float("nan"))`?',
      answer: '`False`, `True`, `False`, and `True`. Empty containers and numeric zero are falsy; nonempty strings and NaN are truthy.',
    },
    {
      id: 'python-sort-return',
      topic: 'Semantics',
      question: 'Why does `items = items.sort()` usually break code?',
      answer: '`list.sort()` mutates the list in place and returns `None`. Use `items.sort()` for in-place mutation or `sorted(items)` for a new list.',
    },
    {
      id: 'python-identity-interning',
      topic: 'Semantics',
      question: 'Why must code not rely on `a is b` for equal integers or strings?',
      answer: 'An implementation may intern or reuse some immutable objects, but that is not the value-comparison contract. Identity reuse can vary by value, expression, implementation, and run.',
    },
    {
      id: 'python-iterable-iterator',
      topic: 'Iteration',
      question: 'What is the difference between an iterable and an iterator?',
      answer: 'An iterable can produce an iterator through `iter(obj)`. An iterator carries traversal state, returns itself from `__iter__`, and produces values through `__next__` until `StopIteration`.',
    },
    {
      id: 'python-generator-single-use',
      topic: 'Iteration',
      question: 'Why are generators usually single-use?',
      answer: 'A generator is an iterator with suspended execution state. Once it reaches completion, it remains exhausted; iterating it again does not recreate the function call.',
    },
    {
      id: 'python-yield-return',
      topic: 'Iteration',
      question: 'How does `yield` differ from `return`?',
      answer: '`yield` produces a value and suspends the frame so execution can resume. `return` terminates the function; inside a generator, its value becomes the `StopIteration.value` seen by a delegating caller.',
    },
    {
      id: 'python-list-generator-comprehension',
      topic: 'Iteration',
      question: 'List comprehension or generator expression: what changes?',
      answer: 'A list comprehension eagerly materializes every result. A generator expression computes lazily, uses less peak memory, and can normally be consumed only once.',
    },
    {
      id: 'python-next-default',
      topic: 'Iteration',
      question: 'What does `next(iterator, default)` do?',
      answer: 'It returns the next item, or `default` if the iterator is exhausted. Without the second argument, exhaustion raises `StopIteration`.',
    },
    {
      id: 'python-yield-from',
      topic: 'Iteration',
      question: 'What does `yield from subiterator` add beyond a simple loop?',
      answer: 'It delegates iteration and also forwards `send`, `throw`, and `close` interactions. When the subgenerator returns, its return value becomes the value of the `yield from` expression.',
    },
    {
      id: 'python-legb',
      topic: 'Scope & functions',
      question: 'What is Python’s LEGB name-resolution order?',
      answer: 'Local, Enclosing, Global, then Built-in. Assignment normally creates a local binding unless the name is declared `nonlocal` or `global`.',
    },
    {
      id: 'python-late-binding',
      topic: 'Scope & functions',
      question: 'Why do lambdas created in a loop often all use the final loop value?',
      answer: 'Closures capture the variable binding, not a snapshot of its value. Bind the current value as a default argument, such as `lambda i=i: i`, or use a factory function.',
    },
    {
      id: 'python-global-nonlocal',
      topic: 'Scope & functions',
      question: 'How do `global` and `nonlocal` differ?',
      answer: '`global` makes assignments target a module-level binding. `nonlocal` targets the nearest matching binding in an enclosing function scope.',
    },
    {
      id: 'python-loop-scope',
      topic: 'Scope & functions',
      question: 'Do `for` loops create block scope in Python?',
      answer: 'No. The loop variable remains in the surrounding function or module scope. Python 3 comprehensions, however, execute their iteration variable in a separate implicit scope.',
    },
    {
      id: 'python-signature-markers',
      topic: 'Scope & functions',
      question: 'What do `/` and `*` mean in a Python function signature?',
      answer: 'Parameters before `/` are positional-only. Parameters after a bare `*` are keyword-only. These markers let an API control how callers bind arguments.',
    },
    {
      id: 'python-args-kwargs',
      topic: 'Scope & functions',
      question: 'What do `*args` and `**kwargs` receive?',
      answer: '`*args` collects extra positional arguments into a tuple. `**kwargs` collects extra keyword arguments into a dictionary. The same operators unpack iterables and mappings at a call site.',
    },
    {
      id: 'python-decorator-timing',
      topic: 'Scope & functions',
      question: 'When is a decorator applied, and why use `functools.wraps`?',
      answer: 'The decorator expression runs when the decorated `def` or `class` executes. `functools.wraps` preserves metadata such as the wrapped name, documentation, annotations, and `__wrapped__` link.',
    },
    {
      id: 'python-hashability',
      topic: 'Collections',
      question: 'What makes an object suitable as a dictionary key?',
      answer: 'It must be hashable: its hash must remain stable while stored, and objects that compare equal must have equal hashes. Mutable built-in containers are therefore unhashable.',
    },
    {
      id: 'python-dict-complexity',
      topic: 'Collections',
      question: 'What is dictionary lookup complexity?',
      answer: 'Average-case lookup, insertion, and deletion are `O(1)`; worst case is `O(n)`. A hash collision does not overwrite an unrelated key because equality resolves candidates.',
    },
    {
      id: 'python-dict-order',
      topic: 'Collections',
      question: 'Do dictionaries preserve order?',
      answer: 'Yes, insertion order is a language guarantee in modern Python. That does not mean keys are sorted.',
    },
    {
      id: 'python-list-append',
      topic: 'Collections',
      question: 'Why is list append called amortized `O(1)`?',
      answer: 'Most appends write into spare capacity. An occasional resize allocates a larger array and copies existing references, so one append can be `O(n)` while the average across many appends stays constant.',
    },
    {
      id: 'python-deque',
      topic: 'Collections',
      question: 'When is `collections.deque` better than a list?',
      answer: 'Use a deque for frequent additions or removals at either end. A list is efficient at the right end but inserting or removing at the front shifts `O(n)` references.',
    },
    {
      id: 'python-set-frozenset',
      topic: 'Collections',
      question: 'What is the difference between `set` and `frozenset`?',
      answer: 'Both hold unique hashable elements. A set is mutable and unhashable; a frozenset is immutable and can be hashable, so it can serve as a dictionary key or another set’s member.',
    },
    {
      id: 'python-class-instance-attributes',
      topic: 'Object model',
      question: 'How do class and instance attributes differ?',
      answer: 'A class attribute lives on the class and is shared through lookup. Assigning `self.name` creates or replaces an instance attribute that shadows the class attribute. A mutable class attribute can unintentionally share state.',
    },
    {
      id: 'python-method-kinds',
      topic: 'Object model',
      question: 'Instance method, class method, or static method?',
      answer: 'An instance method receives `self`. A class method receives `cls` and fits polymorphic alternative constructors. A static method receives neither and is simply namespaced under the class.',
    },
    {
      id: 'python-super-mro',
      topic: 'Object model',
      question: 'What does zero-argument `super()` actually follow?',
      answer: 'It continues lookup after the current class in the instance type’s method resolution order. It does not mean “call my named parent,” which is why cooperative multiple inheritance can work.',
    },
    {
      id: 'python-new-init',
      topic: 'Object model',
      question: 'How do `__new__` and `__init__` differ?',
      answer: '`__new__` creates and returns the instance; `__init__` initializes an instance already created. Immutable subclasses and metaprogramming are common reasons to customize `__new__`.',
    },
    {
      id: 'python-slots',
      topic: 'Object model',
      question: 'What does `__slots__` do?',
      answer: 'It declares a fixed set of instance attributes and can avoid a per-instance `__dict__`, reducing memory. Trade-offs include inheritance complexity, weak-reference configuration, and less dynamic attribute assignment.',
    },
    {
      id: 'python-descriptor',
      topic: 'Object model',
      question: 'What is a descriptor?',
      answer: 'An object that controls attribute access through methods such as `__get__`, `__set__`, or `__delete__`. Functions, bound methods, `property`, and many ORM fields use the descriptor protocol.',
    },
    {
      id: 'python-eq-hash',
      topic: 'Object model',
      question: 'What usually happens to `__hash__` when a class defines value-based `__eq__`?',
      answer: 'Python normally makes instances unhashable unless a compatible hash is supplied. This prevents equal, mutable objects from violating dictionary and set invariants.',
    },
    {
      id: 'python-not-implemented',
      topic: 'Object model',
      question: 'How does returning `NotImplemented` differ from raising `NotImplementedError`?',
      answer: 'A binary special method returns `NotImplemented` to let Python try the reflected operation or another comparison path. `NotImplementedError` is an exception for an intentionally unimplemented API.',
    },
    {
      id: 'python-bare-except',
      topic: 'Errors & resources',
      question: 'Why is a bare `except:` usually wrong?',
      answer: 'It catches `BaseException` subclasses such as `KeyboardInterrupt` and `SystemExit`, not only ordinary application errors. Catch the narrowest exception that the code can handle meaningfully.',
    },
    {
      id: 'python-exception-chaining',
      topic: 'Errors & resources',
      question: 'What does `raise ConfigError(...) from exc` do?',
      answer: 'It translates the error while preserving `exc` as the explicit cause. `raise ... from None` suppresses display of the implicit context; a bare `raise` re-raises the active exception.',
    },
    {
      id: 'python-context-manager',
      topic: 'Errors & resources',
      question: 'Can a context manager suppress an exception?',
      answer: 'Yes. `__exit__` receives the exception type, value, and traceback; returning a truthy value suppresses it. Returning falsey propagates it after cleanup.',
    },
    {
      id: 'python-finally',
      topic: 'Errors & resources',
      question: 'Does `finally` run if `try` returns?',
      answer: 'Normally yes: Python evaluates the return value, executes `finally`, then returns. Process termination, `os._exit`, or a fatal crash can bypass it, so external durability still needs stronger guarantees.',
    },
    {
      id: 'python-eafp-lbyl',
      topic: 'Errors & resources',
      question: 'What are EAFP and LBYL?',
      answer: 'EAFP attempts an operation and handles an expected failure. LBYL checks first. EAFP often matches Python APIs and avoids some check-then-act races, but predictable expensive failures can justify LBYL.',
    },
    {
      id: 'python-gil',
      topic: 'Concurrency',
      question: 'What practical restriction does the traditional CPython GIL impose?',
      answer: 'Only one thread at a time executes Python bytecode in a traditional GIL-enabled process. Threads can still overlap I/O, and native libraries such as PyTorch can release the GIL and run parallel kernels.',
    },
    {
      id: 'python-concurrency-models',
      topic: 'Concurrency',
      question: 'When would you choose threads, processes, or `asyncio`?',
      answer: 'Threads suit blocking I/O and shared-memory integration. Processes provide CPU parallelism and isolation at serialization cost. `asyncio` suits many cooperative I/O tasks when the full call path is nonblocking.',
    },
    {
      id: 'python-blocking-async',
      topic: 'Concurrency',
      question: 'What happens when blocking code runs inside an async coroutine?',
      answer: 'It blocks the event-loop thread, delaying every other task on that loop. Use an async API, move the call to a thread or process executor, or redesign the boundary.',
    },
    {
      id: 'python-race-gil',
      topic: 'Concurrency',
      question: 'Does the GIL eliminate race conditions?',
      answer: 'No. A logical operation can span several bytecode steps, threads can switch between them, and native code may release the GIL. Shared mutable state still needs a synchronization design.',
    },
    {
      id: 'python-memory-management',
      topic: 'Runtime & typing',
      question: 'How does CPython usually reclaim objects?',
      answer: 'Reference counting handles most object lifetimes, and a cyclic garbage collector finds unreachable reference cycles. Portable code should use context managers—not destructor timing—for external resources.',
    },
    {
      id: 'python-import-cache',
      topic: 'Runtime & typing',
      question: 'What happens when a module is imported twice?',
      answer: 'The first import creates a module object and executes its top-level code. Later imports normally reuse the object cached in `sys.modules`; they do not rerun the module automatically.',
    },
    {
      id: 'python-any-object',
      topic: 'Runtime & typing',
      question: 'How does `typing.Any` differ from `object`?',
      answer: '`Any` tells a static checker to allow essentially any operation and propagates dynamic typing. Every value is an `object`, but code receiving `object` must narrow the type before using type-specific operations.',
    },
    {
      id: 'python-protocol',
      topic: 'Runtime & typing',
      question: 'What does a typing `Protocol` express?',
      answer: 'Structural subtyping: a value satisfies the protocol if it provides the required members, without inheriting from or registering with the protocol. Runtime checks require `@runtime_checkable` and remain limited.',
    },
    {
      id: 'python-stdlib-dataclass',
      topic: 'Data modeling',
      question: 'What does a standard-library dataclass provide—and what does it not provide?',
      answer: '`@dataclass` can generate methods such as `__init__`, `__repr__`, and `__eq__` from annotated fields. The annotations are not runtime validation; invalid types are accepted unless your own code checks them.',
    },
    {
      id: 'python-dataclass-default-factory',
      topic: 'Data modeling',
      question: 'How should a dataclass define a mutable default?',
      answer: 'Use `field(default_factory=list)` or another factory so each instance receives a fresh value. Modern dataclasses reject many unhashable defaults because they are likely mutable.',
      code: 'from dataclasses import dataclass, field\n\n@dataclass\nclass Batch:\n    values: list[int] = field(default_factory=list)',
    },
    {
      id: 'python-pydantic-dataclass',
      topic: 'Data modeling',
      question: 'Pydantic dataclass versus standard dataclass: what is the core difference?',
      answer: 'A standard dataclass is a lightweight generated data container and does not enforce its annotations at runtime. A Pydantic dataclass validates constructor input and, in normal lax mode, may coerce compatible values. Strict rejection is configurable—not the default.',
      detail: 'Assignment is not automatically revalidated unless `validate_assignment=True` is configured.',
    },
    {
      id: 'python-pydantic-strict',
      topic: 'Data modeling',
      question: 'Does a Pydantic dataclass enforce strict types by default?',
      answer: 'No. Pydantic defaults to lax validation for many types, so a value such as `"42"` may become integer `42`. Configure strict mode globally or at the field or validation-call level when coercion is unwanted.',
      code: 'from pydantic import ConfigDict\nfrom pydantic.dataclasses import dataclass\n\n@dataclass(config=ConfigDict(strict=True))\nclass Job:\n    retries: int',
    },
    {
      id: 'python-pydantic-model-vs-dataclass',
      topic: 'Data modeling',
      question: 'Why might `BaseModel` be preferable to a Pydantic dataclass?',
      answer: '`BaseModel` is Pydantic’s primary model API and directly exposes model validation, serialization, copying, and JSON-schema methods. A Pydantic dataclass keeps dataclass semantics; use `TypeAdapter` for many equivalent dump or schema operations.',
    },
    {
      id: 'python-frozen-dataclass',
      topic: 'Data modeling',
      question: 'Does `@dataclass(frozen=True)` make the full object graph immutable?',
      answer: 'No. It blocks normal field reassignment on the instance, but a field can still reference a mutable list, dictionary, or custom object. Frozen is shallow, and hashability still depends on generated-method rules and field values.',
    },
  ],
};

export const pytorchTriviaDeck: TriviaDeckData = {
  id: 'pytorch-interview-trivia-v1',
  title: 'PyTorch interview trivia',
  cards: [
    {
      id: 'torch-tensor-metadata',
      topic: 'Tensors',
      question: 'Which properties define how a dense strided tensor maps indices to memory?',
      answer: 'Storage, storage offset, shape, and strides define the mapping. Dtype determines element interpretation, while device and layout determine where and how the storage is managed.',
    },
    {
      id: 'torch-view-reshape',
      topic: 'Tensors',
      question: 'How do `view` and `reshape` differ?',
      answer: '`view` requires strides compatible with the requested shape and fails otherwise. `reshape` returns a view when possible but may silently allocate a copy, so callers should not assume aliasing.',
    },
    {
      id: 'torch-transpose-contiguous',
      topic: 'Tensors',
      question: 'Does `transpose` copy tensor data?',
      answer: 'Usually no. It returns a view with reordered shape and strides. Some later kernels require a particular layout and may need `contiguous()`, which copies only when the requested memory format is absent.',
    },
    {
      id: 'torch-clone-detach',
      topic: 'Tensors',
      question: 'What is the difference between `clone()` and `detach()`?',
      answer: '`clone()` copies values into new storage but preserves the autograd connection. `detach()` cuts the incoming graph edge but usually shares storage. Use `x.detach().clone()` for an independent snapshot.',
    },
    {
      id: 'torch-broadcasting',
      topic: 'Tensors',
      question: 'What is PyTorch’s broadcasting rule?',
      answer: 'Compare dimensions from the right. Aligned dimensions must be equal or one must be `1`; missing leading dimensions act like `1`. Expansion can use zero strides instead of copying the smaller input.',
    },
    {
      id: 'torch-cat-stack',
      topic: 'Tensors',
      question: 'How do `torch.cat` and `torch.stack` change shape?',
      answer: '`cat` joins tensors along an existing axis and preserves rank. `stack` requires equal input shapes and inserts a new axis, increasing rank by one.',
    },
    {
      id: 'torch-indexing-copy',
      topic: 'Tensors',
      question: 'Which tensor indexing operations usually return views versus copies?',
      answer: 'Basic indexing with integers and slices usually returns a view. Advanced indexing with integer tensors, lists, or boolean masks returns selected values in new storage; assignment through that syntax still writes to the destination.',
    },
    {
      id: 'torch-inplace-promotion',
      topic: 'Tensors',
      question: 'Why can a mixed-dtype expression work out of place but fail in place?',
      answer: 'An out-of-place operation can allocate the promoted result dtype. An in-place operation must write back into the destination dtype, so PyTorch rejects conversions that cannot satisfy that contract safely.',
    },
    {
      id: 'torch-to-noop',
      topic: 'Tensors',
      question: 'Does `x.to(device=x.device, dtype=x.dtype)` always copy?',
      answer: 'No. If no conversion is needed, `to` can return `x` itself. Pass `copy=True` only when a distinct tensor is required.',
    },
    {
      id: 'torch-empty',
      topic: 'Tensors',
      question: 'What values does `torch.empty` contain?',
      answer: 'Uninitialized values from the allocated memory. The code must write every element before reading it; `empty` is a performance-oriented allocation primitive, not a zero-filled tensor.',
    },
    {
      id: 'torch-requires-grad-recording',
      topic: 'Autograd',
      question: 'When does autograd record an operation in normal grad mode?',
      answer: 'When at least one input requires gradients and the operation is differentiable. The output receives graph history through `grad_fn`; leaf tensors supplied by the user normally have no `grad_fn`.',
    },
    {
      id: 'torch-leaf-grad',
      topic: 'Autograd',
      question: 'Which tensors receive a populated `.grad` after backward?',
      answer: 'Leaf tensors with `requires_grad=True` accumulate gradients by default. Intermediates need `retain_grad()` if their `.grad` field must be inspected.',
    },
    {
      id: 'torch-grad-accumulation',
      topic: 'Autograd',
      question: 'Does `backward()` overwrite existing parameter gradients?',
      answer: 'No. It accumulates into `.grad`. Clear gradients at the intended accumulation boundary, commonly with `optimizer.zero_grad(set_to_none=True)`.',
    },
    {
      id: 'torch-none-zero-grad',
      topic: 'Autograd',
      question: 'Why can a gradient of `None` be more informative than a zero tensor?',
      answer: '`None` means no gradient has been accumulated for that parameter. A zero tensor means a differentiable path reached it and produced zero. Optimizers may also treat missing and zero gradients differently.',
    },
    {
      id: 'torch-nonscalar-backward',
      topic: 'Autograd',
      question: 'Why does a non-scalar tensor need an argument to `backward()`?',
      answer: 'The argument supplies the upstream vector for a vector-Jacobian product. A scalar loss has the unambiguous default upstream gradient of one.',
    },
    {
      id: 'torch-no-grad-inference',
      topic: 'Autograd',
      question: 'How does `torch.inference_mode()` differ from `torch.no_grad()`?',
      answer: 'Both prevent backward-graph recording. Inference mode also removes more autograd bookkeeping and can be faster, but tensors created there cannot later participate normally in a graph recorded by autograd.',
    },
    {
      id: 'torch-eval-no-grad',
      topic: 'Autograd',
      question: 'Does `model.eval()` disable gradient tracking?',
      answer: 'No. `eval()` changes the `training` flag used by modules such as Dropout and BatchNorm. Gradient mode is orthogonal; evaluation usually combines `model.eval()` with `torch.inference_mode()` or `torch.no_grad()`.',
    },
    {
      id: 'torch-inplace-autograd',
      topic: 'Autograd',
      question: 'Why can an in-place operation trigger an autograd version-counter error?',
      answer: 'Backward may need a tensor value saved during forward. If an in-place write changes that storage before backward, the saved value is no longer valid, so autograd detects the version mismatch.',
    },
    {
      id: 'torch-retain-create-graph',
      topic: 'Autograd',
      question: 'How do `retain_graph=True` and `create_graph=True` differ?',
      answer: '`retain_graph` keeps the current forward graph available for another backward traversal. `create_graph` records the derivative computation itself so higher-order derivatives can be taken.',
    },
    {
      id: 'torch-grad-vs-backward',
      topic: 'Autograd',
      question: '`torch.autograd.grad` versus `Tensor.backward`: when does each fit?',
      answer: '`backward` accumulates gradients into graph leaves, matching optimizer training loops. `autograd.grad` returns gradients for named inputs directly and is useful for functional gradients, penalties, and higher-order work.',
    },
    {
      id: 'torch-parameter-registration',
      topic: 'Modules & state',
      question: 'What makes `nn.Parameter` different from a tensor with `requires_grad=True`?',
      answer: 'Assigning an `nn.Parameter` as a module attribute registers it, so it appears in `parameters()` and `state_dict()`. A plain tensor is not registered as a parameter merely because it requires gradients.',
    },
    {
      id: 'torch-module-list',
      topic: 'Modules & state',
      question: 'Why use `nn.ModuleList` instead of a Python list of submodules?',
      answer: '`ModuleList` registers its children. A plain list can hold working modules, but the parent will not discover their parameters, device moves, training-mode changes, or state unless you register them another way.',
    },
    {
      id: 'torch-parameter-buffer',
      topic: 'Modules & state',
      question: 'Parameter versus buffer: what is the contract?',
      answer: 'Parameters are trainable model state exposed to optimizers. Buffers are non-parameter state that follows device moves and normally appears in `state_dict`, such as BatchNorm running statistics.',
    },
    {
      id: 'torch-state-dict',
      topic: 'Modules & state',
      question: 'What does a module `state_dict` contain?',
      answer: 'A mapping of registered parameters and persistent buffers. It does not serialize arbitrary Python attributes or the model’s class definition, so code must reconstruct the module before loading weights.',
    },
    {
      id: 'torch-load-state-strict',
      topic: 'Modules & state',
      question: 'What does `load_state_dict(..., strict=True)` check?',
      answer: 'It requires checkpoint keys to match the module’s expected parameter and persistent-buffer keys. With `strict=False`, inspect the returned missing and unexpected keys instead of silently assuming a complete load.',
    },
    {
      id: 'torch-forward-call',
      topic: 'Modules & state',
      question: 'Why call `model(x)` instead of `model.forward(x)`?',
      answer: '`nn.Module.__call__` wraps `forward` with framework behavior such as hooks and compiled-call machinery. Directly calling `forward` bypasses that wrapper.',
    },
    {
      id: 'torch-cross-entropy-logits',
      topic: 'Training',
      question: 'Should `CrossEntropyLoss` receive softmax probabilities?',
      answer: 'No. It expects unnormalized logits and internally performs the stable log-softmax plus negative log-likelihood calculation. Applying softmax first loses numerical stability and changes the intended interface.',
    },
    {
      id: 'torch-cross-entropy-target',
      topic: 'Training',
      question: 'What target dtype and shape does class-index cross entropy expect?',
      answer: 'For logits shaped `(N, C, ...)`, class-index targets normally use integer `torch.long` values shaped `(N, ...)`, with each value in `[0, C)`. Probability targets use the same shape as logits and a floating dtype.',
    },
    {
      id: 'torch-bce-logits',
      topic: 'Training',
      question: 'Why prefer `BCEWithLogitsLoss` over `sigmoid` followed by binary cross entropy?',
      answer: 'The fused loss uses a numerically stable formulation that avoids materializing extreme probabilities. It expects logits and floating targets, commonly with the same shape.',
    },
    {
      id: 'torch-training-order',
      topic: 'Training',
      question: 'What is the standard optimizer-step order?',
      answer: 'Clear gradients, run forward, compute loss, call backward, then step the optimizer. Gradient clipping, logging, schedulers, and accumulation add boundaries that must be placed deliberately.',
      code: 'optimizer.zero_grad(set_to_none=True)\nloss = criterion(model(inputs), targets)\nloss.backward()\noptimizer.step()',
    },
    {
      id: 'torch-amp',
      topic: 'Training',
      question: 'What jobs do autocast and gradient scaling perform?',
      answer: 'Autocast chooses lower precision for eligible operations while keeping sensitive operations in safer dtypes. Gradient scaling helps FP16 gradients avoid underflow; BF16 often does not need scaling because it has FP32-like exponent range.',
    },
    {
      id: 'torch-clip-unscale',
      topic: 'Training',
      question: 'When using a gradient scaler, when should gradients be clipped?',
      answer: 'Unscale the optimizer’s gradients first, then clip, then call the scaler’s step and update. Clipping scaled gradients applies the wrong threshold.',
    },
    {
      id: 'torch-gradient-accumulation-loss',
      topic: 'Training',
      question: 'Why is loss often divided by the number of accumulation steps?',
      answer: 'Backward sums gradient contributions. Dividing each microbatch loss makes the accumulated gradient match the mean over the effective batch; omitting the division scales the gradient and changes the effective learning rate.',
    },
    {
      id: 'torch-checkpoint',
      topic: 'Training',
      question: 'What belongs in a resumable training checkpoint?',
      answer: 'At minimum: model state, optimizer state, current step or epoch, and scheduler or scaler state when used. Exact continuation may also require random-number-generator, sampler, and data-pipeline state.',
    },
    {
      id: 'torch-dataset-kinds',
      topic: 'Data loading',
      question: 'Map-style versus iterable-style dataset: what changes?',
      answer: 'A map-style dataset supports keyed indexing and usually length. An `IterableDataset` yields a stream and fits logs, remote sources, or generated data, but each worker must shard the stream to avoid duplicates.',
    },
    {
      id: 'torch-dataloader-workers',
      topic: 'Data loading',
      question: 'What does `DataLoader(num_workers > 0)` do?',
      answer: 'It loads and processes samples in subprocesses, which can overlap CPU input work with model execution. More workers are not always faster because startup, serialization, memory, and storage contention can dominate.',
    },
    {
      id: 'torch-pin-memory',
      topic: 'Data loading',
      question: 'What does `pin_memory=True` help with?',
      answer: 'Workers place CPU tensors in page-locked host memory, enabling faster and potentially asynchronous host-to-CUDA copies. Pair the later device transfer with `non_blocking=True` when the rest of the pipeline can overlap it.',
    },
    {
      id: 'torch-persistent-workers',
      topic: 'Data loading',
      question: 'What trade-off does `persistent_workers=True` make?',
      answer: 'It keeps worker processes and their dataset instances alive between epochs, reducing repeated startup cost while retaining their memory and other resources for longer.',
    },
    {
      id: 'torch-worker-cuda-tensors',
      topic: 'Data loading',
      question: 'Should multiprocess DataLoader workers normally return CUDA tensors?',
      answer: 'No. CUDA plus multiprocessing has subtle lifetime and initialization constraints. PyTorch recommends returning CPU tensors, optionally pinned, and moving batches to the accelerator in the training process.',
    },
    {
      id: 'torch-reproducibility',
      topic: 'Data loading',
      question: 'Does setting `torch.manual_seed` guarantee identical results everywhere?',
      answer: 'No. Reproducibility can depend on device, release, nondeterministic kernels, library seeds, worker seeds, and algorithm selection. Deterministic settings can reduce variance but may cost performance or lack an implementation.',
    },
    {
      id: 'torch-ddp-data-parallel',
      topic: 'Distributed',
      question: 'Why is `DistributedDataParallel` preferred over `nn.DataParallel`?',
      answer: 'DDP uses one process per device and synchronizes gradients efficiently without a single Python thread scattering work and gathering outputs. It also scales across machines.',
    },
    {
      id: 'torch-ddp-inputs',
      topic: 'Distributed',
      question: 'Does DDP automatically split the input batch across ranks?',
      answer: 'No. DDP replicates the module and synchronizes gradients. The program must partition input data, commonly with `DistributedSampler` or explicit iterable-dataset sharding.',
    },
    {
      id: 'torch-distributed-sampler-epoch',
      topic: 'Distributed',
      question: 'Why call `DistributedSampler.set_epoch(epoch)`?',
      answer: 'It changes the deterministic shuffle seed each epoch while keeping ranks coordinated. Without it, the sampler can produce the same ordering every epoch.',
    },
    {
      id: 'torch-ddp-unused',
      topic: 'Distributed',
      question: 'Why can conditional model branches cause a DDP reduction error?',
      answer: 'A rank may leave some registered parameters unused, so expected gradient reductions do not occur. `find_unused_parameters=True` can detect this at overhead, but stable graph design is usually better.',
    },
    {
      id: 'torch-fsdp',
      topic: 'Distributed',
      question: 'What memory problem does Fully Sharded Data Parallel address?',
      answer: 'FSDP shards parameters, gradients, and optimizer state across ranks, materializing fuller parameter views only when computation needs them. DDP normally keeps a complete model replica on every rank.',
    },
    {
      id: 'torch-compile',
      topic: 'Performance',
      question: 'What does `torch.compile` try to optimize?',
      answer: 'It captures regions of Python-level PyTorch execution, transforms the forward and backward graphs, and generates optimized kernels. Unsupported Python behavior can create graph breaks, and changing shapes or guards can trigger recompilation.',
    },
    {
      id: 'torch-cuda-async-timing',
      topic: 'Performance',
      question: 'Why can ordinary wall-clock timing underreport CUDA operation time?',
      answer: 'CUDA launches are asynchronous with respect to the host, so the timer may stop before device work completes. Synchronize around the measured region or use CUDA events.',
    },
    {
      id: 'torch-allocated-reserved',
      topic: 'Performance',
      question: 'What is the difference between CUDA memory allocated and reserved?',
      answer: 'Allocated memory backs live tensors. Reserved memory is held by PyTorch’s caching allocator and includes allocated blocks plus reusable free blocks; it can remain high after tensors are deleted.',
    },
    {
      id: 'torch-empty-cache',
      topic: 'Performance',
      question: 'Does `torch.cuda.empty_cache()` free memory held by live tensors?',
      answer: 'No. It releases unused cached blocks for other applications to see, but live tensor storage remains allocated. Calling it every iteration can add synchronization and allocation overhead.',
    },
    {
      id: 'torch-item-sync',
      topic: 'Performance',
      question: 'Why can frequent `.item()` calls hurt accelerator throughput?',
      answer: 'Converting a device tensor to a Python scalar requires the host to observe the result, which can synchronize pending accelerator work and break overlap.',
    },
    {
      id: 'torch-optimizer-memory',
      topic: 'Performance',
      question: 'Why can optimizer state use more memory than model weights?',
      answer: 'Optimizers may keep one or more full-sized tensors per parameter, such as Adam’s first and second moments, often in higher precision. Gradients, activations, and temporary workspaces add further peaks.',
    },
  ],
};
