export interface AtomicTriviaSpec {
  sourceId: string;
  id: string;
  question: string;
  answer: string;
  acceptedAnswers?: string[];
  code?: string;
  codeQuestion?: string;
  codeAnswer?: string;
  codeAcceptedAnswers?: string[];
}

export const pytorchAtomicSpecs: AtomicTriviaSpec[] = [
  { sourceId: 'torch-tensor-metadata', id: 'torch-shape-metadata', question: 'What does `torch.zeros(2, 3, 4).shape` return?', answer: '`torch.Size([2, 3, 4])`', acceptedAnswers: ['[2, 3, 4]', '(2, 3, 4)', '2, 3, 4'] },
  { sourceId: 'torch-tensor-metadata', id: 'torch-stride-metadata', question: 'What strides does a contiguous tensor shaped `[2, 3, 4]` normally have?', answer: '`(12, 4, 1)`', acceptedAnswers: ['12, 4, 1', '[12, 4, 1]'] },
  { sourceId: 'torch-tensor-metadata', id: 'torch-offset-metadata', question: 'What is `torch.arange(10)[3:].storage_offset()`?', answer: '`3`', acceptedAnswers: ['three'] },
  {
    sourceId: 'torch-view-reshape',
    id: 'torch-view-contract',
    question: 'Why can reshaping a transposed tensor with `view(...)` raise an error?',
    answer: 'Its strides may be incompatible with the requested shape',
    acceptedAnswers: ['incompatible strides', 'non-contiguous layout', 'the layout is not view-compatible'],
    code: 'features = encoder(images)          # [B, C, H, W]\ntokens = features.flatten(2).transpose(1, 2)  # [B, HW, C]\ntokens = tokens.contiguous().view(batch, -1, channels)',
    codeQuestion: 'Why is `contiguous()` called before the final `view`?',
    codeAnswer: 'To materialize a dense, view-compatible layout',
    codeAcceptedAnswers: ['make the layout contiguous', 'compatible strides', 'make view safe'],
  },
  { sourceId: 'torch-view-reshape', id: 'torch-reshape-contract', question: 'What allocation risk does `reshape(...)` hide when the current strides cannot represent the requested shape?', answer: 'It may allocate and copy', acceptedAnswers: ['copy', 'it can make a copy', 'new storage'] },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-transpose-copy', question: 'Does `transpose` usually copy storage?', answer: 'No' },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-contiguous-copy', question: 'When can `x.contiguous()` allocate new storage?', answer: 'When `x` is not already contiguous', acceptedAnswers: ['non-contiguous', 'when the layout is non-contiguous', 'if x is noncontiguous'] },
  {
    sourceId: 'torch-clone-detach',
    id: 'torch-clone-storage',
    question: 'Does `y = x.clone()` share storage with `x`, and is `y` still connected to `x` in autograd?',
    answer: 'No shared storage; yes, still connected',
    acceptedAnswers: ['no and yes', 'independent storage with autograd history', 'copy but graph-connected'],
    code: 'target = online_output.detach().clone()  # independent teacher target\nloss = criterion(prediction, target)',
    codeQuestion: 'Does `target` share storage with `online_output`?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-clone-detach', id: 'torch-detach-graph', question: 'Does `y = x.detach()` share storage with `x`, and does `y` retain `x`\'s autograd history?', answer: 'Shared storage; no autograd history', acceptedAnswers: ['yes and no', 'shares storage but detached from graph'] },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-direction', question: 'What output shape results from adding tensors shaped `[8, 1, 32]` and `[5, 32]`?', answer: '`[8, 5, 32]`', acceptedAnswers: ['8, 5, 32', '(8, 5, 32)'] },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-size', question: 'Why does adding tensors shaped `[2, 3]` and `[2, 4]` fail?', answer: 'The trailing sizes `3` and `4` differ and neither is `1`', acceptedAnswers: ['3 and 4 are incompatible', 'neither trailing dimension is 1', 'broadcast mismatch'] },
  {
    sourceId: 'torch-cat-stack',
    id: 'torch-cat-rank',
    question: 'What shape does `torch.cat` produce from two tensors shaped `[4, 16]` along `dim=0`?',
    answer: '`[8, 16]`',
    acceptedAnswers: ['8, 16', '(8, 16)'],
    code: 'all_logits = torch.cat(batch_logits, dim=0)  # [sum(B_i), C]',
    codeQuestion: 'Does `all_logits` keep rank two?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-cat-stack', id: 'torch-stack-rank', question: 'What shape does `torch.stack` produce from two tensors shaped `[4, 16]` along a new leading axis?', answer: '`[2, 4, 16]`', acceptedAnswers: ['2, 4, 16', '(2, 4, 16)'] },
  { sourceId: 'torch-indexing-copy', id: 'torch-basic-indexing', question: 'Can an in-place change to `row` usually change `matrix` after `row = matrix[0]`?', answer: 'Yes; basic indexing usually returns a view', acceptedAnswers: ['yes', 'yes, it is a view'] },
  { sourceId: 'torch-indexing-copy', id: 'torch-advanced-indexing', question: 'Can an in-place change to `selected` usually change `matrix` after `selected = matrix[mask]`?', answer: 'No; Boolean indexing returns a copy', acceptedAnswers: ['no', 'no, it is a copy'] },
  { sourceId: 'torch-inplace-promotion', id: 'torch-inplace-promotion', question: 'Why can an integer tensor reject `x.add_(0.5)` even when `x + 0.5` works?', answer: 'The in-place result cannot be stored safely in the existing integer dtype', acceptedAnswers: ['in-place cannot change dtype', 'float result cannot be cast into integer destination', 'dtype mismatch'] },
  { sourceId: 'torch-to-noop', id: 'torch-to-noop', question: 'Can `y = x.to(device=x.device, dtype=x.dtype)` make `y is x` true?', answer: 'Yes' },
  { sourceId: 'torch-empty', id: 'torch-empty', question: 'Can code safely read values from `torch.empty(4)` before writing them?', answer: 'No; its values are uninitialized', acceptedAnswers: ['no', 'uninitialized'] },
  { sourceId: 'torch-requires-grad-recording', id: 'torch-grad-recording', question: 'Will `y = x.square()` normally have a `grad_fn` when `x.requires_grad` is `True`?', answer: 'Yes' },
  { sourceId: 'torch-leaf-grad', id: 'torch-leaf-grad', question: 'Where does `loss.backward()` store optimizer-ready gradients by default?', answer: 'In `.grad` on leaf parameters', acceptedAnswers: ['leaf tensors', 'parameter .grad fields', 'leaves'] },
  {
    sourceId: 'torch-grad-accumulation',
    id: 'torch-grad-accumulation',
    question: 'Does `backward()` overwrite or accumulate gradients?',
    answer: 'Accumulate',
    acceptedAnswers: ['accumulates'],
    code: 'optimizer.zero_grad(set_to_none=True)\nfor microbatch in microbatches:\n    (loss_fn(model(microbatch)) / len(microbatches)).backward()\noptimizer.step()',
    codeQuestion: 'Does the division produce a summed or mean gradient?',
    codeAnswer: 'Mean',
  },
  { sourceId: 'torch-none-zero-grad', id: 'torch-none-grad', question: 'What is `unused_parameter.grad` after backward when that parameter had no path to the loss?', answer: '`None`' },
  { sourceId: 'torch-nonscalar-backward', id: 'torch-vjp', question: 'What product does a non-scalar `backward(v)` compute?', answer: 'Vector-Jacobian', acceptedAnswers: ['VJP'] },
  { sourceId: 'torch-no-grad-inference', id: 'torch-inference-mode', question: 'Which context fits a deployment forward pass whose outputs will never enter a later autograd graph?', answer: '`torch.inference_mode()`', acceptedAnswers: ['inference_mode', 'torch.inference_mode'] },
  { sourceId: 'torch-no-grad-inference', id: 'torch-no-grad', question: 'Which context should disable recording when its outputs may later participate in grad-enabled work?', answer: '`torch.no_grad()`', acceptedAnswers: ['no_grad', 'torch.no_grad'] },
  {
    sourceId: 'torch-eval-no-grad',
    id: 'torch-eval-no-grad',
    question: 'Does `model.eval()` disable gradient recording?',
    answer: 'No',
    code: 'model.eval()\nwith torch.inference_mode():\n    logits = model(batch.to(device, non_blocking=True))',
    codeQuestion: 'Is an autograd graph recorded here?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-inplace-autograd', id: 'torch-version-counter', question: 'What detects unsafe in-place autograd mutation?', answer: 'Version counter' },
  { sourceId: 'torch-retain-create-graph', id: 'torch-retain-graph', question: 'Which backward flag is needed when the same forward graph must be traversed again?', answer: '`retain_graph=True`', acceptedAnswers: ['retain_graph'] },
  { sourceId: 'torch-retain-create-graph', id: 'torch-create-graph', question: 'Which gradient flag is needed when computing a second derivative through the first derivative?', answer: '`create_graph=True`', acceptedAnswers: ['create_graph'] },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-autograd-grad', question: 'Which API returns a derivative for selected inputs without filling every leaf `.grad` field?', answer: '`torch.autograd.grad`', acceptedAnswers: ['autograd.grad'] },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-tensor-backward', question: 'Which API fits an optimizer loop that expects gradients accumulated in parameter `.grad` fields?', answer: '`loss.backward()`', acceptedAnswers: ['backward', 'Tensor.backward'] },
  { sourceId: 'torch-parameter-registration', id: 'torch-parameter-registration', question: 'Why will `self.weight = torch.randn(8, requires_grad=True)` not appear in `model.parameters()`?', answer: 'It is a plain tensor, not an `nn.Parameter`', acceptedAnswers: ['not registered', 'plain tensors are not parameters', 'must wrap it in nn.Parameter'] },
  {
    sourceId: 'torch-module-list',
    id: 'torch-module-list',
    question: 'Why should a module store a variable-depth block sequence in `nn.ModuleList` instead of a plain list?',
    answer: 'So PyTorch registers and discovers every block',
    acceptedAnswers: ['registration', 'so model.parameters finds them', 'register the submodules'],
    code: 'self.blocks = nn.ModuleList([Block(width) for _ in range(depth)])\n\ndef forward(self, x: torch.Tensor) -> torch.Tensor:\n    for block in self.blocks:\n        x = block(x)\n    return x',
    codeQuestion: 'Will `model.parameters()` discover every block?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-parameter-buffer', id: 'torch-parameter-state', question: 'Should a learned weight updated by the optimizer be registered as a parameter or a buffer?', answer: 'Parameter' },
  {
    sourceId: 'torch-parameter-buffer',
    id: 'torch-buffer-state',
    question: 'Should fixed class weights that move and save with a model be registered as a parameter or a buffer?',
    answer: 'Buffer',
    code: 'self.register_buffer("class_weights", weights, persistent=True)\nloss = F.cross_entropy(logits, target, weight=self.class_weights)',
    codeQuestion: 'Will an optimizer update `class_weights` by default?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-state-dict', id: 'torch-state-dict', question: 'Does `model.state_dict()` include registered parameters, persistent buffers, or arbitrary Python attributes?', answer: 'Parameters and persistent buffers, not arbitrary attributes', acceptedAnswers: ['parameters and buffers', 'registered parameters and persistent buffers only'] },
  {
    sourceId: 'torch-load-state-strict',
    id: 'torch-load-state-strict',
    question: 'What does `strict=True` do when checkpoint keys do not exactly match the model?',
    answer: 'It raises an error',
    acceptedAnswers: ['error', 'raises RuntimeError', 'loading fails'],
    code: 'missing, unexpected = model.load_state_dict(checkpoint["model"], strict=False)\nif missing or unexpected:\n    raise RuntimeError(f"checkpoint mismatch: {missing=}, {unexpected=}")',
    codeQuestion: 'What happens when checkpoint keys mismatch?',
    codeAnswer: 'Raise error',
    codeAcceptedAnswers: ['error'],
  },
  {
    sourceId: 'torch-forward-call',
    id: 'torch-forward-call',
    question: 'Why should training code call `model(x)` instead of `model.forward(x)`?',
    answer: '`model(x)` preserves `nn.Module.__call__` behavior such as hooks',
    acceptedAnswers: ['hooks', '__call__ wrapper', 'model(x) runs module hooks'],
    code: 'with torch.autocast(device_type=device.type, enabled=use_amp):\n    logits = model(inputs)  # preserves Module.__call__ behavior',
    codeQuestion: 'Which module wrapper executes before `forward`?',
    codeAnswer: '`__call__`',
  },
  { sourceId: 'torch-cross-entropy-logits', id: 'torch-cross-entropy-logits', question: 'Should `softmax` be applied before passing model outputs to `CrossEntropyLoss`?', answer: 'No; pass raw logits', acceptedAnswers: ['no', 'raw logits', 'do not apply softmax'] },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-dtype', question: 'What dtype must labels such as `[2, 0, 1]` use for class-index cross entropy?', answer: '`torch.long`', acceptedAnswers: ['long', 'int64'] },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-rank', question: 'What shape should class-index targets have when logits have shape `[32, 10]`?', answer: '`[32]`', acceptedAnswers: ['32', '(32,)'] },
  { sourceId: 'torch-bce-logits', id: 'torch-bce-logits', question: 'Why prefer `BCEWithLogitsLoss` to `sigmoid` followed by binary cross entropy?', answer: 'It combines both operations more numerically stably', acceptedAnswers: ['numerical stability', 'stable fused operation', 'it avoids unstable extreme probabilities'] },
  {
    sourceId: 'torch-training-order',
    id: 'torch-training-first-step',
    question: 'Why does a standard training iteration clear gradients before the new forward pass?',
    answer: 'Because backward accumulates into existing gradients',
    acceptedAnswers: ['gradients accumulate', 'to avoid stale gradient accumulation', 'backward adds to .grad'],
    code: 'optimizer.zero_grad(set_to_none=True)\nlogits = model(inputs)\nloss = criterion(logits, targets)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'Which call changes model parameters?',
    codeAnswer: '`optimizer.step`',
  },
  { sourceId: 'torch-training-order', id: 'torch-training-gradient-step', question: 'What does `loss.backward()` change before the optimizer step?', answer: 'It accumulates gradients in parameter `.grad` fields', acceptedAnswers: ['parameter gradients', '.grad', 'computes gradients'] },
  { sourceId: 'torch-training-order', id: 'torch-training-update-step', question: 'What does `optimizer.step()` change that `loss.backward()` does not?', answer: 'The parameter values', acceptedAnswers: ['parameters', 'model weights', 'weights'] },
  { sourceId: 'torch-amp', id: 'torch-autocast-job', question: 'What does `autocast` decide for eligible operations during mixed-precision execution?', answer: 'Their execution dtype', acceptedAnswers: ['operation dtypes', 'precision per operation', 'which ops use lower precision'] },
  { sourceId: 'torch-amp', id: 'torch-grad-scaler-job', question: 'Why scale an FP16 loss before backward?', answer: 'To keep small gradients from underflowing to zero', acceptedAnswers: ['prevent gradient underflow', 'protect small gradients', 'underflow'] },
  {
    sourceId: 'torch-clip-unscale',
    id: 'torch-clip-unscale',
    question: 'What should happen before scaled gradients are clipped?',
    answer: 'Unscale',
    code: 'scaler.scale(loss).backward()\nscaler.unscale_(optimizer)\ntorch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\nscaler.step(optimizer)\nscaler.update()',
    codeQuestion: 'Which operation immediately precedes clipping?',
    codeAnswer: '`unscale_`',
  },
  { sourceId: 'torch-gradient-accumulation-loss', id: 'torch-accumulation-loss', question: 'How should each microbatch loss be scaled so `K` backward passes match one mean-loss gradient?', answer: 'Divide each loss by `K`', acceptedAnswers: ['divide by K', 'loss / K', 'divide by accumulation steps'] },
  { sourceId: 'torch-checkpoint', id: 'torch-checkpoint-model', question: 'What model data must a checkpoint save to reproduce learned predictions?', answer: '`model.state_dict()`', acceptedAnswers: ['model state', 'model weights', 'state_dict'] },
  {
    sourceId: 'torch-checkpoint',
    id: 'torch-checkpoint-optimizer',
    question: 'Why is saving only model weights insufficient for an exact Adam training resume?',
    answer: 'Adam\'s moment tensors and step state would be lost',
    acceptedAnswers: ['optimizer state is missing', 'Adam moments are missing', 'moments and step counters'],
    code: 'torch.save({\n    "model": model.state_dict(),\n    "optimizer": optimizer.state_dict(),\n    "step": step,\n    "scaler": scaler.state_dict(),\n}, checkpoint_path)',
    codeQuestion: 'Which field preserves Adam moment tensors?',
    codeAnswer: '`optimizer`',
  },
  { sourceId: 'torch-dataset-kinds', id: 'torch-map-dataset', question: 'Which dataset style fits a finite image set that supports `dataset[index]` and `len(dataset)`?', answer: 'Map-style dataset', acceptedAnswers: ['map-style', 'Dataset'] },
  { sourceId: 'torch-dataset-kinds', id: 'torch-iterable-dataset', question: 'Which dataset style fits a stream whose next sample arrives without random indexing?', answer: '`IterableDataset`', acceptedAnswers: ['iterable-style', 'iterable dataset'] },
  { sourceId: 'torch-dataloader-workers', id: 'torch-dataloader-workers', question: 'What execution change occurs when `DataLoader` uses `num_workers > 0`?', answer: 'Sample loading runs in worker subprocesses', acceptedAnswers: ['subprocesses', 'multiprocessing workers', 'worker processes'] },
  {
    sourceId: 'torch-pin-memory',
    id: 'torch-pin-memory',
    question: 'Why can `pin_memory=True` speed CPU-to-CUDA batch transfer?',
    answer: 'It stages tensors in page-locked host memory',
    acceptedAnswers: ['pinned memory', 'page-locked memory', 'enables asynchronous transfer'],
    code: 'loader = DataLoader(dataset, batch_size=64, pin_memory=True, num_workers=8)\nfor images, target in loader:\n    images = images.to(device, non_blocking=True)',
    codeQuestion: 'Which transfer flag permits host-device overlap?',
    codeAnswer: '`non_blocking`',
  },
  { sourceId: 'torch-persistent-workers', id: 'torch-persistent-workers', question: 'What trade-off does `persistent_workers=True` make between epochs?', answer: 'Less worker startup time, but worker memory stays alive', acceptedAnswers: ['faster startup but retains resources', 'keeps workers and their memory alive', 'reuse workers at a memory cost'] },
  { sourceId: 'torch-worker-cuda-tensors', id: 'torch-worker-cuda-tensors', question: 'Where should CUDA transfer normally occur when a multiprocess DataLoader returns a batch?', answer: 'In the main training process', acceptedAnswers: ['main process', 'training process', 'not in loader workers'] },
  { sourceId: 'torch-reproducibility', id: 'torch-manual-seed', question: 'Why can two runs still differ after both call `torch.manual_seed(0)`?', answer: 'Other libraries, workers, kernels, or hardware may remain nondeterministic', acceptedAnswers: ['nondeterministic kernels', 'other random sources', 'a seed alone is insufficient'] },
  { sourceId: 'torch-ddp-data-parallel', id: 'torch-ddp', question: 'Why is one-process-per-GPU DDP usually preferred over `nn.DataParallel`?', answer: 'It synchronizes replicas efficiently without a single Python-thread bottleneck', acceptedAnswers: ['more efficient multi-process parallelism', 'one process per GPU', 'avoids DataParallel bottleneck'] },
  { sourceId: 'torch-ddp-inputs', id: 'torch-ddp-inputs', question: 'Which part of training must give each DDP rank its own input shard?', answer: 'The input pipeline', acceptedAnswers: ['the user', 'DistributedSampler', 'the program', 'data loader or sampler', 'training input pipeline'] },
  {
    sourceId: 'torch-distributed-sampler-epoch',
    id: 'torch-distributed-sampler-epoch',
    question: 'Why call `train_sampler.set_epoch(epoch)` before each distributed training epoch?',
    answer: 'To change the shuffle while keeping ranks coordinated',
    acceptedAnswers: ['new coordinated shuffle', 'change the shuffle seed each epoch', 'avoid the same order every epoch'],
    code: 'for epoch in range(start_epoch, epochs):\n    train_sampler.set_epoch(epoch)\n    train_one_epoch(model, loader, optimizer)',
    codeQuestion: 'How often is `set_epoch` called?',
    codeAnswer: 'Each epoch',
  },
  { sourceId: 'torch-ddp-unused', id: 'torch-ddp-unused', question: 'Which DDP option can diagnose parameters skipped by a conditional forward branch?', answer: '`find_unused_parameters=True`', acceptedAnswers: ['find_unused_parameters'] },
  { sourceId: 'torch-fsdp', id: 'torch-fsdp', question: 'How does FSDP reduce the per-rank memory cost compared with replicated DDP?', answer: 'It shards parameters, gradients, and optimizer state across ranks', acceptedAnswers: ['sharding', 'fully shards model and optimizer state', 'partitions parameters gradients and optimizer state'] },
  {
    sourceId: 'torch-compile',
    id: 'torch-compile',
    question: 'What does `torch.compile(model)` try to optimize?',
    answer: 'Captured forward and backward execution regions',
    acceptedAnswers: ['PyTorch graphs', 'execution graphs', 'model execution regions'],
    code: 'model = torch.compile(model, dynamic=False)\n# Keep input shapes stable to reduce recompilation.',
    codeQuestion: 'What shape policy reduces recompilation here?',
    codeAnswer: 'Stable shapes',
  },
  {
    sourceId: 'torch-cuda-async-timing',
    id: 'torch-cuda-async-timing',
    question: 'Why are CUDA events more reliable than an unsynchronized CPU timer for kernel latency?',
    answer: 'They measure positions in the asynchronous device stream',
    acceptedAnswers: ['CUDA is asynchronous', 'device stream timing', 'they record GPU work'],
    code: 'start = torch.cuda.Event(enable_timing=True)\nend = torch.cuda.Event(enable_timing=True)\nstart.record(); output = model(batch); end.record()\ntorch.cuda.synchronize()\nlatency_ms = start.elapsed_time(end)',
    codeQuestion: 'What unit does `elapsed_time` return?',
    codeAnswer: 'Milliseconds',
    codeAcceptedAnswers: ['ms'],
  },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-allocated', question: 'Which CUDA memory metric tracks storage currently owned by live tensors?', answer: 'Allocated memory', acceptedAnswers: ['allocated', 'memory_allocated'] },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-reserved', question: 'Why can PyTorch report high reserved CUDA memory after tensors are deleted?', answer: 'The caching allocator keeps freed blocks for reuse', acceptedAnswers: ['allocator cache', 'cached blocks remain reserved', 'reserved includes reusable free blocks'] },
  { sourceId: 'torch-empty-cache', id: 'torch-empty-cache', question: 'Does `empty_cache()` free live tensor storage?', answer: 'No' },
  { sourceId: 'torch-item-sync', id: 'torch-item-sync', question: 'What can frequent accelerator `.item()` calls cause?', answer: 'Synchronization', acceptedAnswers: ['sync'] },
  { sourceId: 'torch-optimizer-memory', id: 'torch-adam-state', question: 'Why can Adam state require roughly two extra parameter-sized tensors?', answer: 'It stores first- and second-moment estimates', acceptedAnswers: ['two moments', 'first and second moments', 'momentum and squared-gradient estimates'] },
  {
    sourceId: 'torch-activation-checkpoint',
    id: 'torch-activation-checkpoint',
    question: 'Why does activation checkpointing use less memory but make backward slower?',
    answer: 'It discards forward activations and recomputes them during backward',
    acceptedAnswers: ['recomputation', 'recomputes activations', 'trades compute for activation memory'],
    code: 'hidden = torch.utils.checkpoint.checkpoint(\n    block, hidden, use_reentrant=False\n)',
    codeQuestion: 'Which pass recomputes discarded activations?',
    codeAnswer: 'Backward',
  },
  { sourceId: 'torch-activation-checkpoint', id: 'torch-checkpoint-reentrant', question: 'What value should modern code pass explicitly for activation checkpointing’s `use_reentrant` option?', answer: '`False`', acceptedAnswers: ['use_reentrant=False', 'non-reentrant'] },
  {
    sourceId: 'torch-ddp-no-sync',
    id: 'torch-ddp-no-sync',
    question: 'How can DDP avoid an all-reduce after every gradient-accumulation microbatch?',
    answer: 'Wrap all but the final forward-backward pair in `no_sync()`',
    acceptedAnswers: ['no_sync', 'DDP.no_sync', 'defer sync until the last microbatch'],
    code: 'with ddp_model.no_sync():\n    for microbatch in microbatches[:-1]:\n        loss_fn(ddp_model(microbatch)).backward()\nloss_fn(ddp_model(microbatches[-1])).backward()',
    codeQuestion: 'Which microbatch triggers synchronization?',
    codeAnswer: 'Last',
  },
  {
    sourceId: 'torch-load-weights-only',
    id: 'torch-load-weights-only',
    question: 'How should a tensor-only checkpoint be loaded to restrict pickle deserialization?',
    answer: 'Use `torch.load(..., weights_only=True)`',
    acceptedAnswers: ['weights_only=True', 'weights_only'],
    code: 'checkpoint = torch.load(path, map_location="cpu", weights_only=True)\nmodel.load_state_dict(checkpoint["model"], strict=True)',
    codeQuestion: 'Where are storages first restored?',
    codeAnswer: 'CPU',
  },
  { sourceId: 'torch-load-map-location', id: 'torch-load-map-location', question: 'How can a CUDA-saved checkpoint be restored without immediately allocating its storages on a GPU?', answer: 'Load with `map_location="cpu"`', acceptedAnswers: ['map_location', 'map_location=cpu', 'load onto CPU'] },
  { sourceId: 'torch-anomaly-detection', id: 'torch-anomaly-detection', question: 'Why should autograd anomaly detection be disabled after a failing backward pass is diagnosed?', answer: 'Its traceback and error checks add substantial overhead', acceptedAnswers: ['slow', 'debugging overhead', 'expensive checks and synchronization'] },
  {
    sourceId: 'torch-zero-grad-none',
    id: 'torch-zero-grad-none',
    question: 'Why can `optimizer.zero_grad(set_to_none=True)` be cheaper than filling every gradient tensor with zeros?',
    answer: 'It avoids the zero-fill memory writes',
    acceptedAnswers: ['fewer memory writes', 'sets grads to None', 'avoids writing zeros'],
    code: 'optimizer.zero_grad(set_to_none=True)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'What does `.grad` remain for an unused parameter?',
    codeAnswer: '`None`',
  },
  {
    sourceId: 'torch-softmax-dim',
    id: 'torch-softmax-dim',
    question: 'Which dimension should softmax use for logits shaped `[B, C]`?',
    answer: '`1`',
    acceptedAnswers: ['dim=1'],
    code: 'probabilities = logits.softmax(dim=1)  # logits: [B, C]\nassert torch.allclose(probabilities.sum(dim=1), torch.ones(batch))',
    codeQuestion: 'Which dimension sums to one?',
    codeAnswer: '`1`',
    codeAcceptedAnswers: ['dim=1'],
  },
];
