export interface AtomicTriviaSpec {
  sourceId: string;
  id: string;
  question: string;
  answer: string;
  acceptedAnswers?: string[];
  code?: string;
  codeQuestion?: string;
  codeAnswer?: string;
  codeAcceptedAnswers?: string[];
}

export const pytorchAtomicSpecs: AtomicTriviaSpec[] = [
  { sourceId: 'torch-tensor-metadata', id: 'torch-shape-metadata', question: 'Which metadata gives tensor dimension lengths?', answer: 'Shape' },
  { sourceId: 'torch-tensor-metadata', id: 'torch-stride-metadata', question: 'Which metadata gives storage steps per axis?', answer: 'Strides' },
  { sourceId: 'torch-tensor-metadata', id: 'torch-offset-metadata', question: 'Which metadata locates the first logical element?', answer: 'Storage offset' },
  {
    sourceId: 'torch-view-reshape',
    id: 'torch-view-contract',
    question: 'Which shape operation requires compatible strides?',
    answer: '`view`',
    code: 'features = encoder(images)          # [B, C, H, W]\ntokens = features.flatten(2).transpose(1, 2)  # [B, HW, C]\ntokens = tokens.contiguous().view(batch, -1, channels)',
    codeQuestion: 'Which call makes the final `view` safe?',
    codeAnswer: '`contiguous`',
  },
  { sourceId: 'torch-view-reshape', id: 'torch-reshape-contract', question: 'Which shape operation may silently copy?', answer: '`reshape`' },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-transpose-copy', question: 'Does `transpose` usually copy storage?', answer: 'No' },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-contiguous-copy', question: 'Which method materializes a requested dense layout?', answer: '`contiguous`' },
  {
    sourceId: 'torch-clone-detach',
    id: 'torch-clone-storage',
    question: 'Which method copies storage but keeps autograd history?',
    answer: '`clone`',
    code: 'target = online_output.detach().clone()  # independent teacher target\nloss = criterion(prediction, target)',
    codeQuestion: 'Does `target` share storage with `online_output`?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-clone-detach', id: 'torch-detach-graph', question: 'Which method cuts the incoming autograd edge?', answer: '`detach`' },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-direction', question: 'Do broadcast dimensions align from the left or the right?', answer: 'Right' },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-size', question: 'What size permits an unequal dimension to broadcast?', answer: '`1`', acceptedAnswers: ['one'] },
  {
    sourceId: 'torch-cat-stack',
    id: 'torch-cat-rank',
    question: 'Which join operation preserves rank?',
    answer: '`torch.cat`',
    acceptedAnswers: ['cat'],
    code: 'all_logits = torch.cat(batch_logits, dim=0)  # [sum(B_i), C]',
    codeQuestion: 'Does `all_logits` keep rank two?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-cat-stack', id: 'torch-stack-rank', question: 'Which join operation inserts a new axis?', answer: '`torch.stack`', acceptedAnswers: ['stack'] },
  { sourceId: 'torch-indexing-copy', id: 'torch-basic-indexing', question: 'Does basic slicing usually return a view or a copy?', answer: 'View' },
  { sourceId: 'torch-indexing-copy', id: 'torch-advanced-indexing', question: 'Does Boolean-mask indexing usually return a view or a copy?', answer: 'Copy' },
  { sourceId: 'torch-inplace-promotion', id: 'torch-inplace-promotion', question: 'Can in-place ops freely change destination dtype?', answer: 'No' },
  { sourceId: 'torch-to-noop', id: 'torch-to-noop', question: 'Can a no-op `Tensor.to(...)` return the same tensor?', answer: 'Yes' },
  { sourceId: 'torch-empty', id: 'torch-empty', question: 'What initialization does `torch.empty` perform?', answer: 'None', acceptedAnswers: ['uninitialized'] },
  { sourceId: 'torch-requires-grad-recording', id: 'torch-grad-recording', question: 'Which input flag enables normal autograd recording?', answer: '`requires_grad`' },
  { sourceId: 'torch-leaf-grad', id: 'torch-leaf-grad', question: 'Which tensors populate `.grad` by default?', answer: 'Leaf tensors', acceptedAnswers: ['leaves'] },
  {
    sourceId: 'torch-grad-accumulation',
    id: 'torch-grad-accumulation',
    question: 'Does `backward()` overwrite or accumulate gradients?',
    answer: 'Accumulate',
    acceptedAnswers: ['accumulates'],
    code: 'optimizer.zero_grad(set_to_none=True)\nfor microbatch in microbatches:\n    (loss_fn(model(microbatch)) / len(microbatches)).backward()\noptimizer.step()',
    codeQuestion: 'Does the division produce a summed or mean gradient?',
    codeAnswer: 'Mean',
  },
  { sourceId: 'torch-none-zero-grad', id: 'torch-none-grad', question: 'What is `.grad` when no gradient path exists?', answer: '`None`' },
  { sourceId: 'torch-nonscalar-backward', id: 'torch-vjp', question: 'What product does a non-scalar `backward(v)` compute?', answer: 'Vector-Jacobian', acceptedAnswers: ['VJP'] },
  { sourceId: 'torch-no-grad-inference', id: 'torch-inference-mode', question: 'Which gradient context has the lowest overhead for evaluation?', answer: '`inference_mode`' },
  { sourceId: 'torch-no-grad-inference', id: 'torch-no-grad', question: 'Which gradient-disabled context allows outputs to re-enter later graphs?', answer: '`no_grad`' },
  {
    sourceId: 'torch-eval-no-grad',
    id: 'torch-eval-no-grad',
    question: 'Does `model.eval()` disable gradient recording?',
    answer: 'No',
    code: 'model.eval()\nwith torch.inference_mode():\n    logits = model(batch.to(device, non_blocking=True))',
    codeQuestion: 'Is an autograd graph recorded here?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-inplace-autograd', id: 'torch-version-counter', question: 'What detects unsafe in-place autograd mutation?', answer: 'Version counter' },
  { sourceId: 'torch-retain-create-graph', id: 'torch-retain-graph', question: 'Which flag keeps a graph for another traversal?', answer: '`retain_graph`' },
  { sourceId: 'torch-retain-create-graph', id: 'torch-create-graph', question: 'Which flag records derivative operations?', answer: '`create_graph`' },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-autograd-grad', question: 'Which API returns gradients for named inputs?', answer: '`autograd.grad`' },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-tensor-backward', question: 'Which API accumulates gradients into leaves?', answer: '`backward`' },
  { sourceId: 'torch-parameter-registration', id: 'torch-parameter-registration', question: 'Which wrapper registers trainable module state?', answer: '`nn.Parameter`' },
  {
    sourceId: 'torch-module-list',
    id: 'torch-module-list',
    question: 'Which registered container holds a variable number of submodules?',
    answer: '`nn.ModuleList`',
    acceptedAnswers: ['ModuleList'],
    code: 'self.blocks = nn.ModuleList([Block(width) for _ in range(depth)])\n\ndef forward(self, x: torch.Tensor) -> torch.Tensor:\n    for block in self.blocks:\n        x = block(x)\n    return x',
    codeQuestion: 'Will `model.parameters()` discover every block?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-parameter-buffer', id: 'torch-parameter-state', question: 'What type of registered model state is trainable?', answer: 'Parameter' },
  {
    sourceId: 'torch-parameter-buffer',
    id: 'torch-buffer-state',
    question: 'What type of registered model state is non-trainable?',
    answer: 'Buffer',
    code: 'self.register_buffer("class_weights", weights, persistent=True)\nloss = F.cross_entropy(logits, target, weight=self.class_weights)',
    codeQuestion: 'Will an optimizer update `class_weights` by default?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-state-dict', id: 'torch-state-dict', question: 'Where are parameters and persistent buffers stored?', answer: '`state_dict`' },
  {
    sourceId: 'torch-load-state-strict',
    id: 'torch-load-state-strict',
    question: 'Which load flag requires exact checkpoint keys?',
    answer: '`strict=True`',
    acceptedAnswers: ['strict'],
    code: 'missing, unexpected = model.load_state_dict(checkpoint["model"], strict=False)\nif missing or unexpected:\n    raise RuntimeError(f"checkpoint mismatch: {missing=}, {unexpected=}")',
    codeQuestion: 'What happens when checkpoint keys mismatch?',
    codeAnswer: 'Raise error',
    codeAcceptedAnswers: ['error'],
  },
  {
    sourceId: 'torch-forward-call',
    id: 'torch-forward-call',
    question: 'Should hooks run through `model(x)` or `model.forward(x)`?',
    answer: '`model(x)`',
    acceptedAnswers: ['model(x)'],
    code: 'with torch.autocast(device_type=device.type, enabled=use_amp):\n    logits = model(inputs)  # preserves Module.__call__ behavior',
    codeQuestion: 'Which module wrapper executes before `forward`?',
    codeAnswer: '`__call__`',
  },
  { sourceId: 'torch-cross-entropy-logits', id: 'torch-cross-entropy-logits', question: 'Does `CrossEntropyLoss` expect logits or probabilities?', answer: 'Logits' },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-dtype', question: 'What dtype should class-index targets use?', answer: '`torch.long`', acceptedAnswers: ['long', 'int64'] },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-rank', question: 'What shape should targets have for logits shaped `[N, C]`?', answer: '`[N]`', acceptedAnswers: ['N'] },
  { sourceId: 'torch-bce-logits', id: 'torch-bce-logits', question: 'Which loss provides stable binary classification from logits?', answer: '`BCEWithLogitsLoss`' },
  {
    sourceId: 'torch-training-order',
    id: 'torch-training-first-step',
    question: 'Which optimizer-loop operation should run first?',
    answer: '`zero_grad`',
    code: 'optimizer.zero_grad(set_to_none=True)\nlogits = model(inputs)\nloss = criterion(logits, targets)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'Which call changes model parameters?',
    codeAnswer: '`optimizer.step`',
  },
  { sourceId: 'torch-training-order', id: 'torch-training-gradient-step', question: 'Which call computes parameter gradients?', answer: '`backward`' },
  { sourceId: 'torch-training-order', id: 'torch-training-update-step', question: 'Which call updates parameters?', answer: '`optimizer.step`' },
  { sourceId: 'torch-amp', id: 'torch-autocast-job', question: 'Which AMP context selects operation dtypes?', answer: '`autocast`' },
  { sourceId: 'torch-amp', id: 'torch-grad-scaler-job', question: 'Which AMP helper protects FP16 gradients from underflow?', answer: '`GradScaler`' },
  {
    sourceId: 'torch-clip-unscale',
    id: 'torch-clip-unscale',
    question: 'What should happen before scaled gradients are clipped?',
    answer: 'Unscale',
    code: 'scaler.scale(loss).backward()\nscaler.unscale_(optimizer)\ntorch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\nscaler.step(optimizer)\nscaler.update()',
    codeQuestion: 'Which operation immediately precedes clipping?',
    codeAnswer: '`unscale_`',
  },
  { sourceId: 'torch-gradient-accumulation-loss', id: 'torch-accumulation-loss', question: 'What should each loss be divided by during K-step accumulation?', answer: '`K`', acceptedAnswers: ['steps'] },
  { sourceId: 'torch-checkpoint', id: 'torch-checkpoint-model', question: 'Which checkpoint field contains the learned weights?', answer: 'Model state' },
  {
    sourceId: 'torch-checkpoint',
    id: 'torch-checkpoint-optimizer',
    question: 'Which checkpoint field is needed to resume Adam moments?',
    answer: 'Optimizer state',
    code: 'torch.save({\n    "model": model.state_dict(),\n    "optimizer": optimizer.state_dict(),\n    "step": step,\n    "scaler": scaler.state_dict(),\n}, checkpoint_path)',
    codeQuestion: 'Which field preserves Adam moment tensors?',
    codeAnswer: '`optimizer`',
  },
  { sourceId: 'torch-dataset-kinds', id: 'torch-map-dataset', question: 'Which dataset style supports keyed indexing?', answer: 'Map-style' },
  { sourceId: 'torch-dataset-kinds', id: 'torch-iterable-dataset', question: 'Which dataset style supports a stream?', answer: '`IterableDataset`' },
  { sourceId: 'torch-dataloader-workers', id: 'torch-dataloader-workers', question: 'Where does a DataLoader load data when `num_workers > 0`?', answer: 'Subprocesses' },
  {
    sourceId: 'torch-pin-memory',
    id: 'torch-pin-memory',
    question: 'What type of host memory does `pin_memory=True` create?',
    answer: 'Page-locked',
    acceptedAnswers: ['pinned memory'],
    code: 'loader = DataLoader(dataset, batch_size=64, pin_memory=True, num_workers=8)\nfor images, target in loader:\n    images = images.to(device, non_blocking=True)',
    codeQuestion: 'Which transfer flag permits host-device overlap?',
    codeAnswer: '`non_blocking`',
  },
  { sourceId: 'torch-persistent-workers', id: 'torch-persistent-workers', question: 'Which flag keeps loader workers alive between epochs?', answer: '`persistent_workers`' },
  { sourceId: 'torch-worker-cuda-tensors', id: 'torch-worker-cuda-tensors', question: 'Should loader workers normally return CUDA tensors?', answer: 'No' },
  { sourceId: 'torch-reproducibility', id: 'torch-manual-seed', question: 'Does `manual_seed` guarantee universal reproducibility?', answer: 'No' },
  { sourceId: 'torch-ddp-data-parallel', id: 'torch-ddp', question: 'Which wrapper is preferred for multi-GPU data parallelism?', answer: 'DDP', acceptedAnswers: ['DistributedDataParallel'] },
  { sourceId: 'torch-ddp-inputs', id: 'torch-ddp-inputs', question: 'Does DDP split input batches automatically?', answer: 'No' },
  {
    sourceId: 'torch-distributed-sampler-epoch',
    id: 'torch-distributed-sampler-epoch',
    question: 'Which call changes each epoch’s coordinated shuffle?',
    answer: '`set_epoch`',
    code: 'for epoch in range(start_epoch, epochs):\n    train_sampler.set_epoch(epoch)\n    train_one_epoch(model, loader, optimizer)',
    codeQuestion: 'How often is `set_epoch` called?',
    codeAnswer: 'Each epoch',
  },
  { sourceId: 'torch-ddp-unused', id: 'torch-ddp-unused', question: 'Which DDP flag detects unused parameters?', answer: '`find_unused_parameters`' },
  { sourceId: 'torch-fsdp', id: 'torch-fsdp', question: 'Which strategy shards parameters, gradients, and optimizer state?', answer: 'FSDP' },
  {
    sourceId: 'torch-compile',
    id: 'torch-compile',
    question: 'Which API compiles PyTorch execution regions?',
    answer: '`torch.compile`',
    acceptedAnswers: ['compile'],
    code: 'model = torch.compile(model, dynamic=False)\n# Keep input shapes stable to reduce recompilation.',
    codeQuestion: 'What shape policy reduces recompilation here?',
    codeAnswer: 'Stable shapes',
  },
  {
    sourceId: 'torch-cuda-async-timing',
    id: 'torch-cuda-async-timing',
    question: 'Which primitive provides reliable CUDA kernel timing?',
    answer: 'CUDA events',
    code: 'start = torch.cuda.Event(enable_timing=True)\nend = torch.cuda.Event(enable_timing=True)\nstart.record(); output = model(batch); end.record()\ntorch.cuda.synchronize()\nlatency_ms = start.elapsed_time(end)',
    codeQuestion: 'What unit does `elapsed_time` return?',
    codeAnswer: 'Milliseconds',
    codeAcceptedAnswers: ['ms'],
  },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-allocated', question: 'What CUDA memory category backs live tensors?', answer: 'Allocated' },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-reserved', question: 'What CUDA memory category is held by the caching allocator?', answer: 'Reserved' },
  { sourceId: 'torch-empty-cache', id: 'torch-empty-cache', question: 'Does `empty_cache()` free live tensor storage?', answer: 'No' },
  { sourceId: 'torch-item-sync', id: 'torch-item-sync', question: 'What can frequent accelerator `.item()` calls cause?', answer: 'Synchronization', acceptedAnswers: ['sync'] },
  { sourceId: 'torch-optimizer-memory', id: 'torch-adam-state', question: 'How many moment tensors does Adam keep per parameter?', answer: 'Two' },
  {
    sourceId: 'torch-activation-checkpoint',
    id: 'torch-activation-checkpoint',
    question: 'What resource does activation checkpointing save by spending more compute?',
    answer: 'Memory',
    code: 'hidden = torch.utils.checkpoint.checkpoint(\n    block, hidden, use_reentrant=False\n)',
    codeQuestion: 'Which pass recomputes discarded activations?',
    codeAnswer: 'Backward',
  },
  { sourceId: 'torch-activation-checkpoint', id: 'torch-checkpoint-reentrant', question: 'Which checkpoint variant is recommended?', answer: 'Non-reentrant', acceptedAnswers: ['use_reentrant=False'] },
  {
    sourceId: 'torch-ddp-no-sync',
    id: 'torch-ddp-no-sync',
    question: 'Which DDP context defers gradient synchronization?',
    answer: '`no_sync`',
    code: 'with ddp_model.no_sync():\n    for microbatch in microbatches[:-1]:\n        loss_fn(ddp_model(microbatch)).backward()\nloss_fn(ddp_model(microbatches[-1])).backward()',
    codeQuestion: 'Which microbatch triggers synchronization?',
    codeAnswer: 'Last',
  },
  {
    sourceId: 'torch-load-weights-only',
    id: 'torch-load-weights-only',
    question: 'Which `torch.load` flag restricts tensor-checkpoint deserialization?',
    answer: '`weights_only`',
    code: 'checkpoint = torch.load(path, map_location="cpu", weights_only=True)\nmodel.load_state_dict(checkpoint["model"], strict=True)',
    codeQuestion: 'Where are storages first restored?',
    codeAnswer: 'CPU',
  },
  { sourceId: 'torch-load-map-location', id: 'torch-load-map-location', question: 'Which argument remaps checkpoint devices?', answer: '`map_location`' },
  { sourceId: 'torch-anomaly-detection', id: 'torch-anomaly-detection', question: 'Should autograd anomaly detection be used for production or debugging?', answer: 'Debugging' },
  {
    sourceId: 'torch-zero-grad-none',
    id: 'torch-zero-grad-none',
    question: 'Which value should low-write `zero_grad` assign to gradients?',
    answer: '`None`',
    code: 'optimizer.zero_grad(set_to_none=True)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'What does `.grad` remain for an unused parameter?',
    codeAnswer: '`None`',
  },
  {
    sourceId: 'torch-softmax-dim',
    id: 'torch-softmax-dim',
    question: 'Which dimension should softmax use for logits shaped `[B, C]`?',
    answer: '`1`',
    acceptedAnswers: ['dim=1'],
    code: 'probabilities = logits.softmax(dim=1)  # logits: [B, C]\nassert torch.allclose(probabilities.sum(dim=1), torch.ones(batch))',
    codeQuestion: 'Which dimension sums to one?',
    codeAnswer: '`1`',
    codeAcceptedAnswers: ['dim=1'],
  },
];
