export interface AtomicTriviaSpec {
  sourceId: string;
  id: string;
  question: string;
  answer: string;
  acceptedAnswers?: string[];
  code?: string;
  codeQuestion?: string;
  codeAnswer?: string;
  codeAcceptedAnswers?: string[];
  codeExplanation?: string;
}

export const pythonAtomicSpecs: AtomicTriviaSpec[] = [
  {
    sourceId: 'python-pass-by-assignment',
    id: 'python-argument-model',
    question: 'Python’s argument-passing model?',
    answer: 'Object sharing',
    acceptedAnswers: ['pass-by-assignment'],
    code: 'def tag(batch: list[str]) -> None:\n    batch.append("ready")  # caller sees this mutation\n\nitems: list[str] = []\ntag(items)\nassert items == ["ready"]',
    codeQuestion: 'After `tag(items)`, what is `len(items)`?',
    codeAnswer: '`1`',
    codeAcceptedAnswers: ['one'],
  },
  { sourceId: 'python-pass-by-assignment', id: 'python-argument-mutation', question: 'Can mutating an argument affect the caller?', answer: 'Yes' },
  { sourceId: 'python-pass-by-assignment', id: 'python-argument-rebinding', question: 'Can local rebinding replace the caller’s binding?', answer: 'No' },
  {
    sourceId: 'python-is-equality',
    id: 'python-is-operator',
    question: 'Which operator checks object identity?',
    answer: '`is`',
    code: 'cached = cache.get(key)\nif cached is None:\n    cached = build_value(key)',
    codeQuestion: 'Which cache-miss sentinel is tested?',
    codeAnswer: '`None`',
  },
  { sourceId: 'python-is-equality', id: 'python-equality-operator', question: 'Which operator checks value equality?', answer: '`==`', acceptedAnswers: ['equals'] },
  {
    sourceId: 'python-mutable-default',
    id: 'python-mutable-default',
    question: 'Safe sentinel for a mutable default?',
    answer: '`None`',
    acceptedAnswers: ['none'],
    code: 'def add(item: str, items: list[str] | None = None) -> list[str]:\n    if items is None:\n        items = []\n    items.append(item)\n    return items',
    codeQuestion: 'Does each omitted `items` argument get a fresh list?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'python-default-evaluation', id: 'python-default-evaluation', question: 'When are function defaults evaluated?', answer: 'Definition time', acceptedAnswers: ['def time'] },
  { sourceId: 'python-shallow-deep-copy', id: 'python-shallow-copy', question: 'Which copy preserves nested aliases?', answer: 'Shallow copy' },
  { sourceId: 'python-shallow-deep-copy', id: 'python-deep-copy', question: 'Which copy recursively duplicates nested state?', answer: 'Deep copy' },
  { sourceId: 'python-assignment-copy', id: 'python-assignment-copy', question: 'Does `b = a` copy the object?', answer: 'No' },
  { sourceId: 'python-tuple-mutability', id: 'python-tuple-deep-immutable', question: 'Is tuple immutability deep?', answer: 'No' },
  { sourceId: 'python-tuple-mutability', id: 'python-tuple-list-hashable', question: 'Is a tuple containing a list hashable?', answer: 'No' },
  { sourceId: 'python-truthiness', id: 'python-empty-list-truthiness', question: '`bool([])`?', answer: '`False`' },
  { sourceId: 'python-truthiness', id: 'python-string-false-truthiness', question: '`bool("False")`?', answer: '`True`' },
  { sourceId: 'python-truthiness', id: 'python-zero-truthiness', question: '`bool(0)`?', answer: '`False`' },
  { sourceId: 'python-truthiness', id: 'python-nan-truthiness', question: '`bool(float("nan"))`?', answer: '`True`' },
  {
    sourceId: 'python-sort-return',
    id: 'python-sort-return',
    question: 'What does `list.sort()` return?',
    answer: '`None`',
    code: 'records.sort(key=lambda row: row.created_at)  # mutate in place\nordered = sorted(records, key=lambda row: row.created_at)  # new list',
    codeQuestion: 'Which variable keeps the original list identity?',
    codeAnswer: '`records`',
  },
  { sourceId: 'python-sort-return', id: 'python-sorted-copy', question: 'Which built-in returns a new sorted list?', answer: '`sorted`' },
  { sourceId: 'python-identity-interning', id: 'python-identity-interning', question: 'For equal strings, use identity or equality?', answer: 'Equality', acceptedAnswers: ['=='] },
  { sourceId: 'python-iterable-iterator', id: 'python-iterable-method', question: 'Which function asks an iterable for an iterator?', answer: '`iter`' },
  { sourceId: 'python-iterable-iterator', id: 'python-iterator-method', question: 'Which method advances an iterator?', answer: '`__next__`', acceptedAnswers: ['next'] },
  { sourceId: 'python-generator-single-use', id: 'python-generator-single-use', question: 'After completion, a generator is…?', answer: 'Exhausted' },
  { sourceId: 'python-yield-return', id: 'python-yield-action', question: 'Which keyword suspends a function frame?', answer: '`yield`' },
  { sourceId: 'python-yield-return', id: 'python-return-action', question: 'Which keyword terminates a function?', answer: '`return`' },
  { sourceId: 'python-list-generator-comprehension', id: 'python-list-comprehension-mode', question: 'A list comprehension evaluates…?', answer: 'Eagerly', acceptedAnswers: ['eager'] },
  { sourceId: 'python-list-generator-comprehension', id: 'python-generator-expression-mode', question: 'A generator expression evaluates…?', answer: 'Lazily', acceptedAnswers: ['lazy'] },
  {
    sourceId: 'python-next-default',
    id: 'python-next-default',
    question: 'What does `next(it, fallback)` return at exhaustion?',
    answer: '`fallback`',
    code: 'record = next((row for row in rows if row.id == target_id), None)\nif record is None:\n    raise LookupError(target_id)',
    codeQuestion: 'If no row matches, what is assigned to `record`?',
    codeAnswer: '`None`',
  },
  { sourceId: 'python-yield-from', id: 'python-yield-from', question: 'Which construct delegates to a subiterator?', answer: '`yield from`' },
  { sourceId: 'python-legb', id: 'python-legb', question: 'Local, Enclosing, Global, Built-in?', answer: 'LEGB' },
  {
    sourceId: 'python-late-binding',
    id: 'python-late-binding',
    question: 'Loop-created closures exhibit what binding?',
    answer: 'Late binding',
    code: 'handlers = [lambda event, i=i: route(i, event) for i in range(4)]',
    codeQuestion: 'What index does `handlers[0]` capture?',
    codeAnswer: '`0`',
    codeAcceptedAnswers: ['zero'],
  },
  { sourceId: 'python-global-nonlocal', id: 'python-global-binding', question: 'Which keyword targets module scope?', answer: '`global`' },
  { sourceId: 'python-global-nonlocal', id: 'python-nonlocal-binding', question: 'Which keyword targets enclosing function scope?', answer: '`nonlocal`' },
  { sourceId: 'python-loop-scope', id: 'python-loop-scope', question: 'Do `for` loops create block scope?', answer: 'No' },
  { sourceId: 'python-loop-scope', id: 'python-comprehension-scope', question: 'Do Python 3 comprehensions have their own scope?', answer: 'Yes' },
  {
    sourceId: 'python-signature-markers',
    id: 'python-positional-only-marker',
    question: 'Positional-only parameter marker?',
    answer: '`/`',
    code: 'def read_blob(path: str, /, *, timeout_s: float = 5.0) -> bytes:\n    ...',
    codeQuestion: 'How must `timeout_s` be supplied?',
    codeAnswer: 'By keyword',
    codeAcceptedAnswers: ['keyword'],
  },
  { sourceId: 'python-signature-markers', id: 'python-keyword-only-marker', question: 'Keyword-only parameter marker?', answer: '`*`' },
  { sourceId: 'python-args-kwargs', id: 'python-args-type', question: 'Runtime type of `args`?', answer: '`tuple`' },
  { sourceId: 'python-args-kwargs', id: 'python-kwargs-type', question: 'Runtime type of `kwargs`?', answer: '`dict`' },
  { sourceId: 'python-decorator-timing', id: 'python-decorator-timing', question: 'When is a decorator applied?', answer: 'Definition time', acceptedAnswers: ['def time'] },
  {
    sourceId: 'python-decorator-timing',
    id: 'python-wraps-purpose',
    question: 'Which helper preserves wrapped-function metadata?',
    answer: '`functools.wraps`',
    acceptedAnswers: ['wraps'],
    code: 'from functools import wraps\n\ndef traced(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs)\n    return wrapper',
    codeQuestion: 'Which helper preserves the original function name?',
    codeAnswer: '`wraps`',
  },
  { sourceId: 'python-hashability', id: 'python-hashability', question: 'Required dictionary-key property?', answer: 'Hashable' },
  {
    sourceId: 'python-dict-complexity',
    id: 'python-dict-complexity',
    question: 'Average dictionary lookup complexity?',
    answer: '`O(1)`',
    acceptedAnswers: ['constant time'],
    code: 'users_by_id: dict[str, User] = {user.id: user for user in users}\nowner = users_by_id[event.user_id]',
    codeQuestion: 'Average complexity of the owner lookup?',
    codeAnswer: '`O(1)`',
    codeAcceptedAnswers: ['constant time'],
  },
  { sourceId: 'python-dict-order', id: 'python-dict-order', question: 'Modern dictionaries preserve which order?', answer: 'Insertion order' },
  { sourceId: 'python-list-append', id: 'python-list-append', question: 'Amortized complexity of `list.append`?', answer: '`O(1)`', acceptedAnswers: ['constant time'] },
  {
    sourceId: 'python-deque',
    id: 'python-deque',
    question: 'Best built-in queue for both ends?',
    answer: '`deque`',
    code: 'from collections import deque\n\npending: deque[Job] = deque()\npending.append(job)\nnext_job = pending.popleft()',
    codeQuestion: 'Amortized complexity of `popleft()`?',
    codeAnswer: '`O(1)`',
    codeAcceptedAnswers: ['constant time'],
  },
  { sourceId: 'python-set-frozenset', id: 'python-set-mutability', question: 'Which unique-element collection is mutable?', answer: '`set`' },
  { sourceId: 'python-set-frozenset', id: 'python-frozenset-hashable', question: 'Which unique-element collection can be hashable?', answer: '`frozenset`' },
  { sourceId: 'python-class-instance-attributes', id: 'python-class-attribute-sharing', question: 'Mutable class attributes create what state?', answer: 'Shared state' },
  {
    sourceId: 'python-class-instance-attributes',
    id: 'python-instance-attribute',
    question: 'What does assigning `self.name` create?',
    answer: 'Instance attribute',
    code: 'class Worker:\n    def __init__(self, queue: str) -> None:\n        self.queue = queue  # per-instance state',
    codeQuestion: 'Is `queue` class or instance state?',
    codeAnswer: 'Instance state',
  },
  { sourceId: 'python-method-kinds', id: 'python-self-method', question: 'Which method kind receives `self`?', answer: 'Instance method' },
  {
    sourceId: 'python-method-kinds',
    id: 'python-cls-method',
    question: 'Which method kind receives `cls`?',
    answer: 'Class method',
    code: 'class Config:\n    @classmethod\n    def from_env(cls) -> "Config":\n        return cls(timeout_s=float(os.environ["TIMEOUT_S"]))',
    codeQuestion: 'What constructor pattern does `from_env` implement?',
    codeAnswer: 'Alternative constructor',
  },
  { sourceId: 'python-method-kinds', id: 'python-static-method', question: 'Which method kind receives neither `self` nor `cls`?', answer: 'Static method' },
  { sourceId: 'python-super-mro', id: 'python-super-mro', question: 'What ordering does zero-argument `super()` follow?', answer: 'MRO', acceptedAnswers: ['method resolution order'] },
  { sourceId: 'python-new-init', id: 'python-new-role', question: 'Which special method creates an instance?', answer: '`__new__`' },
  { sourceId: 'python-new-init', id: 'python-init-role', question: 'Which special method initializes an instance?', answer: '`__init__`' },
  { sourceId: 'python-slots', id: 'python-slots', question: 'Which declaration can remove per-instance `__dict__`?', answer: '`__slots__`' },
  { sourceId: 'python-descriptor', id: 'python-descriptor', question: 'Protocol behind `property` and bound methods?', answer: 'Descriptor protocol', acceptedAnswers: ['descriptor'] },
  { sourceId: 'python-eq-hash', id: 'python-eq-hash', question: 'Defining value `__eq__` usually makes instances…?', answer: 'Unhashable' },
  { sourceId: 'python-not-implemented', id: 'python-not-implemented-value', question: 'Binary special method cannot handle the other type: return?', answer: '`NotImplemented`' },
  { sourceId: 'python-not-implemented', id: 'python-not-implemented-error', question: 'Abstract API method has no implementation: raise?', answer: '`NotImplementedError`' },
  { sourceId: 'python-bare-except', id: 'python-bare-except', question: 'A bare `except:` catches which root class?', answer: '`BaseException`' },
  {
    sourceId: 'python-exception-chaining',
    id: 'python-exception-chaining',
    question: 'Which syntax preserves an explicit exception cause?',
    answer: '`raise from`',
    code: 'try:\n    payload = json.loads(raw)\nexcept json.JSONDecodeError as exc:\n    raise ConfigError("invalid JSON") from exc',
    codeQuestion: 'What exception attribute records `exc`?',
    codeAnswer: '`__cause__`',
  },
  { sourceId: 'python-exception-chaining', id: 'python-suppress-context', question: 'Which suffix suppresses displayed exception context?', answer: '`from None`' },
  {
    sourceId: 'python-context-manager',
    id: 'python-context-manager',
    question: 'Can truthy `__exit__` suppress an exception?',
    answer: 'Yes',
    code: 'with transaction() as tx:\n    tx.write(records)\n# __exit__ commits or rolls back at the boundary',
    codeQuestion: 'Which method owns the cleanup boundary?',
    codeAnswer: '`__exit__`',
  },
  { sourceId: 'python-finally', id: 'python-finally', question: 'Does `finally` normally run before a pending return?', answer: 'Yes' },
  { sourceId: 'python-eafp-lbyl', id: 'python-eafp', question: 'Try first, handle expected failure?', answer: 'EAFP' },
  { sourceId: 'python-eafp-lbyl', id: 'python-lbyl', question: 'Check conditions before acting?', answer: 'LBYL' },
  { sourceId: 'python-gil', id: 'python-gil', question: 'Traditional CPython bytecode lock?', answer: 'GIL' },
  { sourceId: 'python-concurrency-models', id: 'python-threads-use', question: 'Blocking I/O with shared memory?', answer: 'Threads' },
  { sourceId: 'python-concurrency-models', id: 'python-processes-use', question: 'CPU parallelism with isolation?', answer: 'Processes' },
  { sourceId: 'python-concurrency-models', id: 'python-asyncio-use', question: 'Many cooperative I/O tasks?', answer: '`asyncio`' },
  {
    sourceId: 'python-blocking-async',
    id: 'python-blocking-async',
    question: 'Blocking code stalls which async component?',
    answer: 'Event loop',
    code: 'async def fetch_profile(user_id: str) -> Profile:\n    return await asyncio.to_thread(blocking_client.fetch, user_id)',
    codeQuestion: 'Where does `blocking_client.fetch` run?',
    codeAnswer: 'Worker thread',
    codeAcceptedAnswers: ['thread'],
  },
  { sourceId: 'python-race-gil', id: 'python-race-gil', question: 'Does the GIL eliminate logical races?', answer: 'No' },
  { sourceId: 'python-memory-management', id: 'python-reference-counting', question: 'CPython’s primary lifetime mechanism?', answer: 'Reference counting' },
  { sourceId: 'python-memory-management', id: 'python-cycle-collector', question: 'What reclaims unreachable reference cycles?', answer: 'Cycle collector', acceptedAnswers: ['cyclic gc'] },
  { sourceId: 'python-import-cache', id: 'python-import-cache', question: 'Where are imported module objects cached?', answer: '`sys.modules`' },
  { sourceId: 'python-any-object', id: 'python-any-checking', question: 'Which type disables most static checking?', answer: '`Any`' },
  { sourceId: 'python-any-object', id: 'python-object-checking', question: 'Which top type requires narrowing before specific operations?', answer: '`object`' },
  {
    sourceId: 'python-protocol',
    id: 'python-protocol',
    question: 'A typing `Protocol` enables what subtyping?',
    answer: 'Structural subtyping',
    code: 'class Encoder(Protocol):\n    def encode(self, text: str) -> list[int]: ...\n\ndef batch_encode(encoder: Encoder, texts: list[str]) -> list[list[int]]:\n    return [encoder.encode(text) for text in texts]',
    codeQuestion: 'Which method must an `Encoder` provide?',
    codeAnswer: '`encode`',
  },
  { sourceId: 'python-stdlib-dataclass', id: 'python-dataclass-generated', question: 'Which decorator generates container methods?', answer: '`@dataclass`', acceptedAnswers: ['dataclass'] },
  { sourceId: 'python-stdlib-dataclass', id: 'python-dataclass-validation', question: 'Do standard dataclasses validate annotations?', answer: 'No' },
  {
    sourceId: 'python-dataclass-default-factory',
    id: 'python-dataclass-default-factory',
    question: 'Safe mutable dataclass default helper?',
    answer: '`default_factory`',
    code: 'from dataclasses import dataclass, field\n\n@dataclass\nclass Batch:\n    values: list[int] = field(default_factory=list)',
    codeQuestion: 'Do two `Batch` instances share `values`?',
    codeAnswer: 'No',
  },
  {
    sourceId: 'python-pydantic-dataclass',
    id: 'python-pydantic-validation',
    question: 'Which dataclass flavor validates constructor input?',
    answer: 'Pydantic dataclass',
    code: 'from pydantic.dataclasses import dataclass\n\n@dataclass\nclass Request:\n    timeout_s: float\n\nrequest = Request(timeout_s="2.5")  # coerced in lax mode',
    codeQuestion: 'Runtime type of `request.timeout_s`?',
    codeAnswer: '`float`',
  },
  { sourceId: 'python-pydantic-dataclass', id: 'python-stdlib-validation', question: 'Which dataclass flavor skips runtime validation?', answer: 'Standard dataclass' },
  {
    sourceId: 'python-pydantic-strict',
    id: 'python-pydantic-strict',
    question: 'Is Pydantic strict by default?',
    answer: 'No',
    code: 'from pydantic import ConfigDict\nfrom pydantic.dataclasses import dataclass\n\n@dataclass(config=ConfigDict(strict=True))\nclass Job:\n    retries: int',
    codeQuestion: 'Will `Job(retries="3")` be accepted?',
    codeAnswer: 'No',
  },
  { sourceId: 'python-pydantic-model-vs-dataclass', id: 'python-pydantic-primary-api', question: 'Pydantic’s primary model API?', answer: '`BaseModel`' },
  { sourceId: 'python-frozen-dataclass', id: 'python-frozen-depth', question: 'Is `frozen=True` deep immutability?', answer: 'No' },
  { sourceId: 'python-frozen-dataclass', id: 'python-frozen-effect', question: 'What does `frozen=True` block?', answer: 'Field reassignment' },
  {
    sourceId: 'python-task-group',
    id: 'python-task-group',
    question: 'Structured-concurrency API for related async tasks?',
    answer: '`TaskGroup`',
    code: 'async with asyncio.TaskGroup() as group:\n    profile = group.create_task(fetch_profile(user_id))\n    orders = group.create_task(fetch_orders(user_id))',
    codeQuestion: 'When does the context exit?',
    codeAnswer: 'All complete',
  },
  { sourceId: 'python-task-group', id: 'python-task-group-failure', question: 'One `TaskGroup` child fails; siblings are…?', answer: 'Cancelled' },
  { sourceId: 'python-cancelled-error', id: 'python-cancelled-error-base', question: '`asyncio.CancelledError` inherits from…?', answer: '`BaseException`' },
  {
    sourceId: 'python-cancelled-error',
    id: 'python-cancelled-error-action',
    question: 'After cancellation cleanup, normally…?',
    answer: 'Re-raise',
    acceptedAnswers: ['reraise'],
    code: 'try:\n    await consume(queue)\nexcept asyncio.CancelledError:\n    await flush_metrics()\n    raise',
    codeQuestion: 'Which statement preserves cancellation?',
    codeAnswer: '`raise`',
  },
  {
    sourceId: 'python-contextvar',
    id: 'python-contextvar',
    question: 'Async-safe request-local state primitive?',
    answer: '`ContextVar`',
    code: 'request_id: ContextVar[str] = ContextVar("request_id")\n\nasync def handle(req: Request) -> Response:\n    token = request_id.set(req.id)\n    try:\n        return await dispatch(req)\n    finally:\n        request_id.reset(token)',
    codeQuestion: 'Which object restores the previous value?',
    codeAnswer: '`token`',
  },
  { sourceId: 'python-lru-cache-hashable', id: 'python-lru-cache-hashable', question: '`lru_cache` arguments must be…?', answer: 'Hashable' },
  { sourceId: 'python-exception-group', id: 'python-exception-group', question: 'Syntax for matching an `ExceptionGroup` subgroup?', answer: '`except*`' },
];

export const pytorchAtomicSpecs: AtomicTriviaSpec[] = [
  { sourceId: 'torch-tensor-metadata', id: 'torch-shape-metadata', question: 'Which metadata gives tensor dimension lengths?', answer: 'Shape' },
  { sourceId: 'torch-tensor-metadata', id: 'torch-stride-metadata', question: 'Which metadata gives storage steps per axis?', answer: 'Strides' },
  { sourceId: 'torch-tensor-metadata', id: 'torch-offset-metadata', question: 'Which metadata locates the first logical element?', answer: 'Storage offset' },
  {
    sourceId: 'torch-view-reshape',
    id: 'torch-view-contract',
    question: 'Which shape operation requires compatible strides?',
    answer: '`view`',
    code: 'features = encoder(images)          # [B, C, H, W]\ntokens = features.flatten(2).transpose(1, 2)  # [B, HW, C]\ntokens = tokens.contiguous().view(batch, -1, channels)',
    codeQuestion: 'Which call makes the final `view` safe?',
    codeAnswer: '`contiguous`',
  },
  { sourceId: 'torch-view-reshape', id: 'torch-reshape-contract', question: 'Which shape operation may silently copy?', answer: '`reshape`' },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-transpose-copy', question: 'Does `transpose` usually copy storage?', answer: 'No' },
  { sourceId: 'torch-transpose-contiguous', id: 'torch-contiguous-copy', question: 'Which method materializes a requested dense layout?', answer: '`contiguous`' },
  {
    sourceId: 'torch-clone-detach',
    id: 'torch-clone-storage',
    question: 'Which method copies storage but keeps autograd history?',
    answer: '`clone`',
    code: 'target = online_output.detach().clone()  # independent teacher target\nloss = criterion(prediction, target)',
    codeQuestion: 'Does `target` share storage with `online_output`?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-clone-detach', id: 'torch-detach-graph', question: 'Which method cuts the incoming autograd edge?', answer: '`detach`' },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-direction', question: 'Broadcast dimensions align from which side?', answer: 'Right' },
  { sourceId: 'torch-broadcasting', id: 'torch-broadcast-size', question: 'Compatible unequal broadcast dimension size?', answer: '`1`', acceptedAnswers: ['one'] },
  {
    sourceId: 'torch-cat-stack',
    id: 'torch-cat-rank',
    question: 'Which join operation preserves rank?',
    answer: '`torch.cat`',
    acceptedAnswers: ['cat'],
    code: 'all_logits = torch.cat(batch_logits, dim=0)  # [sum(B_i), C]',
    codeQuestion: 'Does `all_logits` keep rank two?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-cat-stack', id: 'torch-stack-rank', question: 'Which join operation inserts a new axis?', answer: '`torch.stack`', acceptedAnswers: ['stack'] },
  { sourceId: 'torch-indexing-copy', id: 'torch-basic-indexing', question: 'Slices usually return a view or copy?', answer: 'View' },
  { sourceId: 'torch-indexing-copy', id: 'torch-advanced-indexing', question: 'Boolean-mask indexing usually returns a view or copy?', answer: 'Copy' },
  { sourceId: 'torch-inplace-promotion', id: 'torch-inplace-promotion', question: 'Can in-place ops freely change destination dtype?', answer: 'No' },
  { sourceId: 'torch-to-noop', id: 'torch-to-noop', question: 'Can a no-op `Tensor.to(...)` return the same tensor?', answer: 'Yes' },
  { sourceId: 'torch-empty', id: 'torch-empty', question: 'What initialization does `torch.empty` perform?', answer: 'None', acceptedAnswers: ['uninitialized'] },
  { sourceId: 'torch-requires-grad-recording', id: 'torch-grad-recording', question: 'Input flag that enables normal autograd recording?', answer: '`requires_grad`' },
  { sourceId: 'torch-leaf-grad', id: 'torch-leaf-grad', question: 'Which tensors populate `.grad` by default?', answer: 'Leaf tensors', acceptedAnswers: ['leaves'] },
  {
    sourceId: 'torch-grad-accumulation',
    id: 'torch-grad-accumulation',
    question: 'Does `backward()` overwrite or accumulate gradients?',
    answer: 'Accumulate',
    acceptedAnswers: ['accumulates'],
    code: 'optimizer.zero_grad(set_to_none=True)\nfor microbatch in microbatches:\n    (loss_fn(model(microbatch)) / len(microbatches)).backward()\noptimizer.step()',
    codeQuestion: 'Does the division produce a summed or mean gradient?',
    codeAnswer: 'Mean',
  },
  { sourceId: 'torch-none-zero-grad', id: 'torch-none-grad', question: 'No gradient path produces `.grad` equal to…?', answer: '`None`' },
  { sourceId: 'torch-nonscalar-backward', id: 'torch-vjp', question: 'A non-scalar `backward(v)` computes what product?', answer: 'Vector-Jacobian', acceptedAnswers: ['VJP'] },
  { sourceId: 'torch-no-grad-inference', id: 'torch-inference-mode', question: 'Lowest-overhead evaluation grad context?', answer: '`inference_mode`' },
  { sourceId: 'torch-no-grad-inference', id: 'torch-no-grad', question: 'Grad-disabled context whose outputs can re-enter later graphs?', answer: '`no_grad`' },
  {
    sourceId: 'torch-eval-no-grad',
    id: 'torch-eval-no-grad',
    question: 'Does `model.eval()` disable gradient recording?',
    answer: 'No',
    code: 'model.eval()\nwith torch.inference_mode():\n    logits = model(batch.to(device, non_blocking=True))',
    codeQuestion: 'Is an autograd graph recorded here?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-inplace-autograd', id: 'torch-version-counter', question: 'What detects unsafe in-place autograd mutation?', answer: 'Version counter' },
  { sourceId: 'torch-retain-create-graph', id: 'torch-retain-graph', question: 'Which flag keeps a graph for another traversal?', answer: '`retain_graph`' },
  { sourceId: 'torch-retain-create-graph', id: 'torch-create-graph', question: 'Which flag records derivative operations?', answer: '`create_graph`' },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-autograd-grad', question: 'Which API returns gradients for named inputs?', answer: '`autograd.grad`' },
  { sourceId: 'torch-grad-vs-backward', id: 'torch-tensor-backward', question: 'Which API accumulates gradients into leaves?', answer: '`backward`' },
  { sourceId: 'torch-parameter-registration', id: 'torch-parameter-registration', question: 'Which wrapper registers trainable module state?', answer: '`nn.Parameter`' },
  {
    sourceId: 'torch-module-list',
    id: 'torch-module-list',
    question: 'Registered container for a variable number of submodules?',
    answer: '`nn.ModuleList`',
    acceptedAnswers: ['ModuleList'],
    code: 'self.blocks = nn.ModuleList([Block(width) for _ in range(depth)])\n\ndef forward(self, x: torch.Tensor) -> torch.Tensor:\n    for block in self.blocks:\n        x = block(x)\n    return x',
    codeQuestion: 'Will `model.parameters()` discover every block?',
    codeAnswer: 'Yes',
  },
  { sourceId: 'torch-parameter-buffer', id: 'torch-parameter-state', question: 'Trainable registered model state?', answer: 'Parameter' },
  {
    sourceId: 'torch-parameter-buffer',
    id: 'torch-buffer-state',
    question: 'Non-trainable registered model state?',
    answer: 'Buffer',
    code: 'self.register_buffer("class_weights", weights, persistent=True)\nloss = F.cross_entropy(logits, target, weight=self.class_weights)',
    codeQuestion: 'Will an optimizer update `class_weights` by default?',
    codeAnswer: 'No',
  },
  { sourceId: 'torch-state-dict', id: 'torch-state-dict', question: 'Parameters plus persistent buffers are stored in…?', answer: '`state_dict`' },
  {
    sourceId: 'torch-load-state-strict',
    id: 'torch-load-state-strict',
    question: 'Which load flag requires exact checkpoint keys?',
    answer: '`strict=True`',
    acceptedAnswers: ['strict'],
    code: 'missing, unexpected = model.load_state_dict(checkpoint["model"], strict=False)\nif missing or unexpected:\n    raise RuntimeError(f"checkpoint mismatch: {missing=}, {unexpected=}")',
    codeQuestion: 'What happens when checkpoint keys mismatch?',
    codeAnswer: 'Raise error',
    codeAcceptedAnswers: ['error'],
  },
  {
    sourceId: 'torch-forward-call',
    id: 'torch-forward-call',
    question: 'Hooks run through `model(x)` or `model.forward(x)`?',
    answer: '`model(x)`',
    acceptedAnswers: ['model(x)'],
    code: 'with torch.autocast(device_type=device.type, enabled=use_amp):\n    logits = model(inputs)  # preserves Module.__call__ behavior',
    codeQuestion: 'Which module wrapper executes before `forward`?',
    codeAnswer: '`__call__`',
  },
  { sourceId: 'torch-cross-entropy-logits', id: 'torch-cross-entropy-logits', question: '`CrossEntropyLoss` expects logits or probabilities?', answer: 'Logits' },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-dtype', question: 'Class-index target dtype?', answer: '`torch.long`', acceptedAnswers: ['long', 'int64'] },
  { sourceId: 'torch-cross-entropy-target', id: 'torch-cross-entropy-target-rank', question: 'For logits `[N, C]`, target shape?', answer: '`[N]`', acceptedAnswers: ['N'] },
  { sourceId: 'torch-bce-logits', id: 'torch-bce-logits', question: 'Stable binary classification loss?', answer: '`BCEWithLogitsLoss`' },
  {
    sourceId: 'torch-training-order',
    id: 'torch-training-first-step',
    question: 'First optimizer-loop operation?',
    answer: '`zero_grad`',
    code: 'optimizer.zero_grad(set_to_none=True)\nlogits = model(inputs)\nloss = criterion(logits, targets)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'Which call changes model parameters?',
    codeAnswer: '`optimizer.step`',
  },
  { sourceId: 'torch-training-order', id: 'torch-training-gradient-step', question: 'Which call computes parameter gradients?', answer: '`backward`' },
  { sourceId: 'torch-training-order', id: 'torch-training-update-step', question: 'Which call updates parameters?', answer: '`optimizer.step`' },
  { sourceId: 'torch-amp', id: 'torch-autocast-job', question: 'Which AMP context selects operation dtypes?', answer: '`autocast`' },
  { sourceId: 'torch-amp', id: 'torch-grad-scaler-job', question: 'Which AMP helper protects FP16 gradients from underflow?', answer: '`GradScaler`' },
  {
    sourceId: 'torch-clip-unscale',
    id: 'torch-clip-unscale',
    question: 'Before clipping scaled gradients, first…?',
    answer: 'Unscale',
    code: 'scaler.scale(loss).backward()\nscaler.unscale_(optimizer)\ntorch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\nscaler.step(optimizer)\nscaler.update()',
    codeQuestion: 'Which operation immediately precedes clipping?',
    codeAnswer: '`unscale_`',
  },
  { sourceId: 'torch-gradient-accumulation-loss', id: 'torch-accumulation-loss', question: 'During K-step accumulation, divide each loss by…?', answer: '`K`', acceptedAnswers: ['steps'] },
  { sourceId: 'torch-checkpoint', id: 'torch-checkpoint-model', question: 'Checkpoint field containing learned weights?', answer: 'Model state' },
  {
    sourceId: 'torch-checkpoint',
    id: 'torch-checkpoint-optimizer',
    question: 'Checkpoint field needed to resume Adam moments?',
    answer: 'Optimizer state',
    code: 'torch.save({\n    "model": model.state_dict(),\n    "optimizer": optimizer.state_dict(),\n    "step": step,\n    "scaler": scaler.state_dict(),\n}, checkpoint_path)',
    codeQuestion: 'Which field preserves Adam moment tensors?',
    codeAnswer: '`optimizer`',
  },
  { sourceId: 'torch-dataset-kinds', id: 'torch-map-dataset', question: 'Dataset style with keyed indexing?', answer: 'Map-style' },
  { sourceId: 'torch-dataset-kinds', id: 'torch-iterable-dataset', question: 'Dataset style for a stream?', answer: '`IterableDataset`' },
  { sourceId: 'torch-dataloader-workers', id: 'torch-dataloader-workers', question: '`num_workers > 0` loads data in…?', answer: 'Subprocesses' },
  {
    sourceId: 'torch-pin-memory',
    id: 'torch-pin-memory',
    question: '`pin_memory=True` creates which host memory?',
    answer: 'Page-locked',
    acceptedAnswers: ['pinned memory'],
    code: 'loader = DataLoader(dataset, batch_size=64, pin_memory=True, num_workers=8)\nfor images, target in loader:\n    images = images.to(device, non_blocking=True)',
    codeQuestion: 'Which transfer flag permits host-device overlap?',
    codeAnswer: '`non_blocking`',
  },
  { sourceId: 'torch-persistent-workers', id: 'torch-persistent-workers', question: 'Which flag keeps loader workers alive between epochs?', answer: '`persistent_workers`' },
  { sourceId: 'torch-worker-cuda-tensors', id: 'torch-worker-cuda-tensors', question: 'Should loader workers normally return CUDA tensors?', answer: 'No' },
  { sourceId: 'torch-reproducibility', id: 'torch-manual-seed', question: 'Does `manual_seed` guarantee universal reproducibility?', answer: 'No' },
  { sourceId: 'torch-ddp-data-parallel', id: 'torch-ddp', question: 'Preferred multi-GPU data-parallel wrapper?', answer: 'DDP', acceptedAnswers: ['DistributedDataParallel'] },
  { sourceId: 'torch-ddp-inputs', id: 'torch-ddp-inputs', question: 'Does DDP split input batches automatically?', answer: 'No' },
  {
    sourceId: 'torch-distributed-sampler-epoch',
    id: 'torch-distributed-sampler-epoch',
    question: 'Which call changes each epoch’s coordinated shuffle?',
    answer: '`set_epoch`',
    code: 'for epoch in range(start_epoch, epochs):\n    train_sampler.set_epoch(epoch)\n    train_one_epoch(model, loader, optimizer)',
    codeQuestion: 'How often is `set_epoch` called?',
    codeAnswer: 'Each epoch',
  },
  { sourceId: 'torch-ddp-unused', id: 'torch-ddp-unused', question: 'Which DDP flag detects unused parameters?', answer: '`find_unused_parameters`' },
  { sourceId: 'torch-fsdp', id: 'torch-fsdp', question: 'Which strategy shards parameters, gradients, and optimizer state?', answer: 'FSDP' },
  {
    sourceId: 'torch-compile',
    id: 'torch-compile',
    question: 'Which API compiles PyTorch execution regions?',
    answer: '`torch.compile`',
    acceptedAnswers: ['compile'],
    code: 'model = torch.compile(model, dynamic=False)\n# Keep input shapes stable to reduce recompilation.',
    codeQuestion: 'What shape policy reduces recompilation here?',
    codeAnswer: 'Stable shapes',
  },
  {
    sourceId: 'torch-cuda-async-timing',
    id: 'torch-cuda-async-timing',
    question: 'Reliable CUDA kernel timing primitive?',
    answer: 'CUDA events',
    code: 'start = torch.cuda.Event(enable_timing=True)\nend = torch.cuda.Event(enable_timing=True)\nstart.record(); output = model(batch); end.record()\ntorch.cuda.synchronize()\nlatency_ms = start.elapsed_time(end)',
    codeQuestion: 'What unit does `elapsed_time` return?',
    codeAnswer: 'Milliseconds',
    codeAcceptedAnswers: ['ms'],
  },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-allocated', question: 'CUDA memory backing live tensors?', answer: 'Allocated' },
  { sourceId: 'torch-allocated-reserved', id: 'torch-memory-reserved', question: 'CUDA memory held by the caching allocator?', answer: 'Reserved' },
  { sourceId: 'torch-empty-cache', id: 'torch-empty-cache', question: 'Does `empty_cache()` free live tensor storage?', answer: 'No' },
  { sourceId: 'torch-item-sync', id: 'torch-item-sync', question: 'Frequent accelerator `.item()` calls can cause…?', answer: 'Synchronization', acceptedAnswers: ['sync'] },
  { sourceId: 'torch-optimizer-memory', id: 'torch-adam-state', question: 'Adam keeps how many moment tensors per parameter?', answer: 'Two' },
  {
    sourceId: 'torch-activation-checkpoint',
    id: 'torch-activation-checkpoint',
    question: 'Activation checkpointing trades compute for…?',
    answer: 'Memory',
    code: 'hidden = torch.utils.checkpoint.checkpoint(\n    block, hidden, use_reentrant=False\n)',
    codeQuestion: 'Which pass recomputes discarded activations?',
    codeAnswer: 'Backward',
  },
  { sourceId: 'torch-activation-checkpoint', id: 'torch-checkpoint-reentrant', question: 'Recommended checkpoint variant?', answer: 'Non-reentrant', acceptedAnswers: ['use_reentrant=False'] },
  {
    sourceId: 'torch-ddp-no-sync',
    id: 'torch-ddp-no-sync',
    question: 'DDP context that defers gradient synchronization?',
    answer: '`no_sync`',
    code: 'with ddp_model.no_sync():\n    for microbatch in microbatches[:-1]:\n        loss_fn(ddp_model(microbatch)).backward()\nloss_fn(ddp_model(microbatches[-1])).backward()',
    codeQuestion: 'Which microbatch triggers synchronization?',
    codeAnswer: 'Last',
  },
  {
    sourceId: 'torch-load-weights-only',
    id: 'torch-load-weights-only',
    question: 'Restricted tensor-checkpoint load flag?',
    answer: '`weights_only`',
    code: 'checkpoint = torch.load(path, map_location="cpu", weights_only=True)\nmodel.load_state_dict(checkpoint["model"], strict=True)',
    codeQuestion: 'Where are storages first restored?',
    codeAnswer: 'CPU',
  },
  { sourceId: 'torch-load-map-location', id: 'torch-load-map-location', question: 'Argument that remaps checkpoint devices?', answer: '`map_location`' },
  { sourceId: 'torch-anomaly-detection', id: 'torch-anomaly-detection', question: 'Autograd anomaly detection is for production or debugging?', answer: 'Debugging' },
  {
    sourceId: 'torch-zero-grad-none',
    id: 'torch-zero-grad-none',
    question: 'Preferred low-write `zero_grad` value?',
    answer: '`None`',
    code: 'optimizer.zero_grad(set_to_none=True)\nloss.backward()\noptimizer.step()',
    codeQuestion: 'Unused parameter `.grad` remains…?',
    codeAnswer: '`None`',
  },
  {
    sourceId: 'torch-softmax-dim',
    id: 'torch-softmax-dim',
    question: 'For logits `[B, C]`, class softmax dimension?',
    answer: '`1`',
    acceptedAnswers: ['dim=1'],
    code: 'probabilities = logits.softmax(dim=1)  # logits: [B, C]\nassert torch.allclose(probabilities.sum(dim=1), torch.ones(batch))',
    codeQuestion: 'Which dimension sums to one?',
    codeAnswer: '`1`',
    codeAcceptedAnswers: ['dim=1'],
  },
];
