export const triviaExplanations: Record<string, string> = {
  'torch-shape-metadata': 'A tensor’s shape lists the logical length of each dimension.',
  'torch-stride-metadata': 'Strides tell PyTorch how many storage positions to move when each index increases by one.',
  'torch-offset-metadata': 'The storage offset identifies where the tensor’s first logical element begins in its underlying storage.',
  'torch-view-contract': '`view` can reinterpret shape without copying only when the existing strides support the requested layout.',
  'torch-view-contract-code': '`transpose` changes the stride pattern, and `contiguous()` materializes a dense layout that `view` can use.',
  'torch-reshape-contract': '`reshape` returns a view when possible but may allocate and copy when the strides are incompatible.',
  'torch-transpose-copy': '`transpose` normally returns a view with changed shape and strides over the same storage.',
  'torch-contiguous-copy': '`contiguous()` materializes data in the requested contiguous memory format when needed.',
  'torch-clone-storage': '`clone()` allocates new storage while preserving an autograd connection to the source tensor.',
  'torch-clone-storage-code': '`detach().clone()` creates independent storage, so `target` does not alias `online_output`.',
  'torch-detach-graph': '`detach()` returns a tensor that shares storage but has no incoming autograd history.',
  'torch-broadcast-direction': 'PyTorch compares broadcast dimensions starting from the trailing, or rightmost, side.',
  'torch-broadcast-size': 'Unequal aligned dimensions are compatible only when one of them has size `1`.',
  'torch-cat-rank': '`torch.cat` joins tensors along an existing dimension, so it preserves their rank.',
  'torch-cat-rank-code': 'Concatenating `[B_i, C]` tensors along dimension `0` produces `[sum(B_i), C]`, which is still rank two.',
  'torch-stack-rank': '`torch.stack` creates a new dimension to hold the input tensors, increasing rank by one.',
  'torch-basic-indexing': 'Basic slicing usually changes metadata and returns a view of the same storage.',
  'torch-advanced-indexing': 'Boolean or advanced indexing gathers selected values into newly allocated storage.',
  'torch-inplace-promotion': 'An in-place operation must store its result in the existing destination dtype and cannot freely promote it.',
  'torch-to-noop': 'When device and dtype already match, `Tensor.to(...)` may return the original tensor instead of copying.',
  'torch-empty': '`torch.empty` allocates storage without initializing its values.',
  'torch-grad-recording': 'Autograd normally records operations when at least one relevant input has `requires_grad=True` and grad mode is enabled.',
  'torch-leaf-grad': 'After backpropagation, autograd accumulates gradients into leaf tensors that require gradients by default.',
  'torch-grad-accumulation': 'Each `backward()` adds into an existing `.grad` buffer unless gradients are cleared first.',
  'torch-grad-accumulation-code': 'Dividing every microbatch loss by the number of microbatches makes the accumulated gradient their mean.',
  'torch-none-grad': 'A parameter that has no path to the loss receives no gradient, represented by `.grad is None`.',
  'torch-vjp': '`backward(v)` contracts the output Jacobian with the supplied vector `v`, producing a vector-Jacobian product.',
  'torch-inference-mode': '`torch.inference_mode()` disables autograd bookkeeping more aggressively for pure inference workloads.',
  'torch-no-grad': '`torch.no_grad()` stops recording operations while retaining tensor behavior suitable for later grad-enabled work.',
  'torch-eval-no-grad': '`model.eval()` changes module behavior such as dropout and batch normalization; it does not change autograd mode.',
  'torch-eval-no-grad-code': 'The surrounding `torch.inference_mode()` block disables graph recording for the forward pass.',
  'torch-version-counter': 'Autograd tracks tensor mutations with version counters and rejects backward passes that need an overwritten value.',
  'torch-retain-graph': '`retain_graph=True` keeps saved graph state available for another backward traversal.',
  'torch-create-graph': '`create_graph=True` records the gradient computation itself so higher-order derivatives are possible.',
  'torch-autograd-grad': '`torch.autograd.grad` returns gradients for explicitly requested inputs without relying on leaf `.grad` fields.',
  'torch-tensor-backward': '`backward()` traverses from an output and accumulates results into the `.grad` fields of leaves.',
  'torch-parameter-registration': 'Assigning an `nn.Parameter` to a module registers it for optimization, device moves, and serialization.',
  'torch-module-list': '`nn.ModuleList` registers every contained submodule while still allowing indexed and iterative access.',
  'torch-module-list-code': 'Because the blocks live in a `ModuleList`, recursive parameter discovery includes every block.',
  'torch-parameter-state': 'A parameter is registered trainable state and is returned by `model.parameters()`.',
  'torch-buffer-state': 'A buffer is registered state that moves and serializes with the module but is not optimized by default.',
  'torch-buffer-state-code': 'Optimizers update registered parameters, not buffers such as `class_weights`.',
  'torch-state-dict': 'A module’s `state_dict` contains its parameters and persistent buffers.',
  'torch-load-state-strict': '`strict=True` requires checkpoint keys to match the module’s state keys exactly.',
  'torch-load-state-strict-code': 'The code checks the missing and unexpected key lists and raises when either list is nonempty.',
  'torch-forward-call': 'Calling `model(x)` runs `nn.Module.__call__`, which handles hooks before and after invoking `forward`.',
  'torch-forward-call-code': '`nn.Module.__call__` wraps `forward` and coordinates hooks and other module behavior.',
  'torch-cross-entropy-logits': '`CrossEntropyLoss` combines log-softmax with negative log-likelihood, so pass raw logits.',
  'torch-cross-entropy-target-dtype': 'Class-index targets for cross-entropy use the integer dtype `torch.long`.',
  'torch-cross-entropy-target-rank': 'One class index is needed for each of the `N` rows, giving target shape `[N]`.',
  'torch-bce-logits': '`BCEWithLogitsLoss` combines the sigmoid and binary cross-entropy calculations for numerical stability.',
  'torch-training-first-step': 'Clear gradients before the new iteration because PyTorch accumulates them by default.',
  'torch-training-first-step-code': '`optimizer.step()` reads parameter gradients and applies the parameter update.',
  'torch-training-gradient-step': '`loss.backward()` differentiates the loss and accumulates parameter gradients.',
  'torch-training-update-step': '`optimizer.step()` changes parameters according to their gradients and optimizer state.',
  'torch-autocast-job': '`autocast` chooses lower-precision or full-precision execution per operation within its context.',
  'torch-grad-scaler-job': '`GradScaler` scales FP16 losses and gradients to reduce underflow, then safely unscales before the update.',
  'torch-clip-unscale': 'Scaled gradients must be unscaled before their true norm can be clipped correctly.',
  'torch-clip-unscale-code': '`scaler.unscale_(optimizer)` restores the gradients’ true scale immediately before clipping.',
  'torch-accumulation-loss': 'Divide each microbatch loss by `K` so summing `K` backward passes matches a mean loss gradient.',
  'torch-checkpoint-model': 'The model state contains the learned parameters and persistent buffers needed to reproduce its predictions.',
  'torch-checkpoint-optimizer': 'The optimizer state preserves Adam’s moments and step counters so training can resume faithfully.',
  'torch-checkpoint-optimizer-code': 'The `optimizer` entry stores `optimizer.state_dict()`, including Adam moment tensors.',
  'torch-map-dataset': 'A map-style dataset implements keyed access such as `__getitem__(index)` and usually has a length.',
  'torch-iterable-dataset': 'An `IterableDataset` yields a stream of samples without requiring random indexed access.',
  'torch-dataloader-workers': 'With worker processes enabled, DataLoader fetches and prepares samples in subprocesses.',
  'torch-pin-memory': 'Pinned, or page-locked, host memory enables faster asynchronous transfers to an accelerator.',
  'torch-pin-memory-code': '`non_blocking=True` allows an eligible pinned-memory transfer to overlap with other work.',
  'torch-persistent-workers': '`persistent_workers=True` reuses worker processes instead of restarting them after each epoch.',
  'torch-worker-cuda-tensors': 'Workers should normally return CPU tensors and let the training process perform device transfer.',
  'torch-manual-seed': 'A seed controls supported random streams, but hardware, kernels, libraries, and execution order can still vary.',
  'torch-ddp': '`DistributedDataParallel` runs one model replica per process and synchronizes gradients efficiently.',
  'torch-ddp-inputs': 'DDP synchronizes gradients but expects each process to receive its own input shard.',
  'torch-distributed-sampler-epoch': '`set_epoch(epoch)` changes the shared shuffle seed while keeping ranks coordinated.',
  'torch-distributed-sampler-epoch-code': 'Call `set_epoch` once before iterating the loader in every training epoch.',
  'torch-ddp-unused': '`find_unused_parameters=True` traverses the autograd graph to identify parameters unused in that iteration.',
  'torch-fsdp': 'Fully Sharded Data Parallel partitions parameters, gradients, and optimizer state across ranks.',
  'torch-compile': '`torch.compile` captures and optimizes compatible execution regions of a PyTorch program.',
  'torch-compile-code': 'Keeping input shapes stable reduces the number of specialized graphs that must be compiled.',
  'torch-cuda-async-timing': 'CUDA events record positions in the device stream, making them suitable for asynchronous kernel timing.',
  'torch-cuda-async-timing-code': '`Event.elapsed_time` reports the interval between recorded events in milliseconds.',
  'torch-memory-allocated': 'Allocated memory is storage currently occupied by live tensors.',
  'torch-memory-reserved': 'Reserved memory includes blocks held by PyTorch’s CUDA caching allocator for reuse.',
  'torch-empty-cache': '`empty_cache()` releases unused cached blocks, not storage still owned by live tensors.',
  'torch-item-sync': 'Reading a device scalar on the CPU can force the host to wait for queued accelerator work.',
  'torch-adam-state': 'Adam tracks a first-moment estimate and a second-moment estimate for each parameter.',
  'torch-activation-checkpoint': 'Checkpointing saves memory by discarding selected activations and recomputing them later.',
  'torch-activation-checkpoint-code': 'During backward, PyTorch reruns the checkpointed forward region to recover discarded activations.',
  'torch-checkpoint-reentrant': 'The non-reentrant checkpoint implementation is the recommended modern variant and is selected with `use_reentrant=False`.',
  'torch-ddp-no-sync': '`no_sync()` skips DDP gradient all-reduce inside its context so microbatches can accumulate locally.',
  'torch-ddp-no-sync-code': 'Only the final backward call runs outside `no_sync()`, so that microbatch triggers synchronization.',
  'torch-load-weights-only': '`weights_only=True` restricts unpickling to tensor checkpoints and a limited safe set of types.',
  'torch-load-weights-only-code': '`map_location="cpu"` restores checkpoint storages on the CPU before loading model state.',
  'torch-load-map-location': '`map_location` controls how serialized device locations are remapped during `torch.load`.',
  'torch-anomaly-detection': 'Anomaly detection adds expensive checks and traceback capture, so use it to debug rather than serve or train normally.',
  'torch-zero-grad-none': '`set_to_none=True` avoids zero-fill writes and represents an absent gradient distinctly.',
  'torch-zero-grad-none-code': 'A parameter unused by the loss receives no new gradient, so its `.grad` stays `None`.',
  'torch-softmax-dim': 'For `[B, C]` logits, dimension `1` contains the classes for each batch item.',
  'torch-softmax-dim-code': 'Softmax normalizes the class axis, so each row sums to one along dimension `1`.',
};
