export const triviaExplanations: Record<string, string> = {
  'python-argument-model': 'Python passes a new local reference to the same object; this is commonly called object sharing or pass-by-assignment.',
  'python-argument-model-code': '`tag` mutates the list shared with the caller by appending one item, so its length becomes `1`.',
  'python-argument-mutation': 'Yes. If a function mutates a shared mutable object, the caller observes that change.',
  'python-argument-rebinding': 'No. Reassigning a parameter changes only the function’s local name, not the caller’s name.',
  'python-is-operator': '`is` checks whether two names refer to the exact same object.',
  'python-is-operator-code': '`dict.get` returns `None` here when the key is absent, and `is None` tests for that exact singleton.',
  'python-equality-operator': '`==` asks whether two objects have equal values.',
  'python-mutable-default': 'Use `None` as the default, then create a new mutable object inside the function.',
  'python-mutable-default-code': 'The function creates a new list whenever `items` is `None`, so omitted arguments do not share a list.',
  'python-default-evaluation': 'Python evaluates a default expression once when the `def` statement runs, not on every call.',
  'python-shallow-copy': 'A shallow copy creates a new outer container but keeps references to the same nested objects.',
  'python-deep-copy': 'A deep copy recursively copies nested objects instead of preserving their aliases.',
  'python-assignment-copy': '`b = a` only binds another name to the same object; it does not create a copy.',
  'python-tuple-deep-immutable': 'A tuple’s slots cannot be reassigned, but a mutable object stored in a slot can still change.',
  'python-tuple-list-hashable': 'A tuple is hashable only when every element is hashable; a list is not hashable.',
  'python-empty-list-truthiness': 'An empty list is falsy, so `bool([])` returns `False`.',
  'python-string-false-truthiness': 'Any nonempty string is truthy; its characters do not receive special Boolean interpretation.',
  'python-zero-truthiness': 'Numeric zero is falsy, so `bool(0)` returns `False`.',
  'python-nan-truthiness': 'A float is falsy only when it is zero; NaN is therefore truthy.',
  'python-sort-return': '`list.sort()` mutates the list in place and deliberately returns `None`.',
  'python-sort-return-code': '`records.sort(...)` changes the existing `records` list, so that variable keeps the original list identity.',
  'python-sorted-copy': '`sorted(iterable)` reads the input and returns a new sorted list.',
  'python-identity-interning': 'Use equality for string values; identity can vary because interning is an implementation detail.',
  'python-iterable-method': '`iter(obj)` asks an iterable to produce an iterator.',
  'python-iterator-method': '`__next__()` returns the next item or raises `StopIteration` when exhausted.',
  'python-generator-single-use': 'A completed generator stays exhausted; iterate a newly created generator to run it again.',
  'python-yield-action': '`yield` emits a value while preserving the function frame for later resumption.',
  'python-return-action': '`return` ends the function immediately and supplies its final return value.',
  'python-list-comprehension-mode': 'A list comprehension computes every item immediately and stores the resulting list.',
  'python-generator-expression-mode': 'A generator expression computes each item only when iteration requests it.',
  'python-next-default': 'When the iterator is exhausted, the two-argument form of `next` returns the supplied fallback instead of raising.',
  'python-next-default-code': 'The generator finds no matching row, so `next(..., None)` assigns its fallback, `None`.',
  'python-yield-from': '`yield from` forwards iteration to another iterable or generator.',
  'python-legb': 'Python resolves an unqualified name through Local, Enclosing, Global, then Built-in scopes.',
  'python-late-binding': 'Closures normally look up a captured loop variable when called, after the loop has advanced.',
  'python-late-binding-code': 'The default argument `i=i` stores the current value during each iteration, so the first handler captures `0`.',
  'python-global-binding': '`global` makes assignments target a name in the module namespace.',
  'python-nonlocal-binding': '`nonlocal` makes assignments target an existing name in an enclosing function scope.',
  'python-loop-scope': 'A `for` statement does not create a new local scope, so its loop variable remains available afterward.',
  'python-comprehension-scope': 'In Python 3, a comprehension’s loop variable is local to the comprehension.',
  'python-positional-only-marker': 'Parameters before `/` must be passed by position.',
  'python-positional-only-marker-code': '`timeout_s` appears after `*`, so callers must write it as a keyword argument.',
  'python-keyword-only-marker': 'Parameters after `*` must be supplied by keyword.',
  'python-args-type': 'Extra positional arguments are collected into a tuple named `args` by convention.',
  'python-kwargs-type': 'Extra keyword arguments are collected into a dictionary named `kwargs` by convention.',
  'python-decorator-timing': 'Python applies a function decorator when the decorated function is defined.',
  'python-wraps-purpose': '`functools.wraps` copies metadata such as `__name__` and `__doc__` to the wrapper.',
  'python-wraps-purpose-code': 'The `@wraps(fn)` decorator preserves the wrapped function’s name on `wrapper`.',
  'python-hashability': 'Dictionary keys must have a stable hash and compatible equality behavior.',
  'python-dict-complexity': 'A dictionary uses a hash table, giving average-case constant-time lookup.',
  'python-dict-complexity-code': '`users_by_id[event.user_id]` is a hash-table lookup, so its average complexity is `O(1)`.',
  'python-dict-order': 'Modern Python dictionaries iterate keys in insertion order.',
  'python-list-append': 'Dynamic-array resizing is occasional, so `append` is `O(1)` when averaged across many calls.',
  'python-deque': '`collections.deque` supports efficient appends and removals at both ends.',
  'python-deque-code': 'A deque removes its leftmost item in amortized `O(1)` time.',
  'python-set-mutability': 'A `set` can add and remove unique elements after construction.',
  'python-frozenset-hashable': 'A `frozenset` cannot change, so it can be hashable when its elements are hashable.',
  'python-class-attribute-sharing': 'A mutable class attribute is stored on the class and shared by instances that do not override it.',
  'python-instance-attribute': 'Assigning through `self` stores an attribute on that particular instance.',
  'python-instance-attribute-code': '`self.queue` is assigned during initialization, so each `Worker` instance owns its value.',
  'python-self-method': 'A normal instance method receives the bound instance as its first argument, conventionally `self`.',
  'python-cls-method': 'A method decorated with `@classmethod` receives the class as `cls`.',
  'python-cls-method-code': '`from_env` builds and returns an instance through `cls`, making it an alternative constructor.',
  'python-static-method': 'A static method is namespaced on the class but receives no automatic instance or class argument.',
  'python-super-mro': 'Zero-argument `super()` continues method lookup along the class’s method resolution order.',
  'python-new-role': '`__new__` allocates and returns the new instance before initialization.',
  'python-init-role': '`__init__` configures an instance that `__new__` has already created.',
  'python-slots': '`__slots__` declares permitted instance attributes and can avoid a per-instance attribute dictionary.',
  'python-descriptor': 'Descriptors customize attribute access through methods such as `__get__`, `__set__`, and `__delete__`.',
  'python-eq-hash': 'When equality becomes value-based, Python disables the inherited identity hash unless a compatible hash is defined.',
  'python-not-implemented-value': 'Returning `NotImplemented` lets Python try the reflected operation or report an unsupported operand pair.',
  'python-not-implemented-error': 'Raise `NotImplementedError` when a method is intentionally left for a subclass to implement.',
  'python-bare-except': 'A bare `except:` catches `BaseException`, including interrupts and system-exit signals.',
  'python-exception-chaining': '`raise NewError(...) from exc` records `exc` as the explicit cause.',
  'python-exception-chaining-code': 'Explicit exception chaining stores the original exception in `__cause__`.',
  'python-suppress-context': '`raise ... from None` hides the automatically attached exception context in the traceback display.',
  'python-context-manager': 'Returning a truthy value from `__exit__` tells the `with` statement that the exception was handled.',
  'python-context-manager-code': 'The context manager’s `__exit__` method runs at the boundary and performs commit, rollback, or cleanup.',
  'python-finally': 'Before control leaves a `try`, its `finally` block runs even when a return is already pending.',
  'python-eafp': 'EAFP means attempting the operation and catching the specific expected exception.',
  'python-lbyl': 'LBYL means checking required conditions before attempting the operation.',
  'python-gil': 'The traditional CPython GIL allows only one thread at a time to execute Python bytecode in a process.',
  'python-threads-use': 'Threads share process memory and work well when blocking I/O releases execution time.',
  'python-processes-use': 'Separate processes can execute CPU work in parallel and isolate their memory.',
  'python-asyncio-use': '`asyncio` multiplexes many tasks that cooperatively yield while waiting for I/O.',
  'python-blocking-async': 'Blocking work prevents the event-loop thread from scheduling other coroutines.',
  'python-blocking-async-code': '`asyncio.to_thread` moves the blocking client call to a worker thread.',
  'python-race-gil': 'The GIL does not make a multi-step shared-state operation atomic or logically race-free.',
  'python-reference-counting': 'CPython usually releases an object when its reference count reaches zero.',
  'python-cycle-collector': 'The cyclic garbage collector detects unreachable cycles that reference counting alone cannot reclaim.',
  'python-import-cache': 'The import system reuses module objects recorded by name in `sys.modules`.',
  'python-any-checking': '`Any` tells a static type checker to permit almost any operation without proving its safety.',
  'python-object-checking': '`object` can hold any Python value, but a type checker requires narrowing before type-specific operations.',
  'python-protocol': 'A protocol accepts any type with the required members, without requiring explicit inheritance.',
  'python-protocol-code': 'An object satisfies this `Encoder` protocol when it provides a compatible `encode` method.',
  'python-dataclass-generated': '`@dataclass` can generate methods such as `__init__`, `__repr__`, and `__eq__` from declared fields.',
  'python-dataclass-validation': 'Standard dataclass annotations guide tools but are not checked when an instance is constructed.',
  'python-dataclass-default-factory': '`field(default_factory=list)` calls `list` separately for each new instance.',
  'python-dataclass-default-factory-code': 'Each `Batch` construction calls the factory, so the instances receive different lists.',
  'python-pydantic-validation': 'A Pydantic dataclass validates constructor input and can coerce compatible values in its default lax mode. Strict rejection is configurable—not the default.',
  'python-pydantic-validation-code': 'Pydantic converts the string `"2.5"` to a floating-point value in lax mode.',
  'python-stdlib-validation': 'A standard dataclass stores constructor values without enforcing its type annotations at runtime.',
  'python-pydantic-strict': 'Pydantic uses coercive lax validation by default; strict rejection must be configured.',
  'python-pydantic-strict-code': 'With strict mode enabled, the string `"3"` is rejected instead of being converted to an integer.',
  'python-pydantic-primary-api': '`BaseModel` is Pydantic’s main model abstraction and exposes its full validation and serialization API.',
  'python-frozen-depth': '`frozen=True` blocks field assignment, but it does not freeze mutable objects stored in those fields.',
  'python-frozen-effect': 'A frozen dataclass prevents assigning a different value to one of its fields.',
  'python-task-group': '`asyncio.TaskGroup` owns a related set of child tasks within one structured lifetime.',
  'python-task-group-code': 'Leaving the `async with` block waits until every child task has finished or been cancelled.',
  'python-task-group-failure': 'If one child fails, the task group cancels its remaining unfinished siblings before exiting.',
  'python-cancelled-error-base': '`asyncio.CancelledError` derives directly from `BaseException`, so broad `except Exception` handlers do not catch it.',
  'python-cancelled-error-action': 'After cleanup, re-raise cancellation so the task still reports that it was cancelled.',
  'python-cancelled-error-action-code': 'A bare `raise` inside the handler re-raises the active `CancelledError`.',
  'python-contextvar': '`ContextVar` keeps a value local to the current asynchronous context instead of sharing one global value.',
  'python-contextvar-code': '`set` returns a token containing the previous state; passing it to `reset` restores that state.',
  'python-lru-cache-hashable': '`lru_cache` uses the call arguments as a dictionary key, so every argument must be hashable.',
  'python-exception-group': '`except*` selects matching exceptions from an `ExceptionGroup` while preserving the remaining subgroup.',

  'torch-shape-metadata': 'A tensor’s shape lists the logical length of each dimension.',
  'torch-stride-metadata': 'Strides tell PyTorch how many storage positions to move when each index increases by one.',
  'torch-offset-metadata': 'The storage offset identifies where the tensor’s first logical element begins in its underlying storage.',
  'torch-view-contract': '`view` can reinterpret shape without copying only when the existing strides support the requested layout.',
  'torch-view-contract-code': '`transpose` changes the stride pattern, and `contiguous()` materializes a dense layout that `view` can use.',
  'torch-reshape-contract': '`reshape` returns a view when possible but may allocate and copy when the strides are incompatible.',
  'torch-transpose-copy': '`transpose` normally returns a view with changed shape and strides over the same storage.',
  'torch-contiguous-copy': '`contiguous()` materializes data in the requested contiguous memory format when needed.',
  'torch-clone-storage': '`clone()` allocates new storage while preserving an autograd connection to the source tensor.',
  'torch-clone-storage-code': '`detach().clone()` creates independent storage, so `target` does not alias `online_output`.',
  'torch-detach-graph': '`detach()` returns a tensor that shares storage but has no incoming autograd history.',
  'torch-broadcast-direction': 'PyTorch compares broadcast dimensions starting from the trailing, or rightmost, side.',
  'torch-broadcast-size': 'Unequal aligned dimensions are compatible only when one of them has size `1`.',
  'torch-cat-rank': '`torch.cat` joins tensors along an existing dimension, so it preserves their rank.',
  'torch-cat-rank-code': 'Concatenating `[B_i, C]` tensors along dimension `0` produces `[sum(B_i), C]`, which is still rank two.',
  'torch-stack-rank': '`torch.stack` creates a new dimension to hold the input tensors, increasing rank by one.',
  'torch-basic-indexing': 'Basic slicing usually changes metadata and returns a view of the same storage.',
  'torch-advanced-indexing': 'Boolean or advanced indexing gathers selected values into newly allocated storage.',
  'torch-inplace-promotion': 'An in-place operation must store its result in the existing destination dtype and cannot freely promote it.',
  'torch-to-noop': 'When device and dtype already match, `Tensor.to(...)` may return the original tensor instead of copying.',
  'torch-empty': '`torch.empty` allocates storage without initializing its values.',
  'torch-grad-recording': 'Autograd normally records operations when at least one relevant input has `requires_grad=True` and grad mode is enabled.',
  'torch-leaf-grad': 'After backpropagation, autograd accumulates gradients into leaf tensors that require gradients by default.',
  'torch-grad-accumulation': 'Each `backward()` adds into an existing `.grad` buffer unless gradients are cleared first.',
  'torch-grad-accumulation-code': 'Dividing every microbatch loss by the number of microbatches makes the accumulated gradient their mean.',
  'torch-none-grad': 'A parameter that has no path to the loss receives no gradient, represented by `.grad is None`.',
  'torch-vjp': '`backward(v)` contracts the output Jacobian with the supplied vector `v`, producing a vector-Jacobian product.',
  'torch-inference-mode': '`torch.inference_mode()` disables autograd bookkeeping more aggressively for pure inference workloads.',
  'torch-no-grad': '`torch.no_grad()` stops recording operations while retaining tensor behavior suitable for later grad-enabled work.',
  'torch-eval-no-grad': '`model.eval()` changes module behavior such as dropout and batch normalization; it does not change autograd mode.',
  'torch-eval-no-grad-code': 'The surrounding `torch.inference_mode()` block disables graph recording for the forward pass.',
  'torch-version-counter': 'Autograd tracks tensor mutations with version counters and rejects backward passes that need an overwritten value.',
  'torch-retain-graph': '`retain_graph=True` keeps saved graph state available for another backward traversal.',
  'torch-create-graph': '`create_graph=True` records the gradient computation itself so higher-order derivatives are possible.',
  'torch-autograd-grad': '`torch.autograd.grad` returns gradients for explicitly requested inputs without relying on leaf `.grad` fields.',
  'torch-tensor-backward': '`backward()` traverses from an output and accumulates results into the `.grad` fields of leaves.',
  'torch-parameter-registration': 'Assigning an `nn.Parameter` to a module registers it for optimization, device moves, and serialization.',
  'torch-module-list': '`nn.ModuleList` registers every contained submodule while still allowing indexed and iterative access.',
  'torch-module-list-code': 'Because the blocks live in a `ModuleList`, recursive parameter discovery includes every block.',
  'torch-parameter-state': 'A parameter is registered trainable state and is returned by `model.parameters()`.',
  'torch-buffer-state': 'A buffer is registered state that moves and serializes with the module but is not optimized by default.',
  'torch-buffer-state-code': 'Optimizers update registered parameters, not buffers such as `class_weights`.',
  'torch-state-dict': 'A module’s `state_dict` contains its parameters and persistent buffers.',
  'torch-load-state-strict': '`strict=True` requires checkpoint keys to match the module’s state keys exactly.',
  'torch-load-state-strict-code': 'The code checks the missing and unexpected key lists and raises when either list is nonempty.',
  'torch-forward-call': 'Calling `model(x)` runs `nn.Module.__call__`, which handles hooks before and after invoking `forward`.',
  'torch-forward-call-code': '`nn.Module.__call__` wraps `forward` and coordinates hooks and other module behavior.',
  'torch-cross-entropy-logits': '`CrossEntropyLoss` combines log-softmax with negative log-likelihood, so pass raw logits.',
  'torch-cross-entropy-target-dtype': 'Class-index targets for cross-entropy use the integer dtype `torch.long`.',
  'torch-cross-entropy-target-rank': 'One class index is needed for each of the `N` rows, giving target shape `[N]`.',
  'torch-bce-logits': '`BCEWithLogitsLoss` combines the sigmoid and binary cross-entropy calculations for numerical stability.',
  'torch-training-first-step': 'Clear gradients before the new iteration because PyTorch accumulates them by default.',
  'torch-training-first-step-code': '`optimizer.step()` reads parameter gradients and applies the parameter update.',
  'torch-training-gradient-step': '`loss.backward()` differentiates the loss and accumulates parameter gradients.',
  'torch-training-update-step': '`optimizer.step()` changes parameters according to their gradients and optimizer state.',
  'torch-autocast-job': '`autocast` chooses lower-precision or full-precision execution per operation within its context.',
  'torch-grad-scaler-job': '`GradScaler` scales FP16 losses and gradients to reduce underflow, then safely unscales before the update.',
  'torch-clip-unscale': 'Scaled gradients must be unscaled before their true norm can be clipped correctly.',
  'torch-clip-unscale-code': '`scaler.unscale_(optimizer)` restores the gradients’ true scale immediately before clipping.',
  'torch-accumulation-loss': 'Divide each microbatch loss by `K` so summing `K` backward passes matches a mean loss gradient.',
  'torch-checkpoint-model': 'The model state contains the learned parameters and persistent buffers needed to reproduce its predictions.',
  'torch-checkpoint-optimizer': 'The optimizer state preserves Adam’s moments and step counters so training can resume faithfully.',
  'torch-checkpoint-optimizer-code': 'The `optimizer` entry stores `optimizer.state_dict()`, including Adam moment tensors.',
  'torch-map-dataset': 'A map-style dataset implements keyed access such as `__getitem__(index)` and usually has a length.',
  'torch-iterable-dataset': 'An `IterableDataset` yields a stream of samples without requiring random indexed access.',
  'torch-dataloader-workers': 'With worker processes enabled, DataLoader fetches and prepares samples in subprocesses.',
  'torch-pin-memory': 'Pinned, or page-locked, host memory enables faster asynchronous transfers to an accelerator.',
  'torch-pin-memory-code': '`non_blocking=True` allows an eligible pinned-memory transfer to overlap with other work.',
  'torch-persistent-workers': '`persistent_workers=True` reuses worker processes instead of restarting them after each epoch.',
  'torch-worker-cuda-tensors': 'Workers should normally return CPU tensors and let the training process perform device transfer.',
  'torch-manual-seed': 'A seed controls supported random streams, but hardware, kernels, libraries, and execution order can still vary.',
  'torch-ddp': '`DistributedDataParallel` runs one model replica per process and synchronizes gradients efficiently.',
  'torch-ddp-inputs': 'DDP synchronizes gradients but expects each process to receive its own input shard.',
  'torch-distributed-sampler-epoch': '`set_epoch(epoch)` changes the shared shuffle seed while keeping ranks coordinated.',
  'torch-distributed-sampler-epoch-code': 'Call `set_epoch` once before iterating the loader in every training epoch.',
  'torch-ddp-unused': '`find_unused_parameters=True` traverses the autograd graph to identify parameters unused in that iteration.',
  'torch-fsdp': 'Fully Sharded Data Parallel partitions parameters, gradients, and optimizer state across ranks.',
  'torch-compile': '`torch.compile` captures and optimizes compatible execution regions of a PyTorch program.',
  'torch-compile-code': 'Keeping input shapes stable reduces the number of specialized graphs that must be compiled.',
  'torch-cuda-async-timing': 'CUDA events record positions in the device stream, making them suitable for asynchronous kernel timing.',
  'torch-cuda-async-timing-code': '`Event.elapsed_time` reports the interval between recorded events in milliseconds.',
  'torch-memory-allocated': 'Allocated memory is storage currently occupied by live tensors.',
  'torch-memory-reserved': 'Reserved memory includes blocks held by PyTorch’s CUDA caching allocator for reuse.',
  'torch-empty-cache': '`empty_cache()` releases unused cached blocks, not storage still owned by live tensors.',
  'torch-item-sync': 'Reading a device scalar on the CPU can force the host to wait for queued accelerator work.',
  'torch-adam-state': 'Adam tracks a first-moment estimate and a second-moment estimate for each parameter.',
  'torch-activation-checkpoint': 'Checkpointing saves memory by discarding selected activations and recomputing them later.',
  'torch-activation-checkpoint-code': 'During backward, PyTorch reruns the checkpointed forward region to recover discarded activations.',
  'torch-checkpoint-reentrant': 'The non-reentrant checkpoint implementation is the recommended modern variant and is selected with `use_reentrant=False`.',
  'torch-ddp-no-sync': '`no_sync()` skips DDP gradient all-reduce inside its context so microbatches can accumulate locally.',
  'torch-ddp-no-sync-code': 'Only the final backward call runs outside `no_sync()`, so that microbatch triggers synchronization.',
  'torch-load-weights-only': '`weights_only=True` restricts unpickling to tensor checkpoints and a limited safe set of types.',
  'torch-load-weights-only-code': '`map_location="cpu"` restores checkpoint storages on the CPU before loading model state.',
  'torch-load-map-location': '`map_location` controls how serialized device locations are remapped during `torch.load`.',
  'torch-anomaly-detection': 'Anomaly detection adds expensive checks and traceback capture, so use it to debug rather than serve or train normally.',
  'torch-zero-grad-none': '`set_to_none=True` avoids zero-fill writes and represents an absent gradient distinctly.',
  'torch-zero-grad-none-code': 'A parameter unused by the loss receives no new gradient, so its `.grad` stays `None`.',
  'torch-softmax-dim': 'For `[B, C]` logits, dimension `1` contains the classes for each batch item.',
  'torch-softmax-dim-code': 'Softmax normalizes the class axis, so each row sums to one along dimension `1`.',
};
