author: "Arunabh Mishra"
description: "A personal blog on computer vision, robotics, and more."
email: "arunabh1904@gmail.com"
twitter_username: "ArunabhMishra8"
github_username: "arunabh1904"
linkedin_username: "arunabh-mishra"

theme: "minima"
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    disable: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Remove or comment out if you don't want H1 headings to become page titles:
# titles_from_headings:
#   strip_title: true
#   collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: content
      tags: Other

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

paginate: 5
paginate_path: "/page:num"
